const SUPABASE_URL = 'https://ulxfsozdryqrnlxzlblt.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_9hmWZwV5WnfQHDK1ir36Pg_JIdHdwPq';
const __qrRoleMatch = location.pathname.toLowerCase().match(/\/(admin|manager|cook|courier|waiter)\.html$/i);
const __qrRole = __qrRoleMatch ? __qrRoleMatch[1].toLowerCase() : 'public';
const __qrAuthStorage = window.sessionStorage;
const __qrAuthKey = 'qr-menu-auth-' + __qrRole;
const baseDb = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true, storage: __qrAuthStorage, storageKey: __qrAuthKey } });
window.db = baseDb;
(function(){
'use strict';
var path=location.pathname.toLowerCase(),isMenu=/\/menu\.html$/i.test(path),staffMatch=path.match(/\/(cook|courier|waiter)\.html$/i),isStaff=!!staffMatch,staffType=isStaff?staffMatch[1]:null,real=baseDb,oldFrom=real.from.bind(real),oldRpc=real.rpc.bind(real);
function staffToken(){if(window.StaffAuth&&window.StaffAuth.token())return window.StaffAuth.token();if(staffType){var t=sessionStorage.getItem(staffType+'_token');if(t)return t;}return sessionStorage.getItem('staff_token');}
function rememberStaffLogin(type,data){if(window.StaffAuth&&data)window.StaffAuth.login(type,data);if(data&&data.token)try{localStorage.setItem('staff_token',data.token);localStorage.setItem(type+'_token',data.token);sessionStorage.setItem(type+'_session',JSON.stringify({venueId:data.venueId,venueName:data.venueName,staffName:data.staffName,token:data.token}));}catch(e){}}
function resolveQrTable(venueId){var token=new URLSearchParams(location.search).get('token');if(!token)return Promise.resolve(null);if(window.__qrTable&&window.__qrTable.qr_token===token)return Promise.resolve(window.__qrTable);var q=oldFrom('venue_tables').select('id,venue_id,table_number,name,qr_token,is_active').eq('qr_token',String(token).trim()).eq('is_active',true);if(venueId)q=q.eq('venue_id',venueId);return q.maybeSingle().then(function(r){if(!r.error&&r.data)window.__qrTable=r.data;return r.data||null;});}
function makeChain(table){var state={action:'select',filters:{},inFilters:{},neqFilters:{},payload:null};var api={select:function(){state.action='select';return api;},insert:function(v){state.action='insert';state.payload=v;return api;},update:function(v){state.action='update';state.payload=v;return api;},delete:function(){state.action='delete';return api;},eq:function(k,v){state.filters[k]=v;return api;},neq:function(k,v){state.neqFilters[k]=v;return api;},in:function(k,v){state.inFilters[k]=v;return api;},order:function(){return api;},limit:function(){return api;},maybeSingle:function(){return execute(true);},single:function(){return execute(true);},then:function(a,b){return execute(false).then(a,b);},catch:function(a){return execute(false).catch(a);}};
async function execute(single){
if(isStaff&&table==='venues'&&state.filters.slug){var r=await oldRpc('staff_venue_by_slug',{p_slug:String(state.filters.slug).trim().toLowerCase()});return{data:r.error?null:r.data,error:r.error||null};}
if(isStaff&&['cooks','waiters','couriers'].indexOf(table)>=0&&state.filters.venue_id&&state.filters.pin){var type=table==='cooks'?'cook':table==='waiters'?'waiter':'courier',ctx=JSON.parse(sessionStorage.getItem(type+'_login_context')||'null')||{},r2=await oldRpc('staff_login',{p_type:type,p_slug:ctx.slug||'',p_pin:String(state.filters.pin)});if(r2.error)return{data:null,error:r2.error};rememberStaffLogin(type,r2.data);return{data:r2.data?{id:r2.data.staffId,name:r2.data.staffName,venue_id:r2.data.venueId,token:r2.data.token}:null,error:null};}
if(isStaff&&table==='orders'&&state.action==='select'){var token=staffToken();if(!token)return{data:[],error:new Error('staff_session_missing')};var r3=await oldRpc((state.filters.cook_name||state.filters.waiter_name||state.filters.courier_name)?'staff_history_json':'staff_orders_json',{p_token:token});var rows=Array.isArray(r3.data)?r3.data:[];return{data:single?(rows[0]||null):rows,error:r3.error||null};}
if(isStaff&&table==='orders'&&state.action==='update'){var token2=staffToken();if(!token2)return{data:null,error:new Error('staff_session_missing')};var r4=await oldRpc('staff_update_order',{p_token:token2,p_order_id:state.filters.id,p_status:state.payload&&state.payload.status});return{data:r4.data||null,error:r4.error||null};}
if(isMenu&&table==='orders'&&state.action==='select'){var venueId=state.filters.venue_id,phone=state.filters.customer_phone||localStorage.getItem('last_phone')||'';if(!venueId||!phone)return{data:null,error:new Error('tracking_context_missing')};var r5=await oldRpc('customer_track_order_json',{p_venue_id:venueId,p_customer_phone:String(phone).trim()});return{data:single?(r5.data||null):(r5.data?[r5.data]:[]),error:r5.error||null};}
if(isMenu&&table==='orders'&&state.action==='update')return oldRpc('customer_change_order_status',{p_order_id:state.filters.id,p_customer_phone:localStorage.getItem('last_phone')||'',p_status:state.payload&&state.payload.status});
var q=oldFrom(table)[state.action](state.action==='select'?'*':state.payload);if(state.action!=='insert'){for(var k in state.filters)q=q.eq(k,state.filters[k]);for(var k2 in state.inFilters)q=q.in(k2,state.inFilters[k2]);for(var k3 in state.neqFilters)q=q.neq(k3,state.neqFilters[k3]);}return single&&state.action==='select'?q.maybeSingle():q;
}
return api;}
function rpc(name,args,options){if(name==='create_public_order'&&args&&typeof args==='object'){var token=new URLSearchParams(location.search).get('token');if(token)args=Object.assign({},args,{p_table_token:String(token).trim()});}return oldRpc(name,args,options);}
window.db={from:function(table){if(isStaff||isMenu&&table==='orders')return makeChain(table);return oldFrom(table);},rpc:rpc,auth:real.auth,storage:real.storage};
async function bootQrTable(){if(!isMenu)return;var token=new URLSearchParams(location.search).get('token');if(!token)return;var t=await resolveQrTable(null);if(!t)return;localStorage.setItem('qr_table_id',t.id);localStorage.setItem('qr_table_number',String(t.table_number));localStorage.setItem('qr_table_name',t.name||('Стол '+t.table_number));}
if(isMenu){bootQrTable();}
if(isStaff){setInterval(async function(){var token=staffToken();if(token){var r=await oldRpc('staff_orders_json',{p_token:token});if(!r.error&&Array.isArray(r.data))window.__staffTableOrders=r.data;}},3000);}
})();
(function(){'use strict';var p=location.pathname.toLowerCase();function load(src,key){if(document.querySelector('script['+key+']'))return;var s=document.createElement('script');s.src=src;s.async=false;s.setAttribute(key,'1');document.head.appendChild(s)}if(/\/admin\.html$/i.test(p))load('/js/admin-design-access.js?v=1','data-admin-design-access');if(/\/manager\.html$/i.test(p))load('/js/manager-staff-statistics.js?v=9','data-manager-staff-stats');if(/\/menu\.html$/i.test(p))load('/js/design-runtime.js?v=4','data-design-runtime');if(/\/(cook|waiter|courier)\.html$/i.test(p))load('/js/staff-workday.js?v=4','data-staff-workday');if(/\/waiter\.html$/i.test(p))load('/js/waiter-history-inline.js?v=1','data-waiter-history-inline');if(/\/menu\.html$/i.test(p))load('/js/customer-order-live.js?v=4','data-customer-order-live');})();
