(function(){
'use strict';
if(!/\/menu\.html$/i.test(location.pathname))return;
if(window.__designRuntimeLoaded)return;window.__designRuntimeLoaded=true;
function hex(v,f){var s=String(v==null?'':v).trim();return /^#[0-9A-Fa-f]{6}$/.test(s)?s:f}
function normalizeFont(v){return String(v==null?'':v).trim().replace(/\+/g,' ')||'Plus Jakarta Sans'}
function apply(v){if(!v)return;var d=v.design_settings||{},root=document.documentElement,body=document.body;var brand=hex(d.brand_color,v.brand_color||'#6366f1'),button=hex(d.button_color,'#8b5cf6'),header=hex(d.header_color,'#ffffff');root.style.setProperty('--brand',brand);root.style.setProperty('--design-button',button);root.style.setProperty('--design-header',header);root.style.setProperty('--design-card-radius',(Number(d.card_radius)||18)+'px');root.style.setProperty('--design-button-radius',(Number(d.button_radius)||12)+'px');var font=normalizeFont(d.font_family);var old=document.getElementById('design-runtime-font');if(old)old.remove();var link=document.createElement('link');link.id='design-runtime-font';link.rel='stylesheet';link.href='https://fonts.googleapis.com/css2?family='+encodeURIComponent(font).replace(/%20/g,'+')+':wght@400;600;700;800&display=swap';document.head.appendChild(link);body.style.fontFamily=font+',sans-serif';var hero=document.querySelector('.hero');if(hero){hero.style.display=d.hero_enabled===false?'none':'';hero.style.background=heroBg(d,brand,header)}document.querySelectorAll('.dish').forEach(function(x){x.style.borderRadius=(Number(d.card_radius)||18)+'px';if(d.card_style==='flat'){x.style.background='transparent';x.style.border='1px solid rgba(148,163,184,.18)'}else if(d.card_style==='bold'){x.style.background='linear-gradient(145deg,rgba(255,255,255,.08),rgba(255,255,255,.02))';x.style.border='1px solid '+brand+'66'}else if(d.card_style==='soft'){x.style.background='rgba(255,255,255,.045)';x.style.border='1px solid rgba(255,255,255,.08)'}else{x.style.background='rgba(255,255,255,.035)';x.style.border='1px solid rgba(255,255,255,.08)';x.style.backdropFilter='blur(10px)'}});document.querySelectorAll('.add-btn').forEach(function(x){x.style.borderRadius=(Number(d.button_radius)||12)+'px';x.style.background=d.button_style==='solid'?button:d.button_style==='outline'?'transparent':'linear-gradient(90deg,'+brand+','+button);if(d.button_style==='outline'){x.style.border='1px solid '+button;x.style.color=button}else{x.style.border='none';x.style.color='#fff'}});document.querySelectorAll('.chip.on').forEach(function(x){x.style.background='linear-gradient(90deg,'+brand+','+button)});document.querySelectorAll('.price-pill').forEach(function(x){x.style.background='linear-gradient(90deg,'+brand+','+button)});var top=document.querySelector('.topbar');if(top)top.style.borderColor=brand+'33'}
function heroBg(d,b,h){if(d.hero_style==='dark')return 'linear-gradient(135deg,#020617,'+b+')';if(d.hero_style==='warm')return 'linear-gradient(135deg,'+b+','+h+')';if(d.hero_style==='minimal')return h;return 'linear-gradient(135deg,'+b+','+b+'aa,#8b5cf6)'}
function boot(){var n=0,t=setInterval(function(){var app=document.getElementById('app'),inst=app&&app.__vue_app__&&app.__vue_app__._instance,proxy=inst&&inst.proxy;if(proxy&&proxy.venue){apply(proxy.venue);clearInterval(t)}if(++n>80)clearInterval(t)},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();