(function(){'use strict';
var cfg={
 quick_resto:{title:'Quick Resto',endpoint:'/api/integrations/pos',fields:[['base_url','URL API Quick Resto','https://...'],['login','API логин','Логин API Quick Resto'],['password','API пароль','Пароль API Quick Resto']],note:'Quick Resto указывает логин и пароль API в настройках предприятия. URL API должен соответствовать доступу, предоставленному Quick Resto.'},
 r_keeper:{title:'r_keeper',endpoint:'/api/integrations/pos',fields:[['base_url','URL API / White Server','https://...'],['client_id','Client ID','Client ID подключения'],['client_secret','Client Secret','Client Secret подключения'],['object_id','ID объекта ресторана','например 199994335']],note:'Для r_keeper используется API подключения. В официальной документации получение меню выполняется через menutree и dishes для конкретного objectId.'},
 onec:{title:'1С',fields:[['base_url','URL HTTP-сервиса 1С','https://.../hs/...'],['login','Логин','Логин HTTP-сервиса'],['password','Пароль HTTP-сервиса','Пароль HTTP-сервиса']],note:'Для 1С используется HTTP-обмен. URL и учётные данные предоставляет администратор 1С.'},
 poster:{title:'Poster',fields:[['account','Поддомен аккаунта','myrestaurant'],['token','API token','API token Poster']],note:'Poster предоставляет API для сторонних приложений.'},
 evotor:{title:'Эвотор',fields:[['client_id','Client ID','ID приложения'],['client_secret','Client Secret','Секрет приложения']],note:'Эвотор использует OAuth 2.0.'},
 tillypad:{title:'Tillypad',fields:[['base_url','URL шлюза','https://...'],['login','Логин','Логин шлюза'],['password','Пароль','Пароль шлюза']],note:'Подключение выполняется через отдельный адаптер/шлюз.'},
 frontol:{title:'Frontol',fields:[['base_url','URL шлюза','https://...'],['token','Токен шлюза','Токен']],note:'Для локального Frontol потребуется шлюз QR Menu.'}
};
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
function session(){return window.__QR_INTEGRATIONS_SESSION__||null}
async function getSession(){var s=session();if(s)return s;if(window.supabase){var key=(window.QR_CONFIG&&window.QR_CONFIG.SUPABASE_ANON_KEY)||'sb_publishable_9hmWZwV5WnfQHDK1ir36Pg_JIdHdwPq',db=window.supabase.createClient('https://ulxfsozdryqrnlxzlblt.supabase.co',key,{auth:{storage:window.sessionStorage,storageKey:'qr-menu-auth-account',persistSession:true,autoRefreshToken:true}}),r=await db.auth.getSession();return r.data&&r.data.session}return null}
function openCard(card){var id=card.getAttribute('data-provider'),c=cfg[id];if(!c)return;document.querySelectorAll('.hub-panel').forEach(function(x){x.remove()});var panel=document.createElement('div');panel.className='hub-panel notice';panel.innerHTML='<b>'+esc(c.title)+'</b><div class="muted" style="margin:6px 0 10px">'+esc(c.note)+'</div>'+c.fields.map(function(f){return '<div class="field"><label>'+esc(f[1])+'</label><input data-field="'+esc(f[0])+'" type="'+(f[0].includes('password')||f[0].includes('secret')||f[0]==='token'?'password':'text')+'" placeholder="'+esc(f[2])+'" autocomplete="off"></div>'}).join('')+'<div class="actions"><button class="btn btn-primary hub-save">Подключить</button><button class="btn btn-ghost hub-close">Отмена</button></div><div class="actions hub-tools hidden"><button class="btn btn-ghost" data-act="test">Проверить</button><button class="btn btn-ghost" data-act="nomenclature">Загрузить меню</button><button class="btn btn-ghost" data-act="preview_import">Предпросмотр</button><button class="btn btn-primary" data-act="import_menu">Импортировать в QR Menu</button></div><div class="result hub-result hidden"></div><div class="muted hub-state" style="margin-top:8px"></div>';card.appendChild(panel);panel.querySelector('.hub-close').onclick=function(){panel.remove()};panel.querySelector('.hub-save').onclick=function(){run(id,panel,'connect')};panel.querySelectorAll('.hub-tools [data-act]').forEach(function(b){b.onclick=function(){run(id,panel,b.getAttribute('data-act'))}});panel.scrollIntoView({behavior:'smooth',block:'nearest'})}
async function run(provider,panel,action){var venue=document.getElementById('venue');if(!venue||!venue.value){panel.querySelector('.hub-state').textContent='Сначала выберите заведение.';return}var values={};panel.querySelectorAll('[data-field]').forEach(function(i){values[i.getAttribute('data-field')]=i.value.trim()});if(action==='connect'&&Object.keys(values).some(function(k){return !values[k]})){panel.querySelector('.hub-state').textContent='Заполните все поля.';return}var b=panel.querySelector('.hub-save');if(b)b.disabled=true;panel.querySelector('.hub-state').textContent=action==='connect'?'Подключение...':'Выполняется...';try{var s=await getSession();if(!s)throw new Error('Сессия истекла. Войдите в кабинет заново.');var r=await fetch('/api/integrations/pos',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+s.access_token},body:JSON.stringify({action:action,provider:provider,venue_id:venue.value,credentials:values})}),d=await r.json().catch(function(){return{}});if(!r.ok)throw new Error(d.error||'Ошибка интеграции');panel.querySelector('.hub-state').textContent=action==='connect'?'Подключено. Найдено позиций: '+Number(d.products_count||0):'Готово: '+JSON.stringify(d,null,2);var result=panel.querySelector('.hub-result');if(result){result.textContent=JSON.stringify(d,null,2);result.classList.remove('hidden')}if(action==='connect'){var tools=panel.querySelector('.hub-tools');if(tools)tools.classList.remove('hidden');var st=cardStatus(provider);if(st){st.textContent='Подключено';st.classList.add('ready')}}}catch(e){panel.querySelector('.hub-state').textContent=e.message||String(e)}finally{if(b)b.disabled=false}}
function cardStatus(provider){var card=document.querySelector('.hub-card[data-provider="'+provider+'"]');return card&&card.querySelector('.status')}
document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.hub-card .hub-open').forEach(function(b){b.onclick=function(){openCard(b.closest('.hub-card'))}})});
})();
