(function(){
'use strict';

/* Unified integrations hub. iiko keeps its dedicated UI in integrations.html. */
var cfg={
 r_keeper:{title:'r_keeper',fields:[['base_url','URL API','https://...'],['client_id','Client ID','Client ID'],['client_secret','Client Secret','Client Secret'],['object_id','ID объекта ресторана','например 199994335']],note:'Импорт меню, модификаторов и синхронизация.'},
 quick_resto:{title:'Quick Resto',fields:[['base_url','URL API','https://...'],['login','API логин','Логин API'],['password','API пароль','Пароль API']],note:'Синхронизация меню, категорий и цен через API.'},
 saby_presto:{title:'Saby Presto',fields:[['app_client_id','App Client ID','ID приложения Saby'],['app_secret','App Secret','Секрет приложения Saby'],['secret_key','Secret Key','Сервисный ключ Saby']],optional:[['point_id','ID точки продаж','Можно выбрать после подключения'],['price_list_id','ID прайс-листа','Можно выбрать после подключения']],note:'Официальный Saby Retail API: сервисная авторизация, точки, прайс-листы, номенклатура и заказы.'},
 yuma:{title:'YUMA',fields:[['base_url','URL API','https://...'],['token','API token','Токен']],note:'Параметры API YUMA.'},
 poster:{title:'Poster',fields:[['account','Поддомен аккаунта','myrestaurant'],['token','API token','API token Poster']],note:'Параметры Poster API.'},
 syrve:{title:'Syrve',fields:[['base_url','URL API','https://...'],['api_login','API логин','Логин API'],['api_key','API key','Ключ API'],['organization_id','Organization ID','UUID организации']],note:'Параметры Syrve API.'},
 tillypad:{title:'Tillypad',fields:[['base_url','URL шлюза','https://...'],['login','Логин','Логин шлюза'],['password','Пароль','Пароль шлюза']],note:'Подключение через защищённый шлюз.'},
 evotor:{title:'Эвотор',fields:[['client_id','Client ID','ID приложения'],['client_secret','Client Secret','Секрет приложения'],['token','Access token','Если выдан']],note:'OAuth/API параметры Эвотор.'},
 frontol:{title:'Frontol',fields:[['base_url','URL шлюза','https://...'],['token','Токен шлюза','Токен']],note:'Локальный Frontol подключается через защищённый шлюз.'},
 frontpad:{title:'FrontPad',fields:[['base_url','URL API','https://...'],['token','API token','Токен']],note:'Параметры FrontPad API.'},
 fast_operator:{title:'Fast Operator',fields:[['base_url','URL API','https://...'],['token','API token','Токен']],note:'Параметры API Fast Operator.'},
 jowi:{title:'Jowi',fields:[['base_url','URL API','https://...'],['token','API token','Токен']],note:'Параметры API Jowi.'},
 smarttouch:{title:'SmartTouch',fields:[['base_url','URL API','https://...'],['token','API token','Токен']],note:'Параметры API SmartTouch.'},
 traktir:{title:'Трактиръ',fields:[['base_url','URL API/шлюза','https://...'],['login','Логин','Логин'],['password','Пароль','Пароль']],note:'Подключение через API или шлюз обмена.'},
 restik:{title:'Restik',fields:[['base_url','URL API','https://...'],['token','API token','Токен']],note:'Параметры API Restik.'},
 paladin:{title:'Paladin',fields:[['base_url','URL API/шлюза','https://...'],['token','Токен','Токен']],note:'Подключение через API или шлюз.'},
 parus_restaurant:{title:'Парус-Ресторан',fields:[['base_url','URL обмена','https://...'],['login','Логин','Логин'],['password','Пароль','Пароль']],note:'HTTP-обмен с установленным шлюзом.'},
 kontur_market:{title:'Контур.Маркет: Общепит',fields:[['base_url','URL API','https://...'],['token','API token','Токен']],note:'Параметры API Контур.Маркет.'},
 onec:{title:'1С: Ресторан / Общепит / 1С-Рарус',fields:[['base_url','URL HTTP-сервиса','https://.../hs/...'],['login','Логин','Логин HTTP-сервиса'],['password','Пароль HTTP-сервиса','Пароль']],note:'URL и учётные данные HTTP-сервиса предоставляет администратор 1С.'}
};
var implemented={r_keeper:true,quick_resto:true,saby_presto:true};
var realActions={r_keeper:['test','nomenclature','preview_import','import_menu'],quick_resto:['test','nomenclature','preview_import','import_menu'],saby_presto:['test','points','price_lists','nomenclature','preview_import','import_menu','order_create','order_status','order_cancel']};
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
function session(){return window.__QR_INTEGRATIONS_SESSION__||null}
async function getSession(){var s=session();if(s)return s;if(window.supabase){var key=(window.QR_CONFIG&&window.QR_CONFIG.SUPABASE_ANON_KEY)||'';var db=window.supabase.createClient('https://ulxfsozdryqrnlxzlblt.supabase.co',key,{auth:{storage:window.sessionStorage,storageKey:'qr-menu-auth-account',persistSession:true,autoRefreshToken:true}});var r=await db.auth.getSession();return r.data&&r.data.session}return null}
function fmtDate(v){if(!v)return '—';try{return new Intl.DateTimeFormat('ru-RU',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch(e){return String(v)}}
function card(provider){return document.querySelector('.hub-card[data-provider="'+provider+'"]')}
function setState(provider,row){var c=card(provider);if(!c)return;var st=c.querySelector('.status'),meta=c.querySelector('.hub-meta');if(!st)return;var connected=row&&(row.status==='connected'||row.status==='configured'||row.status==='disconnected');st.textContent=connected?(row.status==='connected'?'Подключено':'Настроено'):(row&&row.status==='error'?'Ошибка':'Не подключено');st.className='status '+(connected?'ready':'');if(meta)meta.innerHTML='<span>Последняя синхронизация: <b>'+esc(fmtDate(row&&row.last_sync_at))+'</b></span>'+(row&&row.metadata&&row.metadata.products_count!=null?'<span>Позиции: <b>'+Number(row.metadata.products_count)+'</b></span>':'')+(row&&row.error_message?'<span class="hub-error">Ошибка: '+esc(row.error_message)+'</span>':'')}
async function loadStatus(){var venue=document.getElementById('venue');if(!venue||!venue.value||!window.supabase)return;try{var s=await getSession();if(!s)return;var key=(window.QR_CONFIG&&window.QR_CONFIG.SUPABASE_ANON_KEY)||'';var db=window.supabase.createClient('https://ulxfsozdryqrnlxzlblt.supabase.co',key,{auth:{storage:window.sessionStorage,storageKey:'qr-menu-auth-account',persistSession:true,autoRefreshToken:true}});var r=await db.from('venue_integrations').select('provider,status,last_sync_at,error_message,metadata').eq('venue_id',venue.value);if(r.error)throw r.error;var rows=r.data||[];Object.keys(cfg).forEach(function(p){setState(p,rows.find(function(x){return x.provider===p}))});renderOverview(rows)}catch(e){console.warn('[Integrations] status',e)}}
function renderOverview(rows){var box=document.getElementById('integrationOverview');if(!box)return;var connected=rows.filter(function(r){return r.status==='connected'||r.status==='configured'||r.status==='disconnected'}).length,errors=rows.filter(function(r){return r.status==='error'}).length,last=rows.map(function(r){return r.last_sync_at}).filter(Boolean).sort().pop();box.innerHTML='<div class="hub-overview-title"><b>Состояние интеграций</b><span>Выбранное заведение</span></div><div class="hub-overview-grid"><div><b>'+connected+'</b><span>настроено</span></div><div><b>20</b><span>систем в каталоге</span></div><div><b>'+errors+'</b><span>ошибок</span></div><div><b>'+esc(fmtDate(last))+'</b><span>последняя синхронизация</span></div></div>'}
function fieldHtml(f){var secret=/password|secret|token|key/i.test(f[0]);return '<div class="field"><label>'+esc(f[1])+'</label><input data-field="'+esc(f[0])+'" type="'+(secret?'password':'text')+'" placeholder="'+esc(f[2])+'" autocomplete="off"></div>'}
function openCard(c){var id=c.getAttribute('data-provider'),x=cfg[id];if(!x)return;document.querySelectorAll('.hub-panel').forEach(function(p){p.remove()});var panel=document.createElement('div');panel.className='hub-panel notice';panel.innerHTML='<b>'+esc(x.title)+'</b><div class="muted" style="margin:6px 0 10px">'+esc(x.note)+'</div>'+x.fields.map(fieldHtml).join('')+(x.optional?'<div class="muted" style="margin-top:8px">Дополнительно:</div>'+x.optional.map(fieldHtml).join(''):'')+'<div class="actions"><button class="btn btn-primary hub-save">Подключить</button><button class="btn btn-ghost hub-close">Отмена</button></div><div class="actions hub-tools hidden"></div><div class="result hub-result hidden"></div><div class="muted hub-state" style="margin-top:8px"></div>';c.appendChild(panel);panel.querySelector('.hub-close').onclick=function(){panel.remove()};panel.querySelector('.hub-save').onclick=function(){run(id,panel,'connect')};var tools=panel.querySelector('.hub-tools');(realActions[id]||[]).forEach(function(a){var b=document.createElement('button');b.className='btn '+(a==='import_menu'?'btn-primary':'btn-ghost');b.textContent=({test:'Проверить',points:'Точки продаж',price_lists:'Прайс-листы',nomenclature:'Загрузить меню',preview_import:'Предпросмотр импорта',import_menu:'Импортировать в QR Menu',order_create:'Тест заказа',order_status:'Статус заказа',order_cancel:'Отменить заказ'}[a]||a);b.setAttribute('data-act',a);b.onclick=function(){run(id,panel,a)};tools.appendChild(b)});panel.scrollIntoView({behavior:'smooth',block:'nearest'})}
function result(panel,d){var r=panel.querySelector('.hub-result');if(!r)return;var t=d&&d.status?'Статус: '+d.status+'\n':'';if(d&&d.received!=null)t+='Получено: '+d.received+'\nСоздано: '+(d.created||0)+'\nОбновлено: '+(d.updated||0)+'\nБез изменений: '+(d.unchanged||0)+'\nОшибок: '+(d.error_count||0)+'\n';if(d&&d.points)t+='Точек: '+d.points.length+'\n';if(d&&d.price_lists)t+='Прайс-листов: '+d.price_lists.length+'\n';if(d&&d.implemented===false)t+='\nПодключение сохранено и зашифровано. Реальный обмен для этого провайдера будет включён после добавления его официального API/шлюза.\n';if(d&&d.errors&&d.errors.length)t+='\n'+d.errors.slice(0,10).map(function(e){return '• '+(e.name||'item')+': '+(e.error||e)}).join('\n');r.textContent=t||JSON.stringify(d,null,2);r.classList.remove('hidden')}
async function run(provider,panel,action){var venue=document.getElementById('venue');if(!venue||!venue.value){panel.querySelector('.hub-state').textContent='Сначала выберите заведение.';return}var values={};panel.querySelectorAll('[data-field]').forEach(function(i){if(i.value.trim())values[i.getAttribute('data-field')]=i.value.trim()});if(action==='connect'&&Object.keys(values).filter(function(k){return !/^point_id$|^price_list_id$/.test(k)}).length===0){panel.querySelector('.hub-state').textContent='Заполните параметры подключения.';return}try{var s=await getSession();if(!s)throw new Error('Сессия истекла. Войдите в кабинет заново.');var endpoint=provider==='saby_presto'?'/api/integrations/saby-presto':(implemented[provider]?'/api/integrations/pos':'/api/integrations/manage');var body=provider==='saby_presto'?{action:action,venue_id:venue.value,credentials:values}:{action:implemented[provider]?action:'save',provider:provider,venue_id:venue.value,credentials:values};if(action==='connect'&&provider!=='saby_presto'&&implemented[provider]===false)body.action='save';panel.querySelector('.hub-state').textContent=action==='connect'?'Подключение...':'Выполняется...';var save=panel.querySelector('.hub-save');if(save)save.disabled=true;var r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+s.access_token},body:JSON.stringify(body)}),d=await r.json().catch(function(){return{}});if(!r.ok)throw new Error(d.error||'Ошибка интеграции');result(panel,d);if(action==='connect'){var tools=panel.querySelector('.hub-tools');if(tools&&realActions[provider]&&realActions[provider].length)tools.classList.remove('hidden');panel.querySelector('.hub-state').textContent=provider==='saby_presto'?'Saby подключён. Выберите точку и прайс-лист при необходимости.':implemented[provider]?'Подключение проверено.':'Параметры подключения сохранены и зашифрованы.';await loadStatus()}else if(action==='import_menu'){panel.querySelector('.hub-state').textContent=d.error_count?'Импорт завершён частично.':'Импорт завершён без ошибок.';await loadStatus()}else if(action==='preview_import')panel.querySelector('.hub-state').textContent='Предпросмотр сформирован. Ничего не изменено.';else panel.querySelector('.hub-state').textContent='Операция выполнена.'}catch(e){panel.querySelector('.hub-state').textContent=e.message||String(e);await loadStatus()}finally{var save2=panel.querySelector('.hub-save');if(save2)save2.disabled=false}}
function addMissingCards(){var grid=document.getElementById('integrationsGrid');if(!grid)return;Object.keys(cfg).forEach(function(id){if(document.querySelector('.hub-card[data-provider="'+id+'"]'))return;var c=document.createElement('section');c.className='cardx hub-card';c.setAttribute('data-provider',id);var x=cfg[id];c.innerHTML='<div style="font-size:20px;font-weight:700">'+esc(x.title)+'</div><div class="muted">'+esc(x.note)+'</div><div class="hub-meta"><span>Последняя синхронизация: <b>—</b></span></div><div class="status">Не подключено</div><div class="actions"><button class="btn btn-primary hub-open">Подключить</button></div>';grid.appendChild(c)})}
function inject(){var g=document.getElementById('integrationsGrid');if(!g)return;if(!document.getElementById('integrationOverview')){var style=document.createElement('style');style.textContent='.hub-meta{display:flex;flex-direction:column;gap:3px;margin:6px 0 10px;color:#94a3b8;font-size:11px}.hub-meta b{color:#cbd5e1}.hub-error{color:#fca5a5}.hub-overview{grid-column:1/-1}.hub-overview-title{display:flex;justify-content:space-between;margin-bottom:9px}.hub-overview-title span{color:#94a3b8;font-size:11px}.hub-overview-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.hub-overview-grid>div{padding:12px;border-radius:12px;background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.08)}.hub-overview-grid b{display:block;font-size:18px}.hub-overview-grid span{font-size:10px;color:#94a3b8}.hub-panel{grid-column:1/-1}@media(max-width:600px){.hub-overview-grid{grid-template-columns:repeat(2,1fr)}}';document.head.appendChild(style);var o=document.createElement('section');o.id='integrationOverview';o.className='cardx hub-overview';o.innerHTML='<div class="hub-overview-title"><b>Состояние интеграций</b><span>Загрузка...</span></div>';g.insertBefore(o,g.firstChild)}addMissingCards();document.querySelectorAll('.hub-card').forEach(function(c){var b=c.querySelector('.hub-open');if(b&&!b.__hubBound){b.__hubBound=true;b.addEventListener('click',function(){openCard(c)})}});var v=document.getElementById('venue');if(v&&!v.__hubChange){v.__hubChange=true;v.addEventListener('change',loadStatus)}loadStatus()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject,{once:true});else inject();setTimeout(inject,500);setTimeout(inject,1500);
})();
