'use strict';
(function(){
  const SUPABASE_URL='https://ulxfsozdryqrnlxzlblt.supabase.co';
  const PROVIDERS={
    iiko:'iiko',r_keeper:'r_keeper',quick_resto:'Quick Resto',saby_presto:'Saby Presto',yuma:'YUMA',poster:'Poster',syrve:'Syrve',tillypad:'Tillypad',evotor:'Эвотор',frontol:'Frontol',frontpad:'FrontPad',fast_operator:'Fast Operator',jowi:'Jowi',smarttouch:'SmartTouch',traktir:'Трактиръ',restik:'Restik',paladin:'Paladin',parus_restaurant:'Парус-Ресторан',kontur_market:'Контур.Маркет: Общепит',onec:'1С: Ресторан / Общепит / 1С-Рарус'
  };
  const ADAPTERS={
    iiko:'/api/integrations/iiko',r_keeper:'/api/integrations/pos',quick_resto:'/api/integrations/pos',saby_presto:'/api/integrations/saby-presto',poster:'/api/integrations/poster',syrve:'/api/integrations/syrve',evotor:'/api/integrations/evotor',frontpad:'/api/integrations/frontpad'
  };
  const FIELDS={
    iiko:[['api_login','API Login'],['api_password','API Password']],r_keeper:[['base_url','URL сервера'],['login','Логин'],['password','Пароль']],quick_resto:[['login','Логин'],['password','Пароль']],saby_presto:[['app_client_id','Client ID'],['app_secret','Client Secret'],['secret_key','Secret Key']],poster:[['account','Аккаунт / поддомен'],['token','API Token']],syrve:[['api_login','API Login'],['organization_id','Organization ID']],evotor:[['access_token','Access Token'],['store_id','Store ID']],frontpad:[['secret','API Secret']],yuma:[['api_key','API Key']],tillypad:[['base_url','URL сервера'],['api_key','API Key']],frontol:[['base_url','URL сервера'],['api_key','API Key']],fast_operator:[['base_url','URL сервера'],['api_key','API Key']],jowi:[['base_url','URL сервера'],['api_key','API Key']],smarttouch:[['base_url','URL сервера'],['api_key','API Key']],traktir:[['base_url','URL сервера'],['api_key','API Key']],restik:[['base_url','URL сервера'],['api_key','API Key']],paladin:[['base_url','URL сервера'],['api_key','API Key']],parus_restaurant:[['base_url','URL сервера'],['api_key','API Key']],kontur_market:[['base_url','URL сервера'],['api_key','API Key']],onec:[['base_url','URL обмена'],['username','Логин'],['password','Пароль']]
  };
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
  async function session(){try{if(window.db&&window.db.auth){const r=await window.db.auth.getSession();return r&&r.data&&r.data.session||null;}}catch(e){}return null;}
  async function request(url,body){const s=await session();if(!s)throw Error('Сессия управляющего не найдена. Войдите заново.');const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+s.access_token},body:JSON.stringify(body)});let d={};try{d=await r.json();}catch(e){}if(!r.ok||d.ok===false)throw Error(d.error||d.message||('HTTP '+r.status));return d;}
  function currentVenue(){const keys=['qr_selected_venue','selected_venue_id','manager_selected_venue','current_venue_id'];for(const k of keys){const v=localStorage.getItem(k)||sessionStorage.getItem(k);if(v)return v;}const q=new URLSearchParams(location.search).get('venue_id');return q||'';}
  function root(){return document.querySelector('[data-integrations-hub]')||document.querySelector('.integrations-grid')||document.querySelector('main');}
  function ensureRoot(){let r=root();if(!r){r=document.createElement('main');r.className='integrations-grid';document.body.appendChild(r);}r.setAttribute('data-integrations-hub','1');return r;}
  function card(id){return document.querySelector('.hub-card[data-provider="'+CSS.escape(id)+'"]');}
  function render(){const r=ensureRoot();const existing=new Set([...r.querySelectorAll('.hub-card[data-provider]')].map(x=>x.dataset.provider));Object.entries(PROVIDERS).forEach(([id,name])=>{if(existing.has(id))return;const c=document.createElement('section');c.className='hub-card';c.dataset.provider=id;c.style.cssText='padding:18px;border:1px solid rgba(127,127,127,.2);border-radius:16px;margin:10px 0;';c.innerHTML='<h3 style="margin:0 0 8px">'+esc(name)+'</h3><div class="hub-status" style="font-size:13px;opacity:.7;margin-bottom:12px">Не подключено</div><div class="hub-fields"></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button type="button" class="hub-connect">Подключить</button><button type="button" class="hub-test" hidden>Проверить</button><button type="button" class="hub-import" hidden>Импорт меню</button></div><div class="hub-result" style="margin-top:10px;font-size:13px"></div>';r.appendChild(c);});bind();}
  function bind(){document.querySelectorAll('.hub-card').forEach(c=>{if(c.dataset.bound)return;c.dataset.bound='1';const id=c.dataset.provider,fields=c.querySelector('.hub-fields');(FIELDS[id]||[]).forEach(([key,label])=>{const wrap=document.createElement('label');wrap.style.cssText='display:block;margin:7px 0';wrap.innerHTML='<span style="display:block;font-size:12px;margin-bottom:4px">'+esc(label)+'</span><input data-key="'+esc(key)+'" type="'+(key.toLowerCase().includes('password')||key.includes('secret')||key.includes('token')?'password':'text')+'" autocomplete="off" style="width:100%;box-sizing:border-box;padding:9px;border-radius:9px;border:1px solid rgba(127,127,127,.25)">';fields.appendChild(wrap);});c.querySelector('.hub-connect').onclick=()=>act(c,'connect');c.querySelector('.hub-test').onclick=()=>act(c,'test');c.querySelector('.hub-import').onclick=()=>act(c,'import_menu');});}
  function creds(c){const o={};c.querySelectorAll('[data-key]').forEach(i=>{const v=i.value.trim();if(v)o[i.dataset.key]=v;});return o;}
  async function act(c,action){const id=c.dataset.provider,venue_id=currentVenue(),result=c.querySelector('.hub-result'),status=c.querySelector('.hub-status'),connect=c.querySelector('.hub-connect'),test=c.querySelector('.hub-test'),imp=c.querySelector('.hub-import');result.textContent='';if(!venue_id){result.textContent='Выберите заведение управляющего.';return;}connect.disabled=true;test.disabled=true;imp.disabled=true;try{if(!ADAPTERS[id]){await request('/api/integrations/manage',{action:'connect',provider:id,venue_id,credentials:creds(c)});status.textContent='Конфигурация сохранена; API-адаптер ещё не реализован.';result.textContent='Сохранено. Подключение к API станет доступно после реализации адаптера.';return;}const d=await request(ADAPTERS[id],{action,provider:id,venue_id,credentials:creds(c)});status.textContent='Подключено';result.textContent=action==='import_menu'?`Импорт завершён: создано ${d.created||0}, обновлено ${d.updated||0}, без изменений ${d.unchanged||0}.`:'Соединение успешно проверено.';test.hidden=false;imp.hidden=false;}catch(e){status.textContent='Ошибка подключения';result.textContent=e.message||String(e);}finally{connect.disabled=false;test.disabled=false;imp.disabled=false;}}
  function boot(){render();if(window.MutationObserver){new MutationObserver(()=>{render();}).observe(document.body,{childList:true,subtree:true});}window.addEventListener('storage',render);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
