(function(){
'use strict';
if(!/\/manager\.html$/i.test(location.pathname)) return;
var root=document.getElementById('app'),panel=null;
function getVM(){if(!root)return null;if(root.__vueParentComponent&&root.__vueParentComponent.proxy)return root.__vueParentComponent.proxy;if(root.__vue_app__&&root.__vue_app__._instance&&root.__vue_app__._instance.proxy)return root.__vue_app__._instance.proxy;return null}
function css(){if(document.getElementById('manager-tables-style'))return;var s=document.createElement('style');s.id='manager-tables-style';s.textContent='.mt-modal{position:fixed;inset:0;background:rgba(5,10,20,.78);backdrop-filter:blur(8px);z-index:5000;display:flex;align-items:center;justify-content:center;padding:16px}.mt-box{width:min(980px,100%);max-height:90vh;overflow:auto;background:#111827;border:1px solid rgba(255,255,255,.12);border-radius:20px;padding:20px;color:#fff;box-shadow:0 25px 80px rgba(0,0,0,.45)}.mt-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:16px}.mt-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:12px}.mt-card{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:14px;text-align:center}.mt-card.off{opacity:.58}.mt-qr{background:#fff;border-radius:12px;padding:8px;width:150px;height:150px;margin:10px auto;display:flex;align-items:center;justify-content:center}.mt-qr img{max-width:100%;max-height:100%}.mt-muted{color:#94a3b8;font-size:12px}.mt-row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.mt-input{background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.12);color:#fff;border-radius:10px;padding:10px}.mt-btn{border:0;border-radius:10px;padding:9px 12px;cursor:pointer;font-weight:700}.mt-primary{background:#6366f1;color:#fff}.mt-danger{background:#7f1d1d;color:#fff}.mt-green{background:#047857;color:#fff}.mt-ghost{background:rgba(255,255,255,.08);color:#fff}.mt-modal input::placeholder{color:#94a3b8}@media(max-width:600px){.mt-box{padding:14px}.mt-grid{grid-template-columns:1fr}.mt-head{align-items:flex-start}.mt-row{flex-direction:column;align-items:stretch}.mt-row .mt-btn,.mt-row .mt-input{width:100%;box-sizing:border-box}}';document.head.appendChild(s)}
function addButton(){var tabs=document.querySelector('.tabs');if(!tabs||tabs.querySelector('[data-manager-tables]'))return;var b=document.createElement('button');b.type='button';b.textContent='🪑 Столы';b.setAttribute('data-manager-tables','1');b.onclick=openPanel;tabs.appendChild(b)}
async function getVenue(){var vm=getVM();if(vm&&vm.venue&&vm.venue.id)return vm.venue;try{var q=await db.from('manager_venues').select('venue_id, venues(*)');if(q.error||!q.data||!q.data.length)return null;var list=q.data.map(function(x){return x.venues}).filter(Boolean);if(list.length===1)return list[0];var brand=document.querySelector('.brand span'),name=brand?String(brand.textContent||'').trim():'';return list.find(function(v){return v.name===name})||null}catch(e){return null}}
function tableUrl(t,v){return location.origin+location.pathname.replace(/manager\.html$/i,'menu.html')+'?venue='+encodeURIComponent(v.slug)+'&table='+encodeURIComponent(t.qr_token)}
function qr(el,text){el.innerHTML='';if(window.QRCode){new QRCode(el,{text:text,width:140,height:140,colorDark:'#111827',colorLight:'#fff',correctLevel:QRCode.CorrectLevel.M});return}var img=document.createElement('img');img.src='https://api.qrserver.com/v1/create-qr-code/?size=160x160&data='+encodeURIComponent(text);img.alt='QR';el.appendChild(img)}
function escapeHtml(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
async function openPanel(){css();var v=await getVenue();if(!v){var vm=getVM();if(vm&&vm.myVenues&&vm.myVenues.length===1&&typeof vm.selectVenue==='function'){vm.selectVenue(vm.myVenues[0]);await new Promise(function(r){setTimeout(r,250)});v=await getVenue()}}if(!v){alert('Не удалось определить выбранное заведение. Откройте список заведений и выберите нужное.');return}if(panel)panel.remove();panel=document.createElement('div');panel.className='mt-modal';panel.innerHTML='<div class="mt-box"><div class="mt-head"><div><h2 style="margin:0">🪑 Столы и QR-коды</h2><div class="mt-muted" style="margin-top:5px">'+escapeHtml(v.name)+'</div></div><button class="mt-btn mt-ghost" id="mt-close">✕ Закрыть</button></div><div class="mt-row" style="margin-bottom:16px"><input id="mt-count" class="mt-input" type="number" min="1" max="100" value="5" placeholder="Количество"><button id="mt-create" class="mt-btn mt-primary">+ Создать столы</button><button id="mt-print" class="mt-btn mt-ghost">🖨 Печать всех</button></div><div id="mt-msg" class="mt-muted" style="margin-bottom:12px"></div><div id="mt-grid" class="mt-grid"></div></div>';document.body.appendChild(panel);panel.querySelector('#mt-close').onclick=closePanel;panel.addEventListener('click',function(e){if(e.target===panel)closePanel()});panel.querySelector('#mt-create').onclick=function(){createTables(v)};panel.querySelector('#mt-print').onclick=function(){printAll()};await loadTables(v)}
function closePanel(){if(panel)panel.remove();panel=null}
async function loadTables(v){var g=panel.querySelector('#mt-grid'),m=panel.querySelector('#mt-msg');g.innerHTML='<div class="mt-muted">Загрузка...</div>';var r=await db.from('venue_tables').select('*').eq('venue_id',v.id).order('table_number');if(r.error){m.textContent='Ошибка: '+r.error.message;return}m.textContent=r.data.length?'Всего столов: '+r.data.length:'Столов пока нет';g.innerHTML='';(r.data||[]).forEach(function(t){var c=document.createElement('div');c.className='mt-card'+(t.is_active?'':' off');c.innerHTML='<b style="font-size:18px">'+escapeHtml(t.name||('Стол '+t.table_number))+'</b><div class="mt-muted">№'+t.table_number+' · '+(t.is_active?'🟢 Активен':'🔴 Отключён')+'</div><div class="mt-qr"></div><div class="mt-row" style="justify-content:center"><button class="mt-btn mt-primary">✏️ Изменить</button><button class="mt-btn mt-green">'+(t.is_active?'🔴 Отключить':'🟢 Включить')+'</button><button class="mt-btn mt-ghost">🖨 QR</button><button class="mt-btn mt-danger">🗑</button></div>';g.appendChild(c);if(t.is_active)qr(c.querySelector('.mt-qr'),tableUrl(t,v));else c.querySelector('.mt-qr').innerHTML='<div style="color:#111827;font-weight:700">ОТКЛЮЧЁН</div>';var bs=c.querySelectorAll('button');bs[0].onclick=function(){editTable(t,v)};bs[1].onclick=function(){toggleTable(t,v)};bs[2].onclick=function(){printOne(c,t,v)};bs[3].onclick=function(){removeTable(t,v)})})}
async function createTables(v){var n=Math.max(1,Math.min(100,Number(panel.querySelector('#mt-count').value)||1)),m=panel.querySelector('#mt-msg');var r0=await db.from('venue_tables').select('table_number').eq('venue_id',v.id).order('table_number');if(r0.error){m.textContent='Ошибка: '+r0.error.message;return}var used=new Set((r0.data||[]).map(function(x){return Number(x.table_number)})),next=1,rows=[];for(var i=0;i<n;i++){while(used.has(next))next++;rows.push({venue_id:v.id,table_number:next,name:'Стол '+next,is_active:true});used.add(next);next++}var r=await db.from('venue_tables').insert(rows);if(r.error){m.textContent='Ошибка: '+r.error.message;return}m.textContent='Создано столов: '+n;await loadTables(v)}
async function editTable(t,v){var name=prompt('Название стола:',t.name||('Стол '+t.table_number));if(name===null)return;name=String(name).trim();if(!name){alert('Название не может быть пустым');return}var r=await db.from('venue_tables').update({name:name}).eq('id',t.id);if(r.error){alert('Ошибка: '+r.error.message);return}await loadTables(v)}
async function toggleTable(t,v){var r=await db.from('venue_tables').update({is_active:!t.is_active}).eq('id',t.id);if(r.error){alert('Ошибка: '+r.error.message);return}await loadTables(v)}
async function removeTable(t,v){if(!confirm('Удалить '+(t.name||('Стол '+t.table_number))+'?'))return;var r=await db.from('venue_tables').delete().eq('id',t.id);if(r.error){alert('Ошибка: '+r.error.message);return}await loadTables(v)}
function printOne(card,t,v){var clone=card.cloneNode(true);clone.querySelectorAll('button').forEach(function(b){b.remove()});var url=tableUrl(t,v);var w=window.open('','_blank','width=500,height=650');if(!w){alert('Разрешите всплывающие окна для печати QR');return}w.document.write('<html><head><title>'+escapeHtml(t.name||('Стол '+t.table_number))+'</title><style>body{font-family:Arial;text-align:center;padding:30px}.mt-qr{margin:20px auto}.mt-qr img{max-width:100%}.mt-muted{color:#666;font-size:12px}.url{font-size:10px;color:#777;word-break:break-all}</style></head><body>'+clone.outerHTML+'<div class="url">'+escapeHtml(url)+'</div></body></html>');w.document.close();w.focus();setTimeout(function(){w.print();w.close()},400)}
function printAll(){if(!panel)return;var cards=panel.querySelectorAll('.mt-card');if(!cards.length)return;var w=window.open('','_blank','width=900,height=900');if(!w){alert('Разрешите всплывающие окна для печати QR');return}var html='';cards.forEach(function(c){var x=c.cloneNode(true);x.querySelectorAll('button').forEach(function(b){b.remove()});html+='<div style="display:inline-block;width:30%;vertical-align:top;text-align:center;margin:10px;padding:12px;border:1px solid #ddd;border-radius:12px">'+x.outerHTML+'</div>'});w.document.write('<html><head><title>QR столов</title><style>body{font-family:Arial}.mt-qr{margin:10px auto;background:#fff;padding:8px;width:150px;height:150px}.mt-qr img{max-width:100%;max-height:100%}.mt-muted{color:#666;font-size:12px}@media print{body{margin:10mm}}</style></head><body><h1>QR-коды столов</h1>'+html+'</body></html>');w.document.close();w.focus();setTimeout(function(){w.print();w.close()},500)}
var obs=new MutationObserver(function(){addButton()});function start(){css();addButton();obs.observe(document.body,{childList:true,subtree:true});setTimeout(addButton,1000);setTimeout(addButton,3000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();