(function(){
  const style=`#aiHall{margin-top:16px}.ai-hall-head{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}.ai-hall-actions{display:flex;gap:8px;flex-wrap:wrap}.ai-hall-canvas{position:relative;min-height:520px;border:1px solid rgba(255,255,255,.1);border-radius:18px;overflow:hidden;background:linear-gradient(135deg,#111827,#0f172a);margin-top:14px}.ai-hall-canvas img{width:100%;height:auto;display:block;max-height:70vh;object-fit:contain;background:#111}.ai-table{position:absolute;transform:translate(-50%,-50%);width:72px;height:72px;border-radius:50%;display:flex;align-items:center;justify-content:center;text-align:center;font-size:11px;font-weight:800;color:#fff;cursor:grab;box-shadow:0 8px 28px rgba(0,0,0,.35);border:2px solid rgba(255,255,255,.55);user-select:none}.ai-table.square{border-radius:12px}.ai-table.rect{width:96px;border-radius:12px}.ai-table.ai-new{outline:3px solid #a78bfa}.ai-table .confidence{font-size:9px;opacity:.75}.ai-drop{border:2px dashed rgba(129,140,248,.5);border-radius:18px;padding:42px;text-align:center;color:#a5b4fc;margin-top:14px;cursor:pointer}.ai-drop:hover{background:rgba(99,102,241,.06)}.ai-result{margin-top:12px;padding:12px;border-radius:12px;background:rgba(52,211,153,.08);border:1px solid rgba(52,211,153,.25)}.ai-venue-select{background:#111827;color:#fff;border:1px solid rgba(255,255,255,.15);padding:9px;border-radius:9px}`;
  const s=document.createElement('style');s.textContent=style;document.head.appendChild(s);
  let state={venueId:null,venues:[],image:null,plan:null,tables:[],loading:false,drag:null};
  function esc(x){return String(x??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
  async function getVenues(){
    if(!window.db)return[];
    const {data,error}=await db.from('manager_venues').select('venue_id,venues(id,name,slug)').order('created_at');
    if(error)return[]; return (data||[]).map(x=>x.venues).filter(Boolean);
  }
  async function loadTables(){ if(!state.venueId)return; const r=await db.from('venue_tables').select('id,table_number,name,seats,shape,pos_x,pos_y').eq('venue_id',state.venueId).eq('is_active',true).order('table_number'); if(!r.error) state.tables=r.data||[]; render(); }
  async function loadPlan(){ if(!state.venueId)return; const r=await db.rpc('manager_get_hall_plan',{p_venue_id:state.venueId}); if(!r.error && r.data) state.plan=Array.isArray(r.data)?r.data[0]:r.data; render(); }
  function render(){
    const host=document.querySelector('[data-manager-hall-root]'); if(!host)return;
    host.innerHTML=`<div id="aiHall" class="glass card"><div class="ai-hall-head"><div><h3 style="margin:0">🗺️ Умная схема зала</h3><div class="muted" style="font-size:12px;margin-top:4px">Загрузите фото/план — AI найдёт столы, после чего вы сможете поправить их вручную.</div></div><div class="ai-hall-actions"><select id="aiVenue" class="ai-venue-select">${state.venues.map(v=>`<option value="${v.id}" ${v.id===state.venueId?'selected':''}>${esc(v.name)}</option>`).join('')}</select><button class="btn btn-primary btn-sm" id="aiAdd">+ Стол</button><button class="btn btn-ghost btn-sm" id="aiUpload">🖼 Загрузить план</button><button class="btn btn-primary btn-sm" id="aiAnalyze" ${state.image&& !state.loading?'':'disabled'}>✨ Анализировать AI</button><button class="btn btn-green btn-sm" id="aiSave" ${state.tables.length?'':'disabled'}>Сохранить</button></div></div><input id="aiFile" type="file" accept="image/*" hidden>${state.plan?.image_data||state.image?`<div class="ai-hall-canvas" id="aiCanvas"><img id="aiPlanImg" src="${esc(state.image||state.plan?.image_data)}">${state.tables.map(t=>tableHtml(t)).join('')}</div>`:`<div class="ai-drop" id="aiDrop">🖼️<br><b>Загрузите фото или план помещения</b><br><span class="muted">JPG, PNG, WEBP — затем нажмите «Анализировать AI»</span></div>`}${state.loading?'<div class="ai-result">⏳ AI анализирует план…</div>':''}${state.plan?.image_data?'<div class="muted" style="font-size:11px;margin-top:8px">План сохранён. Столы можно перетаскивать мышью.</div>':''}`;
    bind();
  }
  function tableHtml(t){ const x=Number(t.pos_x||t.x||100),y=Number(t.pos_y||t.y||100); return `<div class="ai-table ${esc(t.shape||'round')} ${t.confidence?'ai-new':''}" data-id="${esc(t.id||'new-'+t.table_number)}" data-x="${x}" data-y="${y}" style="left:${x/10}%;top:${y/10}%">🪑 ${esc(t.name||('Стол '+t.table_number))}<br><span class="confidence">${t.seats||4} мест${t.confidence?' · '+Math.round(t.confidence*100)+'%':''}</span></div>`; }
  function bind(){
    const v=document.getElementById('aiVenue'); if(v)v.onchange=async()=>{state.venueId=v.value;state.image=null;state.plan=null;await loadTables();await loadPlan();};
    const f=document.getElementById('aiFile'); const up=()=>f?.click(); document.getElementById('aiUpload')?.addEventListener('click',up);document.getElementById('aiDrop')?.addEventListener('click',up);
    f?.addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;const rd=new FileReader();rd.onload=()=>{state.image=rd.result;state.plan=null;render()};rd.readAsDataURL(file)});
    document.getElementById('aiAnalyze')?.addEventListener('click',analyze); document.getElementById('aiSave')?.addEventListener('click',save);
    document.getElementById('aiAdd')?.addEventListener('click',()=>{const n=(state.tables.reduce((m,t)=>Math.max(m,Number(t.table_number)||0),0)+1);state.tables.push({table_number:n,name:'Стол '+n,seats:4,shape:'round',pos_x:100+n*70,pos_y:100});render()});
    document.querySelectorAll('.ai-table').forEach(el=>{el.onpointerdown=e=>{e.preventDefault();state.drag={el,startX:e.clientX,startY:e.clientY,ox:Number(el.dataset.x),oy:Number(el.dataset.y)};el.setPointerCapture(e.pointerId)};el.onpointermove=e=>{if(!state.drag||state.drag.el!==el)return;const dx=(e.clientX-state.drag.startX)*10,dy=(e.clientY-state.drag.startY)*10;el.dataset.x=state.drag.ox+dx;el.dataset.y=state.drag.oy+dy;el.style.left=(Number(el.dataset.x)/10)+'%';el.style.top=(Number(el.dataset.y)/10)+'%'};el.onpointerup=()=>{if(!state.drag)return;const id=el.dataset.id;const t=state.tables.find(x=>(x.id||'new-'+x.table_number)===id);if(t){t.pos_x=Math.round(Number(el.dataset.x));t.pos_y=Math.round(Number(el.dataset.y))}state.drag=null}});
  }
  async function analyze(){if(!state.image)return;state.loading=true;render();try{const r=await fetch('/api/analyze-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:state.image})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI error');state.tables=d.tables.map((t,i)=>({table_number:t.number||i+1,name:'Стол '+(t.number||i+1),seats:t.seats||4,shape:t.shape||'round',pos_x:Math.round((t.x/d.image_width)*1000),pos_y:Math.round((t.y/d.image_height)*1000),confidence:t.confidence}));alert(`AI нашёл ${state.tables.length} столов. Проверьте и нажмите «Сохранить».`)}catch(e){alert(e.message)}finally{state.loading=false;render()}}
  async function save(){if(!state.venueId)return;try{if(state.image){const r=await db.rpc('manager_save_hall_plan',{p_venue_id:state.venueId,p_image_data:state.image,p_image_name:'venue-plan',p_image_width:null,p_image_height:null});if(r.error)throw r.error;state.plan=Array.isArray(r.data)?r.data[0]:r.data;}for(const t of state.tables){const r=await db.rpc('manager_upsert_table',{p_venue_id:state.venueId,p_table_id:t.id||null,p_table_number:Number(t.table_number),p_name:t.name||('Стол '+t.table_number),p_seats:Number(t.seats)||4,p_shape:t.shape||'round',p_pos_x:Math.round(Number(t.pos_x)||80),p_pos_y:Math.round(Number(t.pos_y)||80)});if(r.error)throw r.error;}await loadTables();alert('Схема зала сохранена.');}catch(e){alert('Не удалось сохранить: '+(e.message||e))}}
  async function mount(){ if(document.getElementById('aiHallMountWatcher'))return; const w=document.createElement('div');w.id='aiHallMountWatcher';w.style.display='none';document.body.appendChild(w); const tryMount=async()=>{let host=document.querySelector('[data-manager-hall-root]');if(!host){const tabs=[...document.querySelectorAll('button')].find(b=>/Зал\s*\/\s*Столы/i.test(b.textContent));if(tabs){let target=document.querySelector('[data-manager-hall-root]');if(!target){target=document.createElement('div');target.setAttribute('data-manager-hall-root','');target.style.display='none';tabs.closest('.tabs')?.parentElement?.appendChild(target)}}host=target}if(!host)return;state.venues=await getVenues();if(!state.venueId&&state.venues[0])state.venueId=state.venues[0].id;host.style.display=document.body.innerText.includes('Зал / Столы')?'block':'block';await loadTables();await loadPlan();render()};setTimeout(tryMount,800);setInterval(()=>{const tab=[...document.querySelectorAll('button')].find(b=>/Зал\s*\/\s*Столы/i.test(b.textContent));if(tab && !document.querySelector('[data-manager-hall-root]'))tryMount()},2500)}
  if(location.pathname.endsWith('/manager.html')){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount()}
})();
