(function(){
const type=window.STAFF_TYPE||'cook';
const labels={cook:['👨‍🍳','Кухня','повара'],courier:['🚗','Курьер','курьера'],waiter:['🤵','Официант','официанта']};
const L=labels[type]; let session=JSON.parse(localStorage.getItem('qr_staff_'+type)||'null'); let orders=[],history=[];
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function money(v){return Number(v||0).toLocaleString('ru-RU')+' ₽'}
function status(s){return ({new:'Новый',changed:'Изменён',cooking:'Готовится',ready:'Готов',delivery:'В доставке',done:'Завершён'}[s]||s)}
function card(o){let action=''; if(type==='cook'&&['new','changed'].includes(o.status)) action=`<button data-a="${o.id}" data-s="cooking">Взять в работу</button>`; else if(type==='cook'&&o.status==='cooking') action=`<button data-a="${o.id}" data-s="ready">Готово ✓</button>`; else if(type==='courier'&&o.status==='ready') action=`<button data-a="${o.id}" data-s="delivery">Взять на доставку</button>`; else if(type==='courier'&&o.status==='delivery') action=`<button data-a="${o.id}" data-s="done">Доставлено ✓</button>`; else if(type==='waiter'&&o.status==='ready'&&o.order_type==='pickup') action=`<button data-a="${o.id}" data-s="done">Выдать клиенту</button>`; else if(type==='waiter'&&o.status==='ready'&&o.order_type==='delivery') action=`<button data-a="${o.id}" data-s="delivery">Передать курьеру</button>`;
return `<article><div class="top"><b>№${esc(o.order_number)}</b><span>${status(o.status)}</span></div><div class="muted">${esc(o.customer_name||'Клиент')} · ${esc(o.customer_phone||'')}</div>${o.delivery_address?`<div class="muted">📍 ${esc(o.delivery_address)}</div>`:''}<div class="items">${(o.items||[]).map(i=>`${esc(i.qty)}× ${esc(i.name||'Товар')}`).join('<br>')}</div><div class="muted">${money(o.total_price)} · ${o.payment_method==='cash'?'наличные':'оплата картой'}</div>${action}</article>`}
async function load(){if(!session)return; try{orders=await StaffAPI.orders(session.token);history=await StaffAPI.history(session.token); render();}catch(e){logout(false); showLogin('Сессия истекла. Войдите снова.')}}
function render(){const active=orders.filter(o=>o.status!=='done'); $('#content').innerHTML=`<div class="stats"><div><b>${active.length}</b><small>Активных</small></div><div><b>${history.length}</b><small>В истории</small></div></div><h3>Активные заказы</h3><div class="grid">${active.length?active.map(card).join(''):'<p class="muted">Нет заказов</p>'}</div><h3>История</h3><div class="grid">${history.slice(0,20).map(card).join('')||'<p class="muted">История пуста</p>'}</div>`; document.querySelectorAll('[data-a]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await StaffAPI.update(session.token,b.dataset.a,b.dataset.s);await load()}catch(e){alert('Не удалось изменить заказ: '+(e.message||e))}finally{b.disabled=false}})}
function showLogin(msg){$('#app').innerHTML=`<div class="login"><h1>${L[0]} ${L[1]}</h1><p class="muted">Безопасный вход ${L[2]}</p><input id="slug" placeholder="Код заведения"><input id="pin" type="password" inputmode="numeric" placeholder="PIN"><button id="login">Войти</button><p id="err" class="err">${esc(msg||'')}</p></div>`;$('#login').onclick=async()=>{const b=$('#login');b.disabled=true;$('#err').textContent='';try{session=await StaffAPI.login(type,$('#slug').value.trim().toLowerCase(),$('#pin').value.trim());localStorage.setItem('qr_staff_'+type,JSON.stringify(session));renderShell();await load()}catch(e){$('#err').textContent=e.message==='invalid_credentials'?'Неверный PIN':e.message==='venue_not_found'?'Заведение не найдено':'Ошибка входа'}finally{b.disabled=false}}}
function renderShell(){$('#app').innerHTML=`<header><b>${L[0]} ${L[1]} · ${esc(session.venueName)}</b><button id="logout">Выйти</button></header><main id="content"></main>`;$('#logout').onclick=()=>logout(true)}
async function logout(remove){if(session)await StaffAPI.logout(session.token);session=null;localStorage.removeItem('qr_staff_'+type);if(remove)showLogin()}
window.addEventListener('load',()=>{if(session){renderShell();load();setInterval(load,5000)}else showLogin()});
})();
