'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');

const root = path.resolve(__dirname, '../..');
function readEntry(name) { return fs.readFileSync(path.join(root, 'api', name), 'utf8'); }
function readLib(relative) { return fs.readFileSync(path.join(root, 'lib', relative), 'utf8'); }

test('canonical recipe mutation module owns recipe actions',()=>{const source=readLib('ai/manager/mutations/recipes.js');assert.ok(fs.existsSync(path.join(root,'lib','ai/manager/mutations/recipes.js')));for(const type of ['recipe_auto_sync','attach_ingredients','create_tech_card','save_recipe'])assert.ok(source.includes(`'${type}'`),`${type} must live in recipe mutation module`);assert.ok(source.includes("await venue(c,vid,'menu')"));assert.ok(source.includes('p_venue_id:vid'));assert.ok(source.includes('manager_recipe_auto_sync'));assert.ok(source.includes('manager_product_recipe_save'));assert.ok(source.includes('resolveProduct'));assert.ok(source.includes('resolveIngredient'));});
test('manager AI action dispatches recipe mutations through canonical module',()=>{const source=readLib('ai/manager/action.js');assert.ok(source.includes("require('./mutations/recipes')"));assert.ok(source.includes('if(recipes.TYPES.has(type))return recipes.run(type,c,vid,p);'));for(const marker of ["if(type==='recipe_auto_sync')","if(['attach_ingredients','create_tech_card','save_recipe'].includes(type)"])assert.equal(source.includes(marker),false,`${marker} must not remain in central action dispatcher`);});
test('manager AI recipe mutations remain venue-isolated',()=>{const source=readLib('ai/manager/mutations/recipes.js');assert.ok(source.includes("await venue(c,vid,'menu')"));assert.ok(source.includes('Object.assign({},r,{venue_id:vid})'));assert.ok(source.includes('p_venue_id:vid'));assert.ok(source.includes('p_product_id:pid'));});
test('manager AI action endpoint remains a thin dispatcher',()=>{const source=readEntry('manager-ai-action.js');assert.equal(source.trim(),"'use strict';\n\nmodule.exports = require('../lib/ai/manager/action');");assert.ok(!source.includes('fetch('));assert.ok(!source.includes('createClient('));});
test('architecture modules retain canonical manager context boundaries',()=>{const context=readLib('ai/manager/context.js');for(const symbol of ['MAP','fail','api','rpc','auth','entitlement','venue','resolveProduct','resolveIngredient','resolveStaff'])assert.ok(context.includes(symbol),`${symbol} must live in manager action context`);});
test('manager AI action keeps one canonical mutation boundary',()=>{const source=readLib('ai/manager/action.js');assert.ok(source.includes('async function run(c,f,a,e)'));assert.ok(source.includes("if(!(MAP[f]||[]).includes(type))throw fail('ACTION_NOT_ALLOWED_FOR_FEATURE:"));assert.ok(source.includes("const vid=str(p.venue_id,80)"));for(const line of ["if(menu.TYPES.has(type))return menu.run(type,c,vid,p,e);","if(ingredients.TYPES.has(type))return ingredients.run(type,c,vid,p);","if(staff.TYPES.has(type))return staff.run(type,c,vid,p);","if(recipes.TYPES.has(type))return recipes.run(type,c,vid,p);"])assert.ok(source.includes(line));});
test('manager AI menu mutations are isolated by venue and permission',()=>{const source=readLib('ai/manager/mutations/menu.js');assert.ok(source.includes("await venue(c,vid,'menu')"));assert.ok(source.includes("await venue(c,vid,'price')"));assert.ok(source.includes('venue_id=eq.'));assert.ok(source.includes("'DELETE'"));assert.ok(source.includes("'PATCH'"));});
test('manager AI ingredient mutations are isolated by venue and permission',()=>{const source=readLib('ai/manager/mutations/ingredients.js');assert.ok(source.includes("await venue(c,vid,'menu')"));assert.ok(source.includes('p_venue_id:vid'));assert.ok(source.includes('venue_id=eq.'));assert.ok(source.includes('manager_ingredient_upsert'));assert.ok(source.includes('manager_ingredient_delete'));});
test('manager AI staff mutations are isolated by venue and permission',()=>{const source=readLib('ai/manager/mutations/staff.js');assert.ok(source.includes("await venue(c,vid,'venue')"));assert.ok(source.includes('p_venue_id:vid'));assert.ok(source.includes('venue_id=eq.'));assert.ok(source.includes('manager_create_staff'));assert.ok(source.includes('manager_reset_staff_pin'));assert.ok(source.includes("'DELETE'"));assert.ok(source.includes("/^\\d{4}$/"));});
test('manager AI non-menu/ingredient/staff mutation families retain venue isolation',()=>{const source=readLib('ai/manager/action.js');const guardedFamilies=[["if(type==='update_order')",'update_order'],["if(type==='update_venue_settings'||type==='update_delivery_settings')",'venue settings'],["if(type==='save_design')",'save_design'],["if(type==='update_delivery_integration'||type==='delete_delivery_integration')",'delivery integrations'],["if(H.includes(type))",'hall/table mutations'],["if(type==='disconnect_integration')",'POS disconnect']];for(const [marker,label] of guardedFamilies){const at=source.indexOf(marker);assert.notEqual(at,-1,`${label} branch must exist`);const guard=source.indexOf('await venue(c,vid,',at);assert.ok(guard>at,`${label} must verify venue access before its mutation boundary`);}});
test('manager AI recipe mutation family no longer remains in central action dispatcher',()=>{const source=readLib('ai/manager/action.js');for(const marker of ["if(type==='recipe_auto_sync')","if(['attach_ingredients','create_tech_card','save_recipe'].includes(type)"])assert.equal(source.includes(marker),false,`${marker} must be extracted`);});
test('manager AI resolver queries are venue-scoped',()=>{const source=readLib('ai/manager/context.js');for(const table of ['products','ingredients','cooks','couriers','waiters'])assert.ok(source.includes(`${table}?venue_id=eq.`),`${table} resolver must be venue-scoped`);});
