'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'../..');
const read=relative=>fs.readFileSync(path.join(root,relative),'utf8');
function walk(dir){const out=[];for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,entry.name);if(entry.isDirectory())out.push(...walk(full));else out.push(full);}return out;}
function normalize(value){return String(value||'').split('#',1)[0].split('?',1)[0].trim();}
function external(value){return !value||value.startsWith('#')||value.startsWith('data:')||value.startsWith('blob:')||value.startsWith('mailto:')||value.startsWith('tel:')||value.startsWith('javascript:')||/^[a-z][a-z\d+.-]*:/i.test(value);}
function dynamic(value){const v=String(value||'');return /\{\{|\}\}|\$\{|\|\||^[A-Za-z_$][\w$]*(?:\.[A-Za-z_$][\w$]*)+$/.test(v);}
function routePattern(source){let pattern=String(source).replace(/:path\*/g,'__WILDCARD__').replace(/:role/g,'__ROLE__');pattern=pattern.replace(/[.+?^${}()|[\]\\]/g,'\\$&');return new RegExp(`^${pattern.replace('__WILDCARD__','.*').replace('__ROLE__','[^/]+')}$`);}
function routes(){const config=JSON.parse(read('vercel.json'));return[...(config.redirects||[]),...(config.rewrites||[])];}
function routeCovers(urlPath,list){return list.some(route=>route&&typeof route.source==='string'&&routePattern(route.source).test(urlPath));}
function localExists(urlPath){const relative=String(urlPath).replace(/^\/+/, '');return fs.existsSync(path.join(root,relative))||fs.existsSync(path.join(root,`${relative}.js`))||fs.existsSync(path.join(root,`${relative}.cjs`));}
function resolve(ref,owner){const clean=normalize(ref);if(external(clean)||dynamic(clean))return null;if(clean.startsWith('/'))return clean;return `/${path.posix.normalize(path.posix.join(path.posix.dirname(owner),clean))}`;}
function assertResolvable(ref,owner,list,label){const target=resolve(ref,owner);if(!target)return;assert.ok(localExists(target)||routeCovers(target,list),`${label}: ${owner} -> ${ref} resolves to ${target}, but no file or Vercel route covers it`);}
function legacy(ref){const clean=normalize(ref).replace(/^\.\//,'');if(!clean||external(clean)||dynamic(clean))return false;return /^(?:\/?(?:js|css|img|icons|pwa)\/|\/?(?:manifest(?:-[A-Za-z0-9_-]+)?\.webmanifest|favicon\.svg|apple-touch-icon\.png)$)/i.test(clean)||/^(?:\/?(?:index|menu|waiter|cook|courier|hall|staff-history|staff-table|manager|manager-demo|manager-staff-statistics|integrations|admin|login|register|forgot-password|reset-password|staff-guide)\.html)$/i.test(clean);}
function htmlRefs(source){const out=[];const re=/\b(?:src|href|poster|action)=\s*["']([^"']+)["']/gi;let m;while((m=re.exec(source)))out.push(m[1]);return out;}
function cssRefs(source){const out=[];const re=/url\(\s*["']?([^"')]+)["']?\s*\)/gi;let m;while((m=re.exec(source)))out.push(m[1]);return out;}
function jsRefs(source){const out=[];const patterns=[/(?:src)\s*[:=]\s*["'`]([^"'`\s<>]+)["'`]/gi,/(?:fetch|window\.open|location(?:\.assign|\.replace)?|window\.location(?:\.assign|\.replace)?)\s*\(\s*["'`]([^"'`]+)["'`]/gi,/(?:location\.href|window\.location(?:\.href)?)\s*=\s*["'`]([^"'`]+)["'`]/gi,/\badd\s*\(\s*["'`]([^"'`]+)["'`]/gi];for(const re of patterns){let m;while((m=re.exec(source))){const ref=m[1];if(/^\/?(?:api\/|src\/|js\/|css\/|img\/|icons\/|pwa\/|[A-Za-z0-9_.-]+\.html(?:[?#]|$)|[A-Za-z0-9_.-]+\.(?:js|css|webmanifest)(?:[?#]|$))/.test(ref))out.push(ref);}}return out;}

test('all canonical HTML local resources resolve to files or declared Vercel routes',()=>{const list=routes();for(const file of walk(path.join(root,'src/pages')).filter(x=>x.endsWith('.html'))){const owner=`/${path.relative(root,file).split(path.sep).join('/')}`;for(const ref of htmlRefs(fs.readFileSync(file,'utf8'))){assert.equal(legacy(ref),false,`${owner} still references legacy runtime path ${ref}`);assertResolvable(ref,owner,list,'HTML path contract');}}});
test('repository JavaScript local asset and page navigation URLs resolve',()=>{const list=routes();for(const file of walk(path.join(root,'src/assets/js')).filter(x=>/\.(?:js|cjs|mjs)$/.test(x))){const owner=`/${path.relative(root,file).split(path.sep).join('/')}`;for(const ref of jsRefs(fs.readFileSync(file,'utf8'))){assert.equal(legacy(ref),false,`${owner} still references legacy runtime path ${ref}`);assertResolvable(ref,owner,list,'JS path contract');}}});
test('canonical CSS url() assets resolve to files or declared Vercel routes',()=>{const list=routes();for(const file of walk(path.join(root,'src/assets/css')).filter(x=>x.endsWith('.css'))){const owner=`/${path.relative(root,file).split(path.sep).join('/')}`;for(const ref of cssRefs(fs.readFileSync(file,'utf8'))){assert.equal(legacy(ref),false,`${owner} still references legacy runtime path ${ref}`);assertResolvable(ref,owner,list,'CSS path contract');}}});
test('service worker precache uses canonical physical paths',()=>{const list=routes();const source=read('sw.js');const refs=[...source.matchAll(/(?:CORE|PRECACHE|ASSETS)\s*=\s*\[([\s\S]*?)\]/g)].flatMap(m=>[...m[1].matchAll(/["']([^"']+)["']/g)].map(x=>x[1]));for(const ref of refs){assert.equal(legacy(ref),false,`sw.js references legacy runtime path ${ref}`);assertResolvable(ref,'/sw.js',list,'Service worker path contract');}});
test('no canonical runtime source embeds a legacy resource URL in a resource context',()=>{const groups=[['html',walk(path.join(root,'src/pages')).filter(x=>x.endsWith('.html')),htmlRefs],['js',walk(path.join(root,'src/assets/js')).filter(x=>/\.(?:js|cjs|mjs)$/.test(x)),jsRefs],['css',walk(path.join(root,'src/assets/css')).filter(x=>x.endsWith('.css')),cssRefs]];for(const [,files,collector] of groups)for(const file of files){const owner=`/${path.relative(root,file).split(path.sep).join('/')}`;for(const ref of collector(fs.readFileSync(file,'utf8')))assert.equal(legacy(ref),false,`${owner} contains legacy resource URL ${ref}; compatibility rewrites are not an internal fix`);}});
test('declared Vercel redirects and rewrites do not point at missing destinations',()=>{const list=routes();for(const route of list){if(!route||typeof route.destination!=='string'||external(route.destination))continue;const destination=normalize(route.destination);if(!destination||/:path\*/.test(destination)||/\$\d/.test(destination)||dynamic(destination))continue;assert.ok(localExists(destination)||routeCovers(destination,list),`Vercel route destination is not backed by a file or another route: ${route.source} -> ${destination}`);}});
test('canonical manifests and root service worker are physically present',()=>{for(const file of ['sw.js','src/assets/pwa/manifest.webmanifest','src/assets/pwa/manifest-admin.webmanifest','src/assets/pwa/manifest-cook.webmanifest','src/assets/pwa/manifest-courier.webmanifest','src/assets/pwa/manifest-manager.webmanifest','src/assets/pwa/manifest-waiter.webmanifest'])assert.ok(fs.existsSync(path.join(root,file)),`required runtime file is missing: ${file}`);});
test('guest manager compatibility URL remains explicitly routed to canonical manager page',()=>{assert.ok(routeCovers('/src/pages/guest/manager.html',routes()));});
