/* QR-Menu — просмотр меню заведений (админ) */
(function(){
'use strict';
if(window.__QR_ADMIN_MENU__)return;
window.__QR_ADMIN_MENU__=true;
var menuMixin={
data:function(){return{menuVenueId:'',menuVenueProducts:[],prodModal:{show:false,venueId:null,venueName:'',list:[],form:{name:'',price:0,category:'main'}},DEFAULT_IMG:window.DEFAULT_IMG||"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><rect width='80' height='80' fill='%231f2937'/><text x='50%' y='50%' text-anchor='middle' dy='.3em' fill='%239ca3af' font-size='30'>🍽</text></svg>"};},
methods:{
categoryLabel:function(c){var l={main:'Основные блюда',starters:'Закуски',salads:'Салаты',soups:'Супы',hot:'Горячие блюда',pizza:'Пицца',burgers:'Бургеры',rolls:'Роллы',sushi:'Суши',desserts:'Десерты',drinks:'Напитки',coffee:'Кофе',tea:'Чай',cocktails:'Коктейли',sides:'Гарниры',sauces:'Соусы',addons:'Добавки',breakfast:'Завтраки',lunch:'Обеды',other:'Другое'};c=String(c==null?'':c).trim().toLowerCase();return l[c]||(c||'Без категории');},
loadMenuVenue:function(){var s=this;if(!s.menuVenueId){s.menuVenueProducts=[];return;}db.from('products').select('*').eq('venue_id',s.menuVenueId).order('category').then(function(r){if(r.error)throw r.error;s.menuVenueProducts=r.data||[];s.bindMenuCardEditors();}).catch(function(e){console.warn('Ошибка загрузки меню:',e);});},
bindMenuCardEditors:function(){var s=this;setTimeout(function(){var g=document.querySelector('#app .menu-grid');if(!g||g.__qrBound)return;g.__qrBound=true;g.addEventListener('click',function(e){if(e.target.closest('button,input,select,textarea,label,a'))return;var card=e.target.closest('.menu-grid>.card');if(!card)return;var i=Array.prototype.indexOf.call(g.children,card),p=(s.menuVenueProducts||[])[i];if(p)s.openProductEditor(p);});},50);},
openProductEditor:function(p){if(!p)return;var v=(this.venues||[]).find(function(x){return x.id===p.venue_id;});this.prodModal={show:true,venueId:p.venue_id,venueName:v?v.name:'',list:[JSON.parse(JSON.stringify(p))],form:{name:'',price:0,category:'main'}};},
openVenueMenu:function(v){var s=this;s.prodModal={show:true,venueId:v.id,venueName:v.name,list:[],form:{name:'',price:0,category:'main'}};db.from('products').select('*').eq('venue_id',v.id).order('created_at').then(function(r){if(r.error)throw r.error;s.prodModal.list=r.data||[];}).catch(function(e){console.warn('Ошибка загрузки меню:',e);});},
openVenueMenuById:function(id){if(!id)return;var v=this.venues.find(function(x){return x.id===id;});if(v)this.openVenueMenu(v);},
uploadProdPhoto:function(ev,p){var s=this,f=ev.target.files[0];if(!f)return;s.resizeImage(f,900,.85).then(function(b){var fn=s.prodModal.venueId+'/prod_'+Date.now()+'.jpg';return db.storage.from('menu-images').upload(fn,b,{cacheControl:'3600',upsert:true,contentType:'image/jpeg'}).then(function(r){if(r.error)throw r.error;var u=db.storage.from('menu-images').getPublicUrl(fn).data.publicUrl;return db.from('products').update({image_url:u}).eq('id',p.id).then(function(x){if(x.error)throw x.error;p.image_url=u;var live=(s.menuVenueProducts||[]).find(function(q){return q.id===p.id;});if(live)live.image_url=u;});});}).catch(function(e){alert('Ошибка: '+e.message);}).finally(function(){ev.target.value='';});},
saveProductRow:function(p){var s=this;db.from('products').update({name:p.name,price:Number(p.price)||0,category:p.category}).eq('id',p.id).then(function(r){if(r.error){alert('Ошибка сохранения: '+r.error.message);return;}var live=(s.menuVenueProducts||[]).find(function(x){return x.id===p.id;});if(live){live.name=p.name;live.price=Number(p.price)||0;live.category=p.category;}});},
toggleAvailRow:function(p){var s=this;p.is_available=!p.is_available;db.from('products').update({is_available:p.is_available}).eq('id',p.id).then(function(r){if(r.error){p.is_available=!p.is_available;return;}var live=(s.menuVenueProducts||[]).find(function(x){return x.id===p.id;});if(live)live.is_available=p.is_available;});},
delProductRow:function(p){var s=this;if(!confirm('Удалить «'+p.name+'»?'))return;db.from('products').delete().eq('id',p.id).then(function(r){if(r.error)throw r.error;s.prodModal.list=s.prodModal.list.filter(function(x){return x.id!==p.id;});s.menuVenueProducts=(s.menuVenueProducts||[]).filter(function(x){return x.id!==p.id;});}).catch(function(e){alert('Ошибка: '+e.message);});},
addProductRow:function(){var s=this;if(!s.prodModal.form.name)return;db.from('products').insert({venue_id:s.prodModal.venueId,name:s.prodModal.form.name,price:Number(s.prodModal.form.price)||0,category:s.prodModal.form.category,applies_to:'all',is_available:true}).select().single().then(function(r){if(r.error)throw r.error;if(r.data){s.prodModal.list.push(r.data);if(s.menuVenueId===s.prodModal.venueId)s.menuVenueProducts.push(r.data);}s.prodModal.form={name:'',price:0,category:'main'};}).catch(function(e){alert('Ошибка добавления блюда: '+e.message);});}
}};
window.__QR_ADMIN_MENU_MIXIN__=menuMixin;
})();
