'use strict';

const U=process.env.SUPABASE_URL||'https://ulxfsozdryqrnlxzlblt.supabase.co';
const A=process.env.SUPABASE_ANON_KEY||process.env.SUPABASE_PUBLISHABLE_KEY||'';
const S=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const H=['create_table','update_table','move_table','delete_table','regenerate_table_qr','set_table_status','seat_table','set_table_reservation_guest','close_table_session','save_hall_plan','delete_hall_plan'];
const POS=['iiko','quick_resto','r_keeper','poster','onec','saby_presto','yuma','syrve','tillypad','evotor','frontol','frontpad','fast_operator','jowi','smarttouch','traktir','restik','paladin','parus_restaurant','kontur_market'];
const DEL=['yandex','delivery','samokat','custom'];
const MAP={assistant:['create_product','update_product','update_product_price','delete_product','create_ingredient','update_ingredient','delete_ingredient','attach_ingredients','create_staff','delete_staff','reset_staff_pin','update_order','update_venue_settings','update_delivery_settings','update_delivery_integration','delete_delivery_integration','save_design','create_venue','change_trial_plan','create_tech_card','disconnect_integration',...H],menu_analysis:['update_product','update_product_price'],analytics:['update_product_price'],recipes:['save_recipe','update_product','update_product_price','create_product','create_ingredient','update_ingredient','delete_ingredient','attach_ingredients','create_tech_card'],chef:['update_product','update_product_price','create_product','save_recipe','create_ingredient','update_ingredient','delete_ingredient','create_tech_card'],staff:['create_staff','delete_staff','reset_staff_pin'],marketing:['marketing_draft'],settings:['update_venue_settings','update_delivery_settings','update_delivery_integration','delete_delivery_integration','save_design','disconnect_integration','update_order'],hall:H,engineer:[]};

const fail=(m,s)=>Object.assign(new Error(m),{status:s});
const bearer=req=>{const m=String(req.headers?.authorization||req.headers?.Authorization||'').match(/^Bearer\s+(.+)$/i);return m?m[1].trim():''};
async function api(path,t,method='GET',body){const r=await fetch(U+'/rest/v1/'+path,{method,headers:{apikey:S||A,authorization:'Bearer '+t,accept:'application/json','Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}),d=await r.json().catch(()=>null);if(!r.ok)throw fail(d?.message||d?.hint||d?.details||'SUPABASE_HTTP_'+r.status,r.status);return d}
async function rpc(name,args,t){const r=await fetch(U+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:A,authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify(args||{})}),d=await r.json().catch(()=>null);if(!r.ok)throw fail(d?.message||d?.hint||d?.details||'RPC_'+name+'_FAILED',r.status);return d}
async function auth(req){const t=bearer(req);if(!t)throw fail('AUTH_REQUIRED',401);const r=await fetch(U+'/auth/v1/user',{headers:{apikey:A,authorization:'Bearer '+t}}),u=await r.json().catch(()=>null);if(!r.ok||!u?.id)throw fail('AUTH_INVALID',401);const p=await api('profiles?id=eq.'+encodeURIComponent(u.id)+'&select=id,role&limit=1',t);if(!p?.[0]||String(p[0].role).toLowerCase()!=='manager')throw fail('MANAGER_ONLY',403);return{token:t,user:u}}
function active(s){if(!s)return false;const st=String(s.status||'').toLowerCase();return st==='trialing'||(st==='active'&&(!s.current_period_end||new Date(s.current_period_end)>=new Date()))}
async function entitlement(c,f){if(!MAP[f])throw fail('AI_ACTIONS_NOT_AVAILABLE_FOR_FEATURE',403);const s=await api('subscriptions?manager_id=eq.'+encodeURIComponent(c.user.id)+'&venue_id=is.null&status=in.(trialing,active)&select=plan_id,status,current_period_end&order=created_at.desc&limit=1',c.token);if(!s?.[0]||!active(s[0]))throw fail('AI_SUBSCRIPTION_REQUIRED',403);const p=(await api('plans?id=eq.'+encodeURIComponent(s[0].plan_id)+'&is_active=eq.true&select=id,name,ai_enabled,ai_features,max_products,max_cooks,max_couriers,max_waiters,max_venues&limit=1',c.token))?.[0],fs=p?.ai_features&&typeof p.ai_features==='object'?p.ai_features:{};if(!p)throw fail('AI_PLAN_REQUIRED',403);if(s[0].status!=='trialing'&&(p.ai_enabled!==true||fs[f]!==true))throw fail('AI_FEATURE_NOT_INCLUDED:'+f,403);return{plan:p,subscription:s[0]}}
async function venue(c,id,need){if(!id)throw fail('VENUE_REQUIRED',400);const own=await api('manager_venues?manager_id=eq.'+encodeURIComponent(c.user.id)+'&venue_id=eq.'+encodeURIComponent(id)+'&select=id,venue_id&limit=1',c.token);if(!own?.[0])throw fail('VENUE_ACCESS_DENIED',403);let p=null;const rows=await api('manager_venue_permissions?manager_id=eq.'+encodeURIComponent(c.user.id)+'&venue_id=eq.'+encodeURIComponent(id)+'&select=can_edit_menu,can_edit_prices,can_edit_delivery,can_edit_design,can_edit_branding,can_edit_venue&limit=1',c.token);if(rows?.[0])p=rows[0];else{const v=(await api('venues?id=eq.'+encodeURIComponent(id)+'&select=manager_permissions&limit=1',c.token))?.[0];const m=v?.manager_permissions||{};p={can_edit_menu:m.products!==false,can_edit_prices:m.prices!==false,can_edit_delivery:m.delivery!==false,can_edit_design:m.design!==false,can_edit_branding:m.branding===true,can_edit_venue:m.venue===true};}if(need==='menu'&&!p.can_edit_menu)throw fail('PRODUCT_EDIT_PERMISSION_DENIED',403);if(need==='price'&&!p.can_edit_prices)throw fail('PRICE_EDIT_PERMISSION_DENIED',403);if(need==='delivery'&&!p.can_edit_delivery)throw fail('DELIVERY_EDIT_PERMISSION_DENIED',403);if(need==='design'&&!p.can_edit_design)throw fail('DESIGN_EDIT_PERMISSION_DENIED',403);if(need==='branding'&&!p.can_edit_branding)throw fail('BRANDING_EDIT_PERMISSION_DENIED',403);if(need==='venue'&&!p.can_edit_venue)throw fail('VENUE_EDIT_PERMISSION_DENIED',403);return{id}}
function num(v,d){const n=Number(v);return Number.isFinite(n)?n:d}
function str(v,n){return String(v==null?'':v).trim().slice(0,n||500)}
function product(p){const o={};['name','description','price','category','image_url','is_available','applies_to'].forEach(k=>{if(k in p)o[k]=p[k]});if(o.name!==undefined){o.name=str(o.name,220);if(!o.name)throw fail('PRODUCT_NAME_REQUIRED',400)}if(o.price!==undefined){o.price=Number(o.price);if(!Number.isFinite(o.price)||o.price<0||o.price>1e7)throw fail('PRODUCT_PRICE_INVALID',400)}if(o.category!==undefined)o.category=str(o.category,120)||'main';if(o.is_available!==undefined)o.is_available=!!o.is_available;return o}
function venuePatch(p){const o={};['name','description','brand_color','logo_url','address','phone','website_url','opening_hours','latitude','longitude','lat','lng','delivery_enabled','delivery_min_order','delivery_min_order_free','delivery_base_fee','delivery_rate_per_km','delivery_max_km'].forEach(k=>{if(k in p)o[k]=p[k]});if(o.name!==undefined)o.name=str(o.name,220);if(o.description!==undefined)o.description=str(o.description,4000)||null;if(o.brand_color!==undefined&&o.brand_color!==null&&!/^#[0-9a-fA-F]{6}$/.test(String(o.brand_color)))throw fail('BRAND_COLOR_INVALID',400);['delivery_min_order','delivery_min_order_free','delivery_base_fee','delivery_rate_per_km','delivery_max_km','latitude','longitude','lat','lng'].forEach(k=>{if(o[k]!==undefined){o[k]=Number(o[k]);if(!Number.isFinite(o[k]))throw fail('VENUE_NUMBER_INVALID:'+k,400)}});return o}
async function resolveProduct(c,p,required=true){if(p.product_id)return String(p.product_id);const name=str(p.product_name,220);if(!name){if(required)throw fail('PRODUCT_ID_OR_NAME_REQUIRED',400);return''}const rows=await api('products?venue_id=eq.'+encodeURIComponent(p.venue_id)+'&name=ilike.'+encodeURIComponent(name)+'&select=id,name,price,description,category,is_available,image_url,applies_to&limit=10',c.token);if(!rows?.length)throw fail('PRODUCT_NOT_FOUND:'+name,404);const exact=rows.filter(x=>String(x.name).toLowerCase()===name.toLowerCase());if(exact.length!==1&&rows.length!==1)throw fail('PRODUCT_AMBIGUOUS:'+name,409);return String((exact[0]||rows[0]).id)}
async function resolveIngredient(c,p){if(p.ingredient_id)return String(p.ingredient_id);const name=str(p.ingredient_name,220);if(!name)throw fail('INGREDIENT_ID_OR_NAME_REQUIRED',400);const rows=await api('ingredients?venue_id=eq.'+encodeURIComponent(p.venue_id)+'&name=ilike.'+encodeURIComponent(name)+'&select=id,name,unit,purchase_quantity,purchase_price&limit=10',c.token);if(!rows?.length)throw fail('INGREDIENT_NOT_FOUND:'+name,404);const exact=rows.filter(x=>String(x.name).toLowerCase()===name.toLowerCase());if(exact.length!==1&&rows.length!==1)throw fail('INGREDIENT_AMBIGUOUS:'+name,409);return String((exact[0]||rows[0]).id)}
async function resolveStaff(c,p){if(p.staff_id)return String(p.staff_id);const name=str(p.staff_name,220);if(!name)throw fail('STAFF_ID_OR_NAME_REQUIRED',400);const all=[];for(const t of ['cooks','couriers','waiters']){const r=await api(t+'?venue_id=eq.'+encodeURIComponent(p.venue_id)+'&name=ilike.'+encodeURIComponent(name)+'&select=id,name&limit=10',c.token);(r||[]).forEach(x=>all.push({id:String(x.id),name:String(x.name),type:t==='cooks'?'cook':t==='couriers'?'courier':'waiter'}));}const exact=all.filter(x=>x.name.toLowerCase()===name.toLowerCase());if(exact.length!==1)throw fail('STAFF_AMBIGUOUS:'+name,409);p.type=p.type||exact[0].type;return exact[0].id}

module.exports={U,A,S,H,POS,DEL,MAP,fail,api,rpc,auth,entitlement,venue,num,str,product,venuePatch,resolveProduct,resolveIngredient,resolveStaff};