const crypto=require('crypto');
const {bearer,getManagerUser}=require('../_lib/manager-auth');
const SUPABASE_URL='https://ulxfsozdryqrnlxzlblt.supabase.co';
const IIKO_BASE=(process.env.IIKO_API_BASE_URL||'https://api-ru.iiko.services').replace(/\/$/,'');
const IIKO_TOKEN_PATH=process.env.IIKO_TOKEN_PATH||'/api/1/access_token';
function send(res,status,body){res.status(status).setHeader('Content-Type','application/json; charset=utf-8').end(JSON.stringify(body));}
function serviceHeaders(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY;if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured');return {apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};}
async function sb(path,options={}){const r=await fetch(`${SUPABASE_URL}${path}`,{...options,headers:{...serviceHeaders(),...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null;}catch(_){data={raw:text};}if(!r.ok)throw new Error((data&&(data.message||data.error))||`Supabase ${r.status}`);return data;}
function encryptionKey(){const raw=process.env.INTEGRATION_ENCRYPTION_KEY;if(!raw)throw new Error('INTEGRATION_ENCRYPTION_KEY is not configured');return crypto.createHash('sha256').update(raw).digest();}
function encrypt(value){const iv=crypto.randomBytes(12);const c=crypto.createCipheriv('aes-256-gcm',encryptionKey(),iv);const out=Buffer.concat([c.update(JSON.stringify(value),'utf8'),c.final()]);return [iv.toString('base64url'),c.getAuthTag().toString('base64url'),out.toString('base64url')].join('.');}
function decrypt(value){const [iv,tag,payload]=String(value||'').split('.');if(!iv||!tag||!payload)throw new Error('invalid_credentials');const d=crypto.createDecipheriv('aes-256-gcm',encryptionKey(),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(payload,'base64url')),d.final()]).toString('utf8'));}
async function assertVenueAccess(userId,venueId,role){if(role==='admin')return;const rows=await sb(`/rest/v1/manager_venues?manager_id=eq.${encodeURIComponent(userId)}&venue_id=eq.${encodeURIComponent(venueId)}&select=id,venue_id&limit=1`);if(!Array.isArray(rows)||!rows.length)throw Object.assign(new Error('venue_access_required'),{status:403});}
async function iikoRequest(path,token,body){const r=await fetch(`${IIKO_BASE}${path}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body||{})});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null;}catch(_){data={raw:text};}if(!r.ok)throw new Error((data&&(data.message||data.description||data.error))||`iiko ${r.status}`);return data;}
async function getIikoToken(credentials){const r=await fetch(`${IIKO_BASE}${IIKO_TOKEN_PATH}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(credentials)});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null;}catch(_){data={raw:text};}if(!r.ok)throw new Error((data&&(data.message||data.description||data.error))||`iiko auth ${r.status}`);const token=data&&(data.token||data.access_token);if(!token)throw new Error('iiko_token_missing');return token;}
function organizationIds(data){const list=Array.isArray(data)?data:(data&&Array.isArray(data.organizations)?data.organizations:(data&&Array.isArray(data.data)?data.data:[]));return list.map(x=>x&&x.id).filter(Boolean);}
function productList(data){return Array.isArray(data)?data:(data&&Array.isArray(data.products)?data.products:[]);}
module.exports=async function handler(req,res){if(req.method!=='POST')return send(res,405,{error:'method_not_allowed'});try{const user=await getManagerUser(bearer(req));const body=req.body||{};const action=body.action;const venueId=body.venue_id;if(!venueId)return send(res,400,{error:'venue_id_required'});await assertVenueAccess(user.id,venueId,user.role);
if(action==='connect'){if(!body.credentials||typeof body.credentials!=='object')return send(res,400,{error:'credentials_required'});const token=await getIikoToken(body.credentials);const meta=await iikoRequest('/api/1/organizations',token,{});const organizations=Array.isArray(meta)?meta:(meta&&Array.isArray(meta.organizations)?meta.organizations:(meta&&Array.isArray(meta.data)?meta.data:[]));const encrypted=encrypt(body.credentials);const existing=await sb(`/rest/v1/venue_integrations?venue_id=eq.${encodeURIComponent(venueId)}&provider=eq.iiko&select=id&limit=1`);const payload={venue_id:venueId,provider:'iiko',status:'connected',credentials_encrypted:encrypted,metadata:{organizations_count:organizations.length,organization_ids:organizationIds(meta)},error_message:null};if(existing&&existing[0])await sb(`/rest/v1/venue_integrations?id=eq.${encodeURIComponent(existing[0].id)}`,{method:'PATCH',body:JSON.stringify(payload)});else await sb('/rest/v1/venue_integrations',{method:'POST',body:JSON.stringify(payload)});return send(res,200,{ok:true,provider:'iiko',organizations_count:organizations.length,organizations});}
const rows=await sb(`/rest/v1/venue_integrations?venue_id=eq.${encodeURIComponent(venueId)}&provider=eq.iiko&select=id,status,credentials_encrypted,metadata,last_sync_at,error_message&limit=1`);const integration=rows&&rows[0];if(!integration||!integration.credentials_encrypted)return send(res,404,{error:'iiko_not_connected'});const token=await getIikoToken(decrypt(integration.credentials_encrypted));
if(action==='test'||action==='organizations'){const organizations=await iikoRequest('/api/1/organizations',token,{});return send(res,200,{ok:true,organizations});}
if(action==='nomenclature'){let ids=Array.isArray(body.organization_ids)?body.organization_ids.filter(Boolean):[];if(!ids.length)ids=organizationIds(await iikoRequest('/api/1/organizations',token,{}));if(!ids.length)return send(res,400,{error:'iiko_organization_required'});const nomenclature=await iikoRequest('/api/1/nomenclature',token,{organizationIds:ids,returnType:'PRODUCTS',includeDeleted:false});const products=productList(nomenclature);const groups=nomenclature&&Array.isArray(nomenclature.groups)?nomenclature.groups:[];await sb(`/rest/v1/venue_integrations?id=eq.${encodeURIComponent(integration.id)}`,{method:'PATCH',body:JSON.stringify({status:'connected',last_sync_at:new Date().toISOString(),metadata:{...(integration.metadata||{}),organization_ids:ids,products_count:products.length,groups_count:groups.length}})});return send(res,200,{ok:true,organization_ids:ids,products_count:products.length,groups_count:groups.length,nomenclature});}
return send(res,400,{error:'unknown_action'});
}catch(e){return send(res,e.status||500,{error:e.message||'integration_error'});}};
