'use strict';
const crypto=require('crypto');
const {bearer,getManagerUser}=require('../_lib/manager-auth');
const SUPABASE_URL='https://ulxfsozdryqrnlxzlblt.supabase.co';
const PROVIDERS=['quick_resto','r_keeper','poster','evotor','onec','tillypad','frontol'];
function send(res,status,body){res.status(status).setHeader('Content-Type','application/json; charset=utf-8').end(JSON.stringify(body));}
function headers(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY;if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured');return {apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};}
async function sb(path,options={}){const r=await fetch(`${SUPABASE_URL}${path}`,{...options,headers:{...headers(),...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch(_){data={raw:text}}if(!r.ok)throw new Error((data&&(data.message||data.error))||`Supabase ${r.status}`);return data;}
function key(){const raw=process.env.INTEGRATION_ENCRYPTION_KEY;if(!raw)throw new Error('INTEGRATION_ENCRYPTION_KEY is not configured');return crypto.createHash('sha256').update(raw).digest();}
function encrypt(v){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv);const out=Buffer.concat([c.update(JSON.stringify(v),'utf8'),c.final()]);return [iv.toString('base64url'),c.getAuthTag().toString('base64url'),out.toString('base64url')].join('.');}
async function access(user,venue){if(user.role==='admin')return;const rows=await sb(`/rest/v1/manager_venues?manager_id=eq.${encodeURIComponent(user.id)}&venue_id=eq.${encodeURIComponent(venue)}&select=id&limit=1`);if(!rows.length)throw Object.assign(new Error('venue_access_required'),{status:403});}
module.exports=async function(req,res){if(req.method!=='POST')return send(res,405,{error:'method_not_allowed'});try{const user=await getManagerUser(bearer(req));const b=req.body||{};if(b.action!=='save')return send(res,400,{error:'unknown_action'});const provider=String(b.provider||'').trim();const venue=String(b.venue_id||'').trim();if(!PROVIDERS.includes(provider))return send(res,400,{error:'unsupported_provider'});if(!venue)return send(res,400,{error:'venue_id_required'});await access(user,venue);const credentials=b.credentials&&typeof b.credentials==='object'?b.credentials:{};if(!Object.keys(credentials).length)return send(res,400,{error:'credentials_required'});const existing=await sb(`/rest/v1/venue_integrations?venue_id=eq.${encodeURIComponent(venue)}&provider=eq.${encodeURIComponent(provider)}&select=id&limit=1`);const payload={venue_id:venue,provider,status:'disconnected',credentials_encrypted:encrypt(credentials),metadata:{configured_at:new Date().toISOString(),configured_by:user.id},error_message:null};if(existing&&existing[0])await sb(`/rest/v1/venue_integrations?id=eq.${encodeURIComponent(existing[0].id)}`,{method:'PATCH',body:JSON.stringify(payload)});else await sb('/rest/v1/venue_integrations',{method:'POST',body:JSON.stringify(payload)});return send(res,200,{ok:true,provider,status:'disconnected'});}catch(e){return send(res,e.status||500,{error:e.message||'integration_error'});}};
