'use strict';
const crypto=require('crypto');
const {bearer,getManagerUser}=require('../_lib/manager-auth');
const SUPABASE_URL='https://ulxfsozdryqrnlxzlblt.supabase.co';
const SUPPORTED=['quick_resto','r_keeper'];
function send(res,status,body){res.status(status).setHeader('Content-Type','application/json; charset=utf-8').end(JSON.stringify(body));}
function sh(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY;if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured');return {apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};}
async function sb(path,o={}){const r=await fetch(`${SUPABASE_URL}${path}`,{...o,headers:{...sh(),...(o.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(_){d={raw:t}}if(!r.ok)throw new Error((d&&(d.message||d.error))||`Supabase ${r.status}`);return d;}
function ek(){const raw=process.env.INTEGRATION_ENCRYPTION_KEY;if(!raw)throw new Error('INTEGRATION_ENCRYPTION_KEY is not configured');return crypto.createHash('sha256').update(raw).digest();}
function enc(v){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',ek(),iv),out=Buffer.concat([c.update(JSON.stringify(v),'utf8'),c.final()]);return [iv.toString('base64url'),c.getAuthTag().toString('base64url'),out.toString('base64url')].join('.');}
function dec(v){const [iv,tag,p]=String(v||'').split('.');if(!iv||!tag||!p)throw new Error('invalid_credentials');const d=crypto.createDecipheriv('aes-256-gcm',ek(),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(p,'base64url')),d.final()]).toString('utf8'));}
async function access(u,v){if(u.role==='admin')return;const r=await sb(`/rest/v1/manager_venues?manager_id=eq.${encodeURIComponent(u.id)}&venue_id=eq.${encodeURIComponent(v)}&select=id&limit=1`);if(!r.length)throw Object.assign(new Error('venue_access_required'),{status:403});}
function normalize(provider,c){c=c&&typeof c==='object'?c:{};if(provider==='quick_resto'){const login=String(c.login||c.api_login||'').trim(),password=String(c.password||c.api_password||'').trim(),base_url=String(c.base_url||process.env.QUICK_RESTO_API_BASE_URL||'').trim().replace(/\/$/,'');if(!login||!password)throw Object.assign(new Error('quick_resto_credentials_required'),{status:400});if(!base_url)throw Object.assign(new Error('quick_resto_api_url_required'),{status:400});return {login,password,base_url};}const base_url=String(c.base_url||'').trim().replace(/\/$/,''),client_id=String(c.client_id||c.clientId||'').trim(),client_secret=String(c.client_secret||c.clientSecret||'').trim(),object_id=String(c.object_id||c.objectId||'').trim();if(!base_url||!client_id||!client_secret)throw Object.assign(new Error('r_keeper_credentials_required'),{status:400});return {base_url,client_id,client_secret,object_id};}
async function http(url,o={}){const r=await fetch(url,{...o,headers:{Accept:'application/json',...(o.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(_){d={raw:t}}if(!r.ok){const e=new Error((d&&(d.message||d.error||d.description))||`remote_api_${r.status}`);e.status=r.status;throw e;}return d;}
function rHeaders(c){return {Authorization:`Basic ${Buffer.from(`${c.client_id}:${c.client_secret}`).toString('base64')}`,'X-Client-Id':c.client_id,'X-Client-Secret':c.client_secret};}
function data(d,k){return d&&d.data&&d.data[k]?d.data[k]:(d&&d[k]?d[k]:[]);}
function find(nodes,id){if(!Array.isArray(nodes))return null;for(const n of nodes){if(String(n.id)===String(id))return n;const x=find(n.items,id);if(x)return x;}return null;}
function walk(nodes,out,parent){if(!Array.isArray(nodes))return;for(const n of nodes){if(!n)continue;const id=n.id,name=n.name||(n.locres&&n.locres.ru&&n.locres.ru.name);if(id&&name)out.push({id:String(id),name:String(name),parent_id:parent||null});walk(n.items,out,id||parent);}}
async function rMenu(c){if(!c.object_id)throw Object.assign(new Error('r_keeper_object_id_required'),{status:400});const base=c.base_url+'/',h=rHeaders(c);const tree=await http(`${base}menutree?objectid=${encodeURIComponent(c.object_id)}&lang=ru`,{headers:h});const dish=await http(`${base}dishes?objectid=${encodeURIComponent(c.object_id)}&lang=ru`,{headers:h});const cats=[],selectors=data(tree,'selectors');for(const s of selectors)walk(s.items||[],cats,null);const catByDish=new Map();for(const cat of cats){const n=find(selectors,cat.id);if(n&&Array.isArray(n.dishes))n.dishes.forEach(id=>catByDish.set(String(id),cat.name));}const products=data(dish,'dishes').map(p=>{const lr=p.locres&&p.locres.ru||{};return {external_id:String(p.id),name:String(lr.name||p.name||'Без названия').trim(),description:String(lr.long_comment||lr.comment||'').trim()||null,price:Number(p.price||0)/100,category:catByDish.get(String(p.id))||'main',image_url:Array.isArray(p.images)&&p.images[0]?p.images[0]:null,is_available:Number(p.active)!==0,metadata:{r_keeper:p}}}).filter(x=>x.external_id&&x.name);return {products,categories:cats,raw:{tree,dishes:dish}};}
async function quickMenu(c){const auth='Basic '+Buffer.from(`${c.login}:${c.password}`).toString('base64'),paths=(process.env.QUICK_RESTO_MENU_PATHS||'/api/menu,/api/dishes,/menu,/dishes').split(',').map(x=>x.trim()).filter(Boolean);let last=null;for(const path of paths){try{const d=await http(c.base_url+(path.startsWith('/')?'':'/')+path,{headers:{Authorization:auth}});const a=Array.isArray(d)?d:(d&&Array.isArray(d.dishes)?d.dishes:(d&&Array.isArray(d.products)?d.products:(d&&d.data&&Array.isArray(d.data.dishes)?d.data.dishes:(d&&d.data&&Array.isArray(d.data.products)?d.data.products:[]))));if(a.length)return {products:a.map(p=>({external_id:String(p.id||p.guid||p.productId),name:String(p.name||p.title||p.productName||'Без названия').trim(),description:String(p.description||p.comment||'').trim()||null,price:Number(p.price||p.defaultPrice||0)/100,category:String(p.categoryName||p.category||p.groupName||'main'),image_url:p.imageUrl||p.image_url||(Array.isArray(p.images)?p.images[0]:null)||null,is_available:p.active!==false&&p.deleted!==true,metadata:{quick_resto:p}})).filter(x=>x.external_id&&x.name),categories:[],raw:d};}catch(e){last=e;}}throw Object.assign(new Error(last&&last.message||'quick_resto_menu_endpoint_not_found'),{status:last&&last.status||502});}
async function load(p,c){return p==='r_keeper'?rMenu(c):quickMenu(c);}
async function sync(v,p,m,mode){const maps=await sb(`/rest/v1/integration_item_mappings?venue_id=eq.${encodeURIComponent(v)}&provider=eq.${p}&entity_type=eq.product&select=id,external_id,local_id`),by=new Map((maps||[]).map(x=>[String(x.external_id),x]));const r={received:m.products.length,created:0,updated:0,unchanged:0,skipped:0,error_count:0,errors:[],items:[]};if(mode==='preview'){for(const x of m.products){const e=by.get(x.external_id);e&&e.local_id?r.updated++:r.created++;r.items.push({external_id:x.external_id,name:x.name,category:x.category,price:x.price,action:e&&e.local_id?'update':'create'});}return r;}for(const x of m.products){try{let id=by.get(x.external_id)?.local_id||null;if(id){const q=await sb(`/rest/v1/products?id=eq.${encodeURIComponent(id)}&venue_id=eq.${encodeURIComponent(v)}&select=id&limit=1`);if(!q.length)id=null;}const payload={venue_id:v,name:x.name,description:x.description,price:x.price,category:x.category,image_url:x.image_url,is_available:x.is_available,applies_to:'all'};if(id){await sb(`/rest/v1/products?id=eq.${encodeURIComponent(id)}&venue_id=eq.${encodeURIComponent(v)}`,{method:'PATCH',body:JSON.stringify(payload)});r.updated++;}else{const made=await sb('/rest/v1/products',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});id=made&&made[0]&&made[0].id;if(!id)throw new Error('product_id_missing');r.created++;}await sb('/rest/v1/integration_item_mappings?on_conflict=venue_id%2Cprovider%2Centity_type%2Cexternal_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({venue_id:v,provider:p,entity_type:'product',external_id:x.external_id,local_id:id,external_name:x.name,metadata:x.metadata})});r.items.push({external_id:x.external_id,local_id:id,name:x.name});}catch(e){r.error_count++;r.skipped++;r.errors.push({external_id:x.external_id,name:x.name,error:e.message||String(e)});}}return r;}
module.exports=async function(req,res){if(req.method!=='POST')return send(res,405,{error:'method_not_allowed'});try{const u=await getManagerUser(bearer(req)),b=req.body||{},p=String(b.provider||''),v=String(b.venue_id||'');if(!SUPPORTED.includes(p))return send(res,400,{error:'unsupported_provider'});if(!v)return send(res,400,{error:'venue_id_required'});await access(u,v);const a=b.action;if(a==='connect'){const c=normalize(p,b.credentials),m=await load(p,c),old=await sb(`/rest/v1/venue_integrations?venue_id=eq.${encodeURIComponent(v)}&provider=eq.${p}&select=id&limit=1`),payload={venue_id:v,provider:p,status:'connected',credentials_encrypted:enc(c),metadata:{auth_mode:p==='r_keeper'?'delivery_api':'api_basic',...(p==='r_keeper'?{object_id:c.object_id}:{}),products_count:m.products.length},error_message:null,last_sync_at:new Date().toISOString()};if(old&&old[0])await sb(`/rest/v1/venue_integrations?id=eq.${encodeURIComponent(old[0].id)}`,{method:'PATCH',body:JSON.stringify(payload)});else await sb('/rest/v1/venue_integrations',{method:'POST',body:JSON.stringify(payload)});return send(res,200,{ok:true,provider:p,products_count:m.products.length,categories_count:(m.categories||[]).length});}const rows=await sb(`/rest/v1/venue_integrations?venue_id=eq.${encodeURIComponent(v)}&provider=eq.${p}&select=id,status,credentials_encrypted,metadata&limit=1`),i=rows&&rows[0];if(!i||!i.credentials_encrypted)return send(res,404,{error:`${p}_not_connected`});const c=dec(i.credentials_encrypted);if(a==='test'||a==='organizations'){const m=await load(p,c);return send(res,200,{ok:true,provider:p,products_count:m.products.length,objects:p==='r_keeper'?[{id:c.object_id,name:c.object_id}]:[]});}if(['nomenclature','preview_import','import_menu'].includes(a)){const m=await load(p,c);if(a==='nomenclature')return send(res,200,{ok:true,provider:p,products_count:m.products.length,categories_count:(m.categories||[]).length,nomenclature:m.raw});const result=await sync(v,p,m,a==='import_menu'?'import':'preview');return send(res,200,{ok:!result.error_count,status:result.error_count?(result.created||result.updated?'partial':'error'):'success',provider:p,...result});}return send(res,400,{error:'unknown_action'});}catch(e){return send(res,e.status||500,{error:e.message||'integration_error'});}};
