'use strict';
const crypto=require('crypto');
const {bearer,getManagerUser}=require('../_lib/manager-auth');
const SUPABASE_URL='https://ulxfsozdryqrnlxzlblt.supabase.co';
function send(res,status,body){res.status(status).setHeader('Content-Type','application/json; charset=utf-8').end(JSON.stringify(body));}
function sbh(){const k=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY;if(!k)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured');return {apikey:k,Authorization:`Bearer ${k}`,'Content-Type':'application/json'};}
async function sb(path,o={}){const r=await fetch(`${SUPABASE_URL}${path}`,{...o,headers:{...sbh(),...(o.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(_){d={raw:t}}if(!r.ok)throw Object.assign(new Error((d&&(d.message||d.error))||`Supabase ${r.status}`),{status:r.status});return d;}
function key(){const raw=process.env.INTEGRATION_ENCRYPTION_KEY;if(!raw)throw new Error('INTEGRATION_ENCRYPTION_KEY is not configured');return crypto.createHash('sha256').update(raw).digest();}
function enc(v){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv),out=Buffer.concat([c.update(JSON.stringify(v),'utf8'),c.final()]);return [iv.toString('base64url'),c.getAuthTag().toString('base64url'),out.toString('base64url')].join('.');}
function dec(v){const [iv,tag,p]=String(v||'').split('.');const d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(p,'base64url')),d.final()]).toString('utf8'));}
async function access(u,v){if(u.role==='admin')return;const r=await sb(`/rest/v1/manager_venues?manager_id=eq.${encodeURIComponent(u.id)}&venue_id=eq.${encodeURIComponent(v)}&select=id&limit=1`);if(!r.length)throw Object.assign(new Error('venue_access_required'),{status:403});}
function creds(c){c=c&&typeof c==='object'?c:{};const base_url=String(c.base_url||'https://api-eu.syrve.live').replace(/\/$/,'');const api_login=String(c.api_login||c.apiLogin||c.api_key||'').trim();const api_key=String(c.api_key||'').trim();const organization_id=String(c.organization_id||'').trim();if(!api_login)throw Object.assign(new Error('syrve_api_login_required'),{status:400});return {base_url,api_login,api_key,organization_id};}
async function remote(base,path,o={}){const r=await fetch(base+path,{...o,headers:{Accept:'application/json','Content-Type':'application/json',...(o.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(_){d={raw:t}}if(!r.ok){const e=new Error((d&&(d.message||d.error||d.description))||`syrve_api_${r.status}`);e.status=r.status;e.details=d;throw e;}return d;}
async function token(c){const d=await remote(c.base_url,'/api/1/access_token',{method:'POST',body:JSON.stringify({apiLogin:c.api_login})});if(!d||!d.token)throw new Error('syrve_token_missing');return d.token;}
function auth(t){return {Authorization:`Bearer ${t}`};}
function list(d,k){return Array.isArray(d)?d:(d&&Array.isArray(d[k])?d[k]:[]);}
async function menus(c,t){return remote(c.base_url,'/api/2/menu',{method:'POST',headers:auth(t),body:'{}'});}
async function menuById(c,t,id,org,priceCategoryId){return remote(c.base_url,'/api/2/menu/by_id',{method:'POST',headers:auth(t),body:JSON.stringify({externalMenuId:Number(id),organizationIds:org?[org]:[],priceCategoryId:priceCategoryId||null})});}
function normalize(menu,org){const products=[];for(const cat of list(menu,'itemCategories')){for(const p of list(cat,'items')){if(!p||!p.itemId||!p.name)continue;const sizes=list(p,'itemSizes');const s=sizes.find(x=>x&&x.isDefault)||sizes[0]||{};const prices=list(s,'prices');const own=prices.find(x=>!org||String(x.organizationId)===String(org))||prices[0]||{};const mods=[];for(const g of list(s,'itemModifierGroups'))for(const m of list(g,'items'))mods.push({id:m.itemId||m.id||m.sku,name:String(m.name||''),price:Number((list(m,'prices').find(x=>!org||String(x.organizationId)===String(org))||list(m,'prices')[0]||{}).price||0),min_count:Number((m.restrictions||{}).minQuantity||0),max_count:Number((m.restrictions||{}).maxQuantity||0),qty:Number((m.restrictions||{}).byDefault||0),group:String(g.name||'')});products.push({external_id:String(p.itemId),name:String(p.name),description:String(p.description||'').trim()||null,price:Number(own.price||0),category:String(cat.id||cat.name||'main'),image_url:s.buttonImageUrl||p.buttonImageUrl||null,is_available:own.price!=null,metadata:{syrve:{sku:p.sku,sizes:sizes.map(z=>({id:z.sizeId,name:z.sizeName,sku:z.sku,weight:z.portionWeightGrams,prices:z.prices||[]})),allergens:p.allergenGroups||[],tags:p.tags||[],nutrition:s.nutritionPerHundredGrams||s.nutritions||null,modifiers:mods,raw:p}});}}return {products,categories:list(menu,'itemCategories').map(c=>({id:String(c.id||c.name),name:String(c.name||'')})),raw:menu};}
async function persist(v,c,status,meta){const rows=await sb(`/rest/v1/venue_integrations?venue_id=eq.${encodeURIComponent(v)}&provider=syrve&select=id&limit=1`);const payload={venue_id:v,provider:'syrve',status,credentials_encrypted:enc(c),error_message:null,metadata:meta||{}};if(rows&&rows[0])await sb(`/rest/v1/venue_integrations?id=eq.${encodeURIComponent(rows[0].id)}`,{method:'PATCH',body:JSON.stringify(payload)});else await sb('/rest/v1/venue_integrations',{method:'POST',body:JSON.stringify(payload)});}
async function importProducts(v,n){const maps=await sb(`/rest/v1/integration_item_mappings?venue_id=eq.${encodeURIComponent(v)}&provider=syrve&entity_type=eq.product&select=id,external_id,local_id`);const by=new Map((maps||[]).map(x=>[String(x.external_id),x]));let created=0,updated=0,unchanged=0,error_count=0;for(const x of n.products){try{const m=by.get(x.external_id),payload={venue_id:v,name:x.name,description:x.description,price:x.price,category:x.category,image_url:x.image_url,is_available:x.is_available,applies_to:'all'};if(m&&m.local_id){const old=(await sb(`/rest/v1/products?id=eq.${encodeURIComponent(m.local_id)}&venue_id=eq.${encodeURIComponent(v)}&select=name,description,price,category,image_url,is_available&limit=1`))[0];if(old&&JSON.stringify({...old,price:Number(old.price)})===JSON.stringify({...payload,price:Number(payload.price)}))unchanged++;else{await sb(`/rest/v1/products?id=eq.${encodeURIComponent(m.local_id)}&venue_id=eq.${encodeURIComponent(v)}`,{method:'PATCH',body:JSON.stringify(payload)});updated++;}await sb(`/rest/v1/integration_item_mappings?id=eq.${encodeURIComponent(m.id)}`,{method:'PATCH',body:JSON.stringify({external_name:x.name,metadata:x.metadata,last_seen_at:new Date().toISOString(),last_synced_at:new Date().toISOString(),external_status:x.is_available?'active':'inactive',updated_at:new Date().toISOString()})});}else{const made=await sb('/rest/v1/products',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});const id=made&&made[0]&&made[0].id;if(!id)throw new Error('product_id_missing');await sb('/rest/v1/integration_item_mappings?on_conflict=venue_id%2Cprovider%2Centity_type%2Cexternal_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({venue_id:v,provider:'syrve',entity_type:'product',external_id:x.external_id,local_id:id,external_name:x.name,metadata:x.metadata,last_seen_at:new Date().toISOString(),last_synced_at:new Date().toISOString(),external_status:x.is_available?'active':'inactive'})});created++;}}catch(_){error_count++;}}return {received:n.products.length,created,updated,unchanged,error_count,skipped:error_count};}
module.exports=async function(req,res){if(req.method!=='POST')return send(res,405,{error:'method_not_allowed'});try{const u=await getManagerUser(bearer(req)),b=req.body||{},v=String(b.venue_id||''),a=String(b.action||'');if(!v)return send(res,400,{error:'venue_id_required'});await access(u,v);let c=b.credentials&&typeof b.credentials==='object'?creds(b.credentials):null;if(!c){const row=(await sb(`/rest/v1/venue_integrations?venue_id=eq.${encodeURIComponent(v)}&provider=syrve&select=credentials_encrypted&limit=1`))[0];if(!row)throw Object.assign(new Error('integration_not_configured'),{status:400});c=dec(row.credentials_encrypted);}const t=await token(c);if(a==='connect'||a==='test'){const m=await menus(c,t);await persist(v,c,'connected',{menu_count:list(m,'externalMenus').length,price_categories:list(m,'priceCategories').length});return send(res,200,{ok:true,status:'connected',menus:list(m,'externalMenus'),price_categories:list(m,'priceCategories'),token_verified:true});}const m=await menus(c,t);if(a==='menus')return send(res,200,{ok:true,menus:list(m,'externalMenus'),price_categories:list(m,'priceCategories')});const menuId=b.menu_id||((list(m,'externalMenus')[0]||{}).id);if(!menuId)throw new Error('syrve_external_menu_required');const menu=await menuById(c,t,menuId,c.organization_id,b.price_category_id);if(a==='nomenclature'||a==='preview_import')return send(res,200,{ok:true,menu_id:menuId,received:normalize(menu,c.organization_id).products.length,products:normalize(menu,c.organization_id).products.slice(0,200),categories:normalize(menu,c.organization_id).categories});if(a==='import_menu'){const n=normalize(menu,c.organization_id),r=await importProducts(v,n);await persist(v,c,r.error_count?'error':'connected',{menu_id:menuId,organization_id:c.organization_id,products_count:n.products.length,sync_created:r.created,sync_updated:r.updated,sync_unchanged:r.unchanged,sync_errors:r.error_count,last_sync_at:new Date().toISOString()});return send(res,200,{ok:true,status:r.error_count?'partial':'connected',menu_id:menuId,...r});}throw Object.assign(new Error('unknown_action'),{status:400});}catch(e){return send(res,e.status||502,{error:e.message||'syrve_integration_error',details:e.details||null});}};
