'use strict';
const {bearer,getManagerUser}=require('../_lib/manager-auth');
const {PROVIDERS}=require('./registry');
const SUPPORTED={iiko:'./iiko',r_keeper:'./pos',quick_resto:'./pos',saby_presto:'./saby-presto',poster:'./poster',syrve:'./syrve',evotor:'./evotor',frontpad:'./frontpad'};
const SUPABASE_URL='https://ulxfsozdryqrnlxzlblt.supabase.co';
function send(res,status,body){res.status(status).setHeader('Content-Type','application/json; charset=utf-8').end(JSON.stringify(body));}
function serviceHeaders(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY;if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured');return {apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};}
async function sb(path,options={}){const r=await fetch(`${SUPABASE_URL}${path}`,{...options,headers:{...serviceHeaders(),...(options.headers||{})}});const text=await r.text();let data={};try{data=text?JSON.parse(text):{};}catch(_){data={};}if(!r.ok)throw Object.assign(new Error((data&&(data.message||data.error))||`Supabase ${r.status}`),{status:r.status});return data;}
function diagnostic(status,error){const code=error&&error.error_code||'';const e=String(error&&error.error||'').toLowerCase();if(status===401||status===403||/auth|token|credential|login|password|secret|api.?key/.test(e)||/auth/.test(code.toLowerCase()))return {error_code:'AUTH_FAILED',message:'Не удалось авторизоваться. Проверьте API-ключ, логин, пароль или токен.'};if(status===404||/not.?found|endpoint|url/.test(e))return {error_code:'ENDPOINT_NOT_FOUND',message:'Сервис доступен, но указанный API-адрес или объект не найден.'};if(status===408||status===504||/timeout|timed.?out/.test(e))return {error_code:'TIMEOUT',message:'Сервис не ответил вовремя. Проверьте доступность API и сеть.'};if(status===429||/rate.?limit|too many/.test(e))return {error_code:'RATE_LIMIT',message:'Сервис временно ограничил частоту запросов. Повторите проверку позже.'};if(status>=500||status===502||status===503)return {error_code:'REMOTE_SERVICE_ERROR',message:'Удалённый сервис интеграции временно недоступен.'};if(e)return {error_code:code||'INTEGRATION_ERROR',message:String(error.error||error.message||'Ошибка проверки интеграции').slice(0,240)};return {error_code:'UNKNOWN',message:'Не удалось подтвердить соединение.'};}
async function saveDiagnostic(venue_id,provider,diagnosticData,ok){const rows=await sb(`/rest/v1/venue_integrations?venue_id=eq.${encodeURIComponent(venue_id)}&provider=eq.${encodeURIComponent(provider)}&select=id,metadata&limit=1`);if(!rows||!rows[0])return;const metadata=rows[0].metadata&&typeof rows[0].metadata==='object'?rows[0].metadata:{};const patch={metadata:{...metadata,last_test:diagnosticData},status:ok?'connected':'error',error_message:ok?null:diagnosticData.message};await sb(`/rest/v1/venue_integrations?id=eq.${encodeURIComponent(rows[0].id)}`,{method:'PATCH',body:JSON.stringify(patch)});}
module.exports=async function(req,res){if(req.method!=='POST')return send(res,405,{error:'method_not_allowed'});let provider='',venue_id='';const checked_at=new Date().toISOString();try{const user=await getManagerUser(bearer(req));const b=req.body||{};provider=String(b.provider||'').trim();venue_id=String(b.venue_id||'').trim();if(!provider||!PROVIDERS[provider])return send(res,400,{error:'unsupported_provider'});if(!venue_id)return send(res,400,{error:'venue_id_required'});if(!PROVIDERS[provider].implemented||!SUPPORTED[provider])return send(res,409,{error:'integration_adapter_not_implemented',provider});const adapter=require(SUPPORTED[provider]);const body={action:'test',provider,venue_id};let result=null;const started=Date.now();const proxy={status(code){this._status=code;return this;},setHeader(){return this;},end(text){try{result=text?JSON.parse(text):{};}catch(_){result={error:'invalid_adapter_response'};}}};let thrown=null;try{await adapter({method:'POST',headers:req.headers,body},proxy);}catch(e){thrown=e;}const status=proxy._status||(thrown&&thrown.status)||502;const latency_ms=Date.now()-started;const verified=status>=200&&status<300&&!thrown&&(!result||result.ok!==false);const safe=verified?{error_code:'OK',message:'Соединение успешно проверено.'}:diagnostic(status,result||thrown||{});const diag={checked_at,verified,http_status:status,latency_ms,error_code:safe.error_code,message:safe.message};try{await saveDiagnostic(venue_id,provider,diag,verified);}catch(_){/* diagnostics must never hide the provider result */}return send(res,verified?200:status,{ok:verified,provider,verified,checked_at,http_status:status,latency_ms,diagnostic:{error_code:safe.error_code,message:safe.message},received:result&&result.received!=null?result.received:undefined,checked_by:user.id});}catch(e){const status=e.status||502;const diag=diagnostic(status,e);try{if(provider&&venue_id)await saveDiagnostic(venue_id,provider,{checked_at,verified:false,http_status:status,latency_ms:null,error_code:diag.error_code,message:diag.message},false);}catch(_){}return send(res,status,{ok:false,provider,verified:false,checked_at,http_status:status,latency_ms:null,diagnostic:diag,error:e.message||'integration_test_error'});}};
