'use strict';

const pos=require('../integrations/pos');
const {PROVIDERS}=require('../integrations/registry');
const {claim,release}=require('../integrations/sync-lock');
const SUPABASE_URL='https://ulxfsozdryqrnlxzlblt.supabase.co';
const HANDLERS={
  iiko:require('../integrations/iiko'),
  saby_presto:require('../integrations/saby-presto'),
  poster:require('../integrations/poster'),
  syrve:require('../integrations/syrve'),
  evotor:require('../integrations/evotor'),
  frontpad:require('../integrations/frontpad')
};
const POS_AUTO_SYNC=new Set(['quick_resto','r_keeper']);
const IMPLEMENTED=Object.keys(PROVIDERS).filter(id=>PROVIDERS[id].implemented);
function headers(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY;if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured');return {apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};}
async function sb(path){const r=await fetch(`${SUPABASE_URL}${path}`,{headers:headers()});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null;}catch(_){d={raw:t};}if(!r.ok)throw new Error((d&&(d.message||d.error))||`Supabase ${r.status}`);return d;}
function invokeInternal(handler,venueId,provider,secret){return new Promise((resolve,reject)=>{let statusCode=200,settled=false;const finish=body=>{if(settled)return;settled=true;let payload=body;if(typeof body==='string'){try{payload=body?JSON.parse(body):{};}catch(_){payload={ok:false,error:body};}}resolve({http_status:statusCode,body:payload&&typeof payload==='object'?payload:{}});};const res={status(code){statusCode=Number(code)||200;return res;},setHeader(){return res;},end(body){finish(body);},json(body){finish(JSON.stringify(body));}};const req={method:'POST',headers:{authorization:`Bearer ${secret}`,'x-qr-cron-secret':secret},body:{action:'import_menu',provider,venue_id:venueId}};Promise.resolve(handler(req,res)).catch(err=>{if(!settled){settled=true;reject(err);}});});}
async function syncOne(row,secret){const venue_id=String(row.venue_id),provider=String(row.provider),started=Date.now();let lock=null;try{lock=await claim(venue_id,provider,900);if(!lock.locked)return {venue_id,provider,ok:false,error:'integration_sync_in_progress',duration_ms:Date.now()-started};if(POS_AUTO_SYNC.has(provider)){const result=await pos.autoSync(venue_id,provider);return {venue_id,provider,ok:!result.error_count,received:result.received||0,created:result.created||0,updated:result.updated||0,unchanged:result.unchanged||0,errors:result.error_count||0,duration_ms:Date.now()-started};}const handler=HANDLERS[provider];if(!handler)throw new Error('integration_adapter_not_registered');const response=await invokeInternal(handler,venue_id,provider,secret);const d=response.body||{};const failed=response.http_status>=400||d.ok===false||(d.status==='partial'&&Number(d.error_count||d.errors||0)>0);return {venue_id,provider,ok:!failed,http_status:response.http_status,received:Number(d.received||0),created:Number(d.created||0),updated:Number(d.updated||0),unchanged:Number(d.unchanged||0),errors:Number(d.error_count||0),error:failed?(d.error||d.message||null):null,duration_ms:Date.now()-started};}catch(e){return {venue_id,provider,ok:false,error:e.message||String(e),duration_ms:Date.now()-started};}finally{if(lock?.locked)await release(venue_id,provider,lock.token);}}
module.exports=async function(req,res){if(req.method!=='GET'&&req.method!=='POST')return res.status(405).json({error:'method_not_allowed'});const secret=process.env.CRON_SECRET;if(!secret)return res.status(503).json({error:'cron_secret_not_configured'});if(String(req.headers.authorization||'')!==`Bearer ${secret}`)return res.status(401).json({error:'unauthorized'});try{const providers=IMPLEMENTED.join(','),rows=await sb(`/rest/v1/venue_integrations?status=eq.connected&provider=in.(${providers})&select=venue_id,provider&order=venue_id.asc,provider.asc`),results=[],batchSize=3;for(let i=0;i<(rows||[]).length;i+=batchSize){const batch=(rows||[]).slice(i,i+batchSize),settled=await Promise.all(batch.map(row=>syncOne(row,secret)));results.push(...settled);}const failed=results.filter(x=>!x.ok).length;return res.status(failed?207:200).json({ok:failed===0,count:results.length,failed,providers:IMPLEMENTED,results});}catch(e){return res.status(500).json({ok:false,error:e.message||'integration_sync_error'});}};
