'use strict';

/* Qrchick admin gateway. The existing admin AI agent remains the single intelligence layer. */
/* Admin AI is intentionally isolated from every other provider key. */
process.env.GEMINI_API_KEY = '';
const crypto = require('crypto');
const agent = require('./agent');
const SUPABASE_URL = process.env.SUPABASE_URL || 'https://ulxfsozdryqrnlxzlblt.supabase.co';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || '';
const SUPABASE_MGMT = process.env.SUPABASE_MANAGEMENT_API_TOKEN || process.env.SUPABASE_ACCESS_TOKEN || '';
const SUPABASE_REF = process.env.SUPABASE_PROJECT_REF || 'ulxfsozdryqrnlxzlblt';
const GITHUB_TOKEN = process.env.GITHUB_TOKEN || '';
const GITHUB_REPO = 'sorokoladov7-gif/qr-menu';
const GITHUB_BRANCH = 'main';
const APPROVAL_TTL_MS = 5 * 60 * 1000;
const APPROVAL_SECRET = process.env.QRCHICK_APPROVAL_SECRET || process.env.ADMIN_AI_APPROVAL_SECRET || process.env.ADMIN_AI_KEY || '';

const QRCHICK_INSTRUCTIONS = `
Ты — Qrchick, встроенный интеллектуальный ассистент проекта и операционной системы пользователя.
Твоя главная задача — быть техническим вторым пилотом по всему проекту: помогать разрабатывать, анализировать, исправлять, улучшать и защищать проект.
Всегда упоминай себя только как Qrchick. Не упоминай другие ИИ, ассистенты, модели, бренды или внешние решения, если пользователь явно не требует техническую информацию о стороннем решении. Если спрашивают, кто ты или на чём работаешь, отвечай: «Я — Qrchick, встроенный ассистент проекта».

РЕЖИМ: «Инженер-отладчик».
Стиль: кратко, технически точно, по делу. Сначала вывод: что найдено, исправлено или нужно сделать. Затем причины, код, патчи, риски и проверка. Не выдумывай факты. Если данных недостаточно — задай только один самый важный вопрос в начале.

ОБЛАСТЬ: архитектура ОС и приложений; ядро, драйверы, системные вызовы, прерывания, память, процессы; загрузчик, файловые системы, сервисы, конфигурации; C/C++/Rust/Python/Bash/Assembly и языки проекта; сборка, линковка, зависимости; логи, дампы, стектрейсы; безопасность, права, изоляция; производительность и профилирование; тесты и отладка; документация и релизы; UI/UX; аппаратная диагностика при наличии схем, даташитов и измерений.

РАБОЧИЙ ПРОЦЕСС: сначала исследуй реальные данные проекта; затем установи корневую причину; затем предложи минимальное безопасное исправление; затем проверь его. При неочевидной ошибке дай 2–3 гипотезы по вероятности и способ проверки каждой. При конфликтах указывай место, причину, последствия, минимальный патч и проверку. При кодовых изменениях предпочитай существующие рабочие файлы и не создавай дубли. Изменения должны быть готовыми к применению, без заглушек.

ДЕЙСТВИЯ: Qrchick — не консультант-заглушка. Если у него есть соответствующий инструмент, он должен реально читать проект, искать код, анализировать БД и окружение, выполнять разрешённые проверки и готовить реальные изменения. Для изменений кода или данных сначала сформируй точный план и запроси подтверждение, если действие потенциально разрушительное или затрагивает production. После подтверждения изменения должны реально выполняться доступным инструментом и затем проверяться.

БИЗНЕС-ОПЕРАЦИИ МЕНЮ: когда пользователь просит изменить рабочее меню (например, «добавь блюдо», «измени цену», «сделай недоступным»), это не консультация. Сначала через реальные Supabase tools определи целевое заведение и проверь схему public.products. Не придумывай venue_id, product_id или category. Для создания блюда используй database_changes с точным INSERT в существующую public.products, включая минимум venue_id,name,description,price,category,is_available,applies_to при наличии этих колонок. Для изменения используй UPDATE с условием по id или однозначно определённому продукту. Для удаления предпочитай безопасное скрытие is_available=false, если пользователь явно не просит физическое удаление. После мутации включай RETURNING id,name,price,category,is_available и сообщай фактический результат. Не утверждай, что операция выполнена, пока сервер не вернул успешный результат.

БЕЗОПАСНОСТЬ: не выполняй деструктивные операции без явного подтверждения; перед опасными действиями учитывай откат/резервную копию; явно отмечай риск потери данных, поломки системы, уязвимости или нестабильности.

ФОРМАТ: каждый технический ответ начинай с краткого итога. Используй маркированные списки, таблицы, код с языком, точные патчи и чек-листы. Для сложного ответа в конце: 1) что применить; 2) что пересобрать; 3) что проверить; 4) какие риски проконтролировать. Если обнаружены незапрошенные проблемы — раздел «Дополнительные риски».

КОМАНДЫ НА РУССКОМ: /исправить — исправить ошибку; /ревью — проверить код; /баг — разобрать баг; /конфликт — найти конфликты; /архитектура — улучшить архитектуру; /тест — создать тесты; /безопасность — проверить безопасность; /производительность — оптимизировать; /документация — обновить документацию; /объяснить — объяснить фрагмент; /сборка — помочь со сборкой; /лог — разобрать лог; /релиз — подготовить релиз.

КОНТЕКСТ: учитывай текущий открытый модуль, файл и задачу, если они переданы клиентом. Сохраняй историю и принятые архитектурные решения между сообщениями. Никогда не отвечай пустой заглушкой вроде «анализ завершён», если можешь дать содержательный результат.
`;

function bearer(req) { const h = String(req.headers?.authorization || req.headers?.Authorization || ''); const m = h.match(/^Bearer\s+(.+)$/i); return m ? m[1].trim() : ''; }
async function requireAdmin(req) { const token = bearer(req); if (!token) throw Object.assign(new Error('AUTH_REQUIRED'), {status:401}); const r = await fetch(SUPABASE_URL + '/auth/v1/user', {headers:{apikey:SUPABASE_ANON_KEY,authorization:'Bearer '+token}}); const user = await r.json().catch(()=>null); if (!r.ok || !user?.id) throw Object.assign(new Error('AUTH_INVALID'), {status:401}); const p = await fetch(SUPABASE_URL + '/rest/v1/profiles?id=eq.' + encodeURIComponent(user.id) + '&select=role&limit=1', {headers:{apikey:SUPABASE_ANON_KEY,authorization:'Bearer '+token}}); const rows = await p.json().catch(()=>[]); if (!p.ok || String(rows?.[0]?.role||'').toLowerCase() !== 'admin') throw Object.assign(new Error('ADMIN_ONLY'), {status:403}); return user; }
function normalizeSql(sql) { return String(sql||'').trim().replace(/^```sql\s*/i,'').replace(/```$/i,'').trim(); }
function validateSql(sql) { const q=normalizeSql(sql); if(!q||q.length>100000) throw Object.assign(new Error('INVALID_SQL'),{status:400}); const low=q.toLowerCase().replace(/\/\*[\s\S]*?\*\//g,' ').replace(/--[^\n]*/g,' '); if(/\b(create|alter|drop)\s+(role|user|policy)\b/i.test(low)) throw Object.assign(new Error('SECURITY_SENSITIVE_SQL_BLOCKED'),{status:403}); if(/\b(grant|revoke)\b/i.test(low)) throw Object.assign(new Error('PRIVILEGE_SQL_BLOCKED'),{status:403}); if(/\b(pg_read_file|pg_write_file|copy\s+.*program)\b/i.test(low)) throw Object.assign(new Error('SERVER_FILE_SQL_BLOCKED'),{status:403}); if(/\btruncate\b/i.test(low)) throw Object.assign(new Error('TRUNCATE_REQUIRES_EXPLICIT_MIGRATION'),{status:403}); return q; }
function stable(v) { if (Array.isArray(v)) return v.map(stable); if (v && typeof v === 'object') return Object.keys(v).sort().reduce((o,k)=>{o[k]=stable(v[k]);return o;},{}); return v; }
function digest(action,userId,changes) { return crypto.createHash('sha256').update(JSON.stringify(stable({action,userId,changes}))).digest('hex'); }
function signApproval(payload) { if (!APPROVAL_SECRET) throw Object.assign(new Error('QRCHICK_APPROVAL_SECRET_NOT_CONFIGURED'),{status:503}); const body=Buffer.from(JSON.stringify(payload)).toString('base64url'); const sig=crypto.createHmac('sha256',APPROVAL_SECRET).update(body).digest('base64url'); return body+'.'+sig; }
function issueApproval(action,userId,changes) { const exp=Date.now()+APPROVAL_TTL_MS; return {token:signApproval({v:1,action,sub:userId,exp,hash:digest(action,userId,changes)}),expires_at:new Date(exp).toISOString()}; }
function verifyApproval(token,action,userId,changes) { if (!APPROVAL_SECRET || !token) throw Object.assign(new Error('APPROVAL_REQUIRED'),{status:403}); const p=String(token).split('.'); if(p.length!==2) throw Object.assign(new Error('INVALID_APPROVAL'),{status:403}); const expected=crypto.createHmac('sha256',APPROVAL_SECRET).update(p[0]).digest('base64url'); if(p[1].length!==expected.length || !crypto.timingSafeEqual(Buffer.from(p[1]),Buffer.from(expected))) throw Object.assign(new Error('INVALID_APPROVAL'),{status:403}); let payload; try{payload=JSON.parse(Buffer.from(p[0],'base64url').toString('utf8'));}catch(_){throw Object.assign(new Error('INVALID_APPROVAL'),{status:403});} if(payload.v!==1||payload.action!==action||payload.sub!==userId||Number(payload.exp||0)<Date.now()||payload.hash!==digest(action,userId,changes)) throw Object.assign(new Error('APPROVAL_EXPIRED_OR_MISMATCHED'),{status:403}); return payload; }
function validateCodeChanges(changes) { if(!Array.isArray(changes)||!changes.length||changes.length>20) throw Object.assign(new Error('INVALID_CHANGE_SET'),{status:400}); return changes.map((item,i)=>{const x=item||{};const op=String(x.operation||'update').toLowerCase();const file=String(x.file||'');const sha=String(x.expected_sha||'');const content=String(x.new_content==null?'':x.new_content);if(op!=='update')throw Object.assign(new Error('UNSUPPORTED_CODE_OPERATION_'+i),{status:403});if(!/^[A-Za-z0-9._\-/]+$/.test(file)||file.includes('..')||file.startsWith('/'))throw Object.assign(new Error('INVALID_CODE_PATH_'+i),{status:400});if(!/^[0-9a-f]{40}$/i.test(sha))throw Object.assign(new Error('EXPECTED_SHA_REQUIRED_'+i),{status:400});if(content.length>500000)throw Object.assign(new Error('CODE_CHANGE_TOO_LARGE_'+i),{status:400});return {operation:'update',file,expected_sha:sha,reason:String(x.reason||'').slice(0,1000),new_content:content};}); }
function ghHeaders() { if(!GITHUB_TOKEN) throw Object.assign(new Error('GITHUB_TOKEN_NOT_CONFIGURED'),{status:503}); return {Authorization:'Bearer '+GITHUB_TOKEN,'Accept':'application/vnd.github+json','User-Agent':'QR-Menu-Qrchick','Content-Type':'application/json'}; }
async function gh(path,opts) { const r=await fetch('https://api.github.com/repos/'+GITHUB_REPO+path,Object.assign({headers:ghHeaders()},opts||{})); const d=await r.json().catch(()=>null); if(!r.ok) throw Object.assign(new Error(d?.message||'GITHUB_HTTP_'+r.status),{status:r.status}); return d; }
async function executeCodeChanges(changes,user) { const items=validateCodeChanges(changes); const head=await gh('/git/ref/heads/'+GITHUB_BRANCH); const parentSha=head?.object?.sha; if(!parentSha) throw Object.assign(new Error('GITHUB_BRANCH_NOT_FOUND'),{status:404}); for(const item of items){const f=await gh('/contents/'+item.file+'?ref='+encodeURIComponent(GITHUB_BRANCH));if(String(f?.sha||'')!==item.expected_sha)throw Object.assign(new Error('STALE_CODE_CHANGE:'+item.file),{status:409});} const blobs=[]; for(const item of items) blobs.push(await gh('/git/blobs',{method:'POST',body:JSON.stringify({content:item.new_content,encoding:'utf-8'})})); const baseCommit=await gh('/git/commits/'+encodeURIComponent(parentSha)); const tree=await gh('/git/trees',{method:'POST',body:JSON.stringify({base_tree:baseCommit.tree.sha,tree:items.map((item,i)=>({path:item.file,mode:'100644',type:'blob',sha:blobs[i].sha}))})}); const commit=await gh('/git/commits',{method:'POST',body:JSON.stringify({message:'feat(qrchick): apply approved admin changes',tree:tree.sha,parents:[parentSha],author:{name:'Qrchick',email:'qrchick@qr-menu-russia.ru'}})}); const updated=await fetch('https://api.github.com/repos/'+GITHUB_REPO+'/git/refs/heads/'+GITHUB_BRANCH,{method:'PATCH',headers:ghHeaders(),body:JSON.stringify({sha:commit.sha,force:false})}); const updatedData=await updated.json().catch(()=>null); if(!updated.ok)throw Object.assign(new Error(updatedData?.message||'GITHUB_REF_UPDATE_FAILED'),{status:updated.status}); return {commit_sha:commit.sha,branch:GITHUB_BRANCH,files:items.map(x=>x.file),author:user.email||user.id}; }
async function executeDatabaseChanges(changes) { if(!SUPABASE_MGMT) throw Object.assign(new Error('SUPABASE_MANAGEMENT_API_TOKEN_NOT_CONFIGURED'),{status:503}); if(!Array.isArray(changes)||!changes.length||changes.length>20) throw Object.assign(new Error('INVALID_CHANGE_SET'),{status:400}); const results=[]; for(let i=0;i<changes.length;i++){const item=changes[i]||{};const sql=validateSql(item.sql);const r=await fetch('https://api.supabase.com/v1/projects/'+encodeURIComponent(SUPABASE_REF)+'/database/query',{method:'POST',headers:{Authorization:'Bearer '+SUPABASE_MGMT,'Content-Type':'application/json'},body:JSON.stringify({query:sql})});const data=await r.json().catch(()=>({}));if(!r.ok) throw Object.assign(new Error(data?.message||data?.error||('SUPABASE_QUERY_FAILED_'+r.status)),{status:r.status});results.push({index:i,sql,reason:String(item.reason||''),risk:String(item.risk||''),result:data});} return results; }
module.exports = async function handler(req,res){ if(req.method!=='POST') return res.status(405).json({error:'method_not_allowed'}); try { const body=req.body||{}; const action=String(body.action||'audit'); if(['prepare_code','prepare_db','apply','apply_db'].includes(action)){const user=await requireAdmin(req); if(action==='prepare_code'){const changes=validateCodeChanges(body.changes);const approval=issueApproval('code',user.id,changes);return res.status(200).json({ok:true,kind:'code',changes:changes.map(x=>({file:x.file,operation:x.operation,reason:x.reason})),approval_token:approval.token,expires_at:approval.expires_at});} if(action==='prepare_db'){if(!Array.isArray(body.database_changes)||!body.database_changes.length)throw Object.assign(new Error('INVALID_CHANGE_SET'),{status:400});const changes=body.database_changes.map(x=>({sql:validateSql(x?.sql),reason:String(x?.reason||'').slice(0,1000),risk:String(x?.risk||'').slice(0,500)}));const approval=issueApproval('db',user.id,changes);return res.status(200).json({ok:true,kind:'db',count:changes.length,approval_token:approval.token,expires_at:approval.expires_at});} if(action==='apply'){const changes=validateCodeChanges(body.changes);verifyApproval(body.approval_token,'code',user.id,changes);const result=await executeCodeChanges(changes,user);return res.status(200).json({ok:true,changes:result});} if(action==='apply_db'){const raw=body.database_changes;if(!Array.isArray(raw)||!raw.length)throw Object.assign(new Error('INVALID_CHANGE_SET'),{status:400});const normalized=raw.map(x=>({sql:validateSql(x?.sql),reason:String(x?.reason||'').slice(0,1000),risk:String(x?.risk||'').slice(0,500)}));verifyApproval(body.approval_token,'db',user.id,normalized);const result=await executeDatabaseChanges(normalized);return res.status(200).json({ok:true,changes:result});}} const enriched=Object.assign({},body,{message:QRCHICK_INSTRUCTIONS+'\n\nПОЛЬЗОВАТЕЛЬСКИЙ ЗАПРОС:\n'+String(body.message||''),mode:'debugger'}); req.body=enriched; return agent(req,res); } catch(e) { return res.status(Number(e.status)||500).json({error:e.message||'Qrchick execution error'}); } };
