/* QR Menu — manager AI control center. Ten tariff-gated AI functions. */
(function(){
  'use strict';
  if(window.__QR_MANAGER_AI_CENTER__)return;
  window.__QR_MANAGER_AI_CENTER__=true;
  var FEATURES=[
    ['assistant','ИИ-помощник','Общие вопросы, навигация и возможности платформы.'],
    ['menu_analysis','Анализ меню','Структура меню, категории, цены и рекомендации.'],
    ['menu_import','ИИ-импорт меню','Запуск существующего AI-импорта меню.'],
    ['analytics','ИИ-аналитика','Продажи, заказы, эффективность и точки роста.'],
    ['recipes','ИИ-рецептуры','Рецептуры, техкарты, нормы и рекомендации.'],
    ['chef','ИИ-шеф','Блюда, кухня, себестоимость и процессы.'],
    ['staff','ИИ-персонал','Персонал, роли, нагрузка и процессы.'],
    ['marketing','ИИ-маркетинг','Акции, тексты, предложения и продвижение.'],
    ['settings','ИИ-настройки','Настройки платформы и заведения.'],
    ['engineer','ИИ-инженер','Диагностика и технические рекомендации.']
  ];
  var DEFAULT_TASKS={
    assistant:'Помоги управляющему с текущей задачей и укажи точный раздел/действие в кабинете.',
    menu_analysis:'Проанализируй текущее меню: структуру, категории, названия и цены. Найди 5 проблем и дай 5 конкретных улучшений.',
    analytics:'Проанализируй текущие показатели заведения. Выдели 3 вывода, 3 риска и 5 действий для роста выручки.',
    recipes:'Проанализируй текущие рецептуры и ингредиенты. Найди проблемы с нормами, себестоимостью и полнотой техкарт.',
    chef:'Оцени меню с позиции шефа: баланс категорий, сложность кухни, заготовки, узкие места и качество процессов.',
    staff:'Проанализируй состав и нагрузку персонала. Укажи дисбалансы, риски и практические рекомендации.',
    marketing:'Предложи маркетинговый план на основе текущего меню: 3 акции, 3 оффера и 5 готовых рекламных формулировок.',
    settings:'Проведи аудит доступных настроек заведения и укажи, что стоит проверить или изменить и почему.',
    engineer:'Проведи техническую диагностику текущего кабинета по переданному контексту и перечисли вероятные проблемы и безопасные шаги проверки.'
  };
  var MODULE_TABS={menu_analysis:'menu',analytics:'analytics',recipes:'recipes',chef:'menu',staff:'staff',marketing:'menu',settings:'settings',engineer:null,assistant:null};
  var QUICK_TASKS={
    menu_analysis:['Найди самые слабые позиции меню','Проверь цены и категории','Предложи улучшение структуры меню'],
    analytics:['Найди точки роста выручки','Разбери самые продаваемые блюда','Найди проблемы по времени заказов'],
    recipes:['Найди неполные рецептуры','Проверь себестоимость блюд','Найди проблемные ингредиенты'],
    chef:['Найди узкие места кухни','Предложи блюда для усиления меню','Проверь баланс категорий'],
    staff:['Найди перегрузку персонала','Проанализируй эффективность','Предложи распределение нагрузки'],
    marketing:['Придумай акцию из текущего меню','Сделай 5 офферов','Выдели блюда для продвижения'],
    settings:['Проверь настройки доставки','Проверь основные настройки заведения','Найди потенциальные проблемы конфигурации'],
    engineer:['Проверь текущую конфигурацию кабинета','Найди вероятные технические проблемы','Составь план диагностики'],
    assistant:['Как пользоваться кабинетом?','Какие функции доступны сейчас?','Куда перейти для нужной задачи?']
  };
  function vm(){return window.__managerVue||null;}
  function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c];});}
  function allowed(v,feature){try{return !!v&&typeof v.hasAIFeature==='function'&&v.hasAIFeature(feature);}catch(e){return false;}}
  function compact(v){return Array.isArray(v)?v.slice(0,120):[];}
  function context(v,feature){
    var venue=v&&v.venue||{},products=Array.isArray(v&&v.products)?v.products:[],orders=Array.isArray(v&&v.orders)?v.orders:[],analytics=v&&v.analytics||{};
    var base={feature:feature,current_tab:v&&v.tab||null,venue:{id:venue.id||null,name:venue.name||null,address:venue.address||null},menu:{count:products.length,items:compact(products)},orders:{count:orders.length,items:orders.slice(0,80)},analytics:{period_days:v&&v.analyticsPeriod||null,revenue:analytics.revenue||0,orders:analytics.orders||0,clients:analytics.clients||0,avgCheck:analytics.avgCheck||0,avgCookTime:analytics.avgCookTime||0,newClients:analytics.newClients||0,repeatClients:analytics.repeatClients||0,topItems:compact(analytics.topItems),topAddons:compact(analytics.topAddons),topHours:compact(analytics.topHours),typeStats:analytics.typeStats||{},payStats:analytics.payStats||{},cooks:compact(analytics.cooks),couriers:compact(analytics.couriers),waiters:compact(analytics.waiters)},staff:{cooks:compact(v&&v.cooks),couriers:compact(v&&v.couriers),waiters:compact(v&&v.waiters),performance:v&&v.staffAnalytics||{}},settings:{form:v&&v.vform||{},delivery_primary:v&&v.deliveryPrimaryName||null,delivery_providers:compact(v&&v.deliveryProviderCards)},plan:{name:v&&v.currentPlan&&v.currentPlan.name||null}};
    var rs=window.__QR_MANAGER_RECIPES_STATE__;
    if(rs)base.recipes={venue_id:rs.venueId||null,products:compact(rs.products),ingredients:compact(rs.ingredients),selected_product:rs.selected||null,selected_rows:compact(rs.rows),tech_cards:compact(rs.techCards),catalog:compact(rs.catalog),catalog_items:compact(rs.catalogItems)};
    if(feature==='engineer')base.engineer={url:location.pathname,online:navigator.onLine,language:navigator.language,viewport:{width:window.innerWidth,height:window.innerHeight},user_agent:navigator.userAgent.slice(0,300),service_worker:!!navigator.serviceWorker};
    return JSON.stringify(base).slice(0,12000);
  }
  async function token(){if(!window.db||!db.auth)throw new Error('Supabase не подключен');var r=await db.auth.getSession(),t=r&&r.data&&r.data.session&&r.data.session.access_token;if(!t)throw new Error('Сессия управляющего не найдена');return t;}
  async function call(feature,message,v){if(!allowed(v,feature))throw new Error(v&&typeof v.aiFeatureError==='function'?v.aiFeatureError(feature):'Функция ИИ не включена в тариф');var t=await token();var r=await fetch('/api/manager-ai',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+t},body:JSON.stringify({feature:feature,message:String(message||'').trim().slice(0,8000),context:context(v,feature)})});var data=await r.json().catch(function(){return{};});if(!r.ok||!data.ok)throw new Error(data.error||('HTTP_'+r.status));return data;}
  function openExistingImport(){var root=document.getElementById('app');if(!root)return false;var block=root.querySelector('#qr-menu-import-block-v2');if(!block)return false;var buttons=block.querySelectorAll('button');for(var i=0;i<buttons.length;i++){var text=(buttons[i].textContent||'').toLowerCase();if(text.indexOf('импорт')!==-1||text.indexOf('анализ')!==-1){buttons[i].click();return true;}}return false;}
  function openModule(feature){var v=vm(),tab=MODULE_TABS[feature];if(!v||!tab)return false;if(typeof v.hasAIFeature==='function'&&!v.hasAIFeature(feature))return false;v.tab=tab;return true;}
  function install(){
    if(document.getElementById('qr-ai-feature-center'))return true;
    var v=vm();if(!v)return false;
    var root=document.createElement('div');root.id='qr-ai-feature-center';root.style.cssText='position:fixed;right:18px;bottom:18px;z-index:15000;font-family:inherit;';
    root.innerHTML='<button type="button" id="qr-ai-feature-fab" aria-label="ИИ для управляющего" title="Qrchick — ИИ-помощник" style="width:78px;height:78px;border-radius:50%;border:2px solid rgba(62,196,255,.78);background:radial-gradient(circle at 50% 42%,#123c78 0,#06152e 62%,#020817 100%);color:#fff;font-size:0;box-shadow:0 0 0 5px rgba(22,140,255,.08),0 0 28px rgba(24,157,255,.60),0 18px 44px rgba(7,48,105,.32);cursor:pointer;position:relative;overflow:visible;animation:qrManagerQrchickFloat 3.2s ease-in-out infinite"><span aria-hidden="true" style="display:block;width:100%;height:100%;background-image:url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ccircle cx='50' cy='50' r='31' fill='%23020916' stroke='%231aaaff' stroke-width='2'/%3E%3Cpath d='M24 38C9 15 49 5 65 18C89 12 94 45 79 57C89 79 56 95 39 78C15 85 5 53 24 38Z' fill='none' stroke='%23128fff' stroke-width='4' stroke-linecap='round'/%3E%3Cpath d='M28 69C47 50 56 27 78 31M21 47C41 64 63 71 82 51' fill='none' stroke='%235ee7ff' stroke-width='2'/%3E%3Ccircle cx='40' cy='48' r='5' fill='%23c7f7ff'/%3E%3Ccircle cx='60' cy='48' r='5' fill='%23c7f7ff'/%3E%3Cpath d='M39 63Q50 72 61 63' fill='none' stroke='%23bdf6ff' stroke-width='4' stroke-linecap='round'/%3E%3C/svg%3E\");background-size:cover;background-position:center;filter:drop-shadow(0 0 8px rgba(76,220,255,.75))"></span><i style="position:absolute;right:-1px;bottom:3px;width:14px;height:14px;border-radius:50%;background:#20d77a;border:3px solid #07172f;box-shadow:0 0 12px rgba(32,215,122,.9)"></i></button><div id="qr-ai-feature-panel" style="display:none;position:absolute;right:0;bottom:88px;width:min(430px,calc(100vw - 28px));max-height:min(700px,calc(100vh - 100px));overflow:auto;background:rgba(5,23,53,.985);border:1px solid rgba(64,181,255,.46);border-radius:18px;box-shadow:0 24px 80px rgba(1,20,52,.55),0 0 45px rgba(14,131,255,.18);padding:14px;backdrop-filter:blur(18px)"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px"><div><b style="font-size:16px;color:#fff">ИИ для управляющего</b><div style="font-size:11px;color:#a9c2e4;margin-top:3px">Доступ определяется конструктором тарифов</div></div><button type="button" id="qr-ai-feature-close" style="border:0;background:rgba(255,255,255,.07);color:#fff;font-size:20px;cursor:pointer">×</button></div><div id="qr-ai-feature-buttons" style="display:grid;grid-template-columns:1fr 1fr;gap:7px"></div><div id="qr-ai-feature-work" style="display:none;margin-top:12px;border-top:1px solid rgba(91,190,255,.15);padding-top:12px"></div></div>';
    document.body.appendChild(root);
    var style=document.createElement('style');style.id='qr-manager-qchick-style';style.textContent='@keyframes qrManagerQrchickFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-5px)}}@media(max-width:900px){#qr-ai-feature-center{right:14px!important;bottom:max(14px,env(safe-area-inset-bottom))!important}#qr-ai-feature-fab{width:66px!important;height:66px!important}#qr-ai-feature-panel{right:-4px!important;bottom:76px!important;width:calc(100vw - 20px)!important;max-height:min(760px,calc(100dvh - 100px))!important}}@media(prefers-reduced-motion:reduce){#qr-ai-feature-fab{animation:none!important}}';document.head.appendChild(style);
    var fab=root.querySelector('#qr-ai-feature-fab'),panel=root.querySelector('#qr-ai-feature-panel'),buttons=root.querySelector('#qr-ai-feature-buttons'),work=root.querySelector('#qr-ai-feature-work');
    fab.onclick=function(){panel.style.display=panel.style.display==='none'?'block':'none';refresh();};
    root.querySelector('#qr-ai-feature-close').onclick=function(){panel.style.display='none';};
    function refresh(){var cur=vm(),any=false;buttons.innerHTML='';FEATURES.forEach(function(f){var ok=allowed(cur,f[0]);if(ok)any=true;var b=document.createElement('button');b.type='button';b.setAttribute('data-ai-feature',f[0]);b.style.cssText='text-align:left;border:1px solid rgba(91,190,255,.18);border-radius:10px;padding:9px;background:rgba(22,86,145,.20);color:#e8f7ff;cursor:pointer;font-size:11px;line-height:1.25;';b.innerHTML='<b>'+esc(f[1])+'</b><br><span style="color:#a9c2e4">'+esc(f[2])+'</span>';if(!ok){b.style.opacity='.48';b.style.cursor='not-allowed';b.title=cur&&cur.aiFeatureError?cur.aiFeatureError(f[0]):'Функция не включена в тариф';}b.onclick=function(){if(!allowed(vm(),f[0])){if(vm()&&vm().showToast)vm().showToast(vm().aiFeatureError?vm().aiFeatureError(f[0]):'Функция ИИ не включена в тариф.','error');return;}if(f[0]==='menu_import'){if(!openExistingImport()&&vm()&&vm().showToast)vm().showToast('Блок ИИ-импорта меню не найден.','error');return;}openWork(f);};buttons.appendChild(b);});root.style.display=any?'block':'none';return any;}
    function openWork(f){work.style.display='block';var task=DEFAULT_TASKS[f[0]]||'';var chips=QUICK_TASKS[f[0]]||[];var nav=MODULE_TABS[f[0]?f[0]:f[0]]?'<button type="button" id="qr-ai-feature-open-module" style="border:1px solid rgba(91,190,255,.18);border-radius:9px;padding:8px 10px;background:rgba(22,86,145,.20);color:#dff5ff;cursor:pointer">Открыть раздел</button>':'';work.innerHTML='<div style="font-size:13px;font-weight:700;color:#fff;margin-bottom:7px">'+esc(f[1])+'</div><div style="font-size:11px;color:#a9c2e4;margin-bottom:9px">'+esc(f[2])+'</div><div id="qr-ai-feature-chips" style="display:flex;flex-wrap:wrap;gap:5px;margin-bottom:8px"></div><textarea id="qr-ai-feature-input" placeholder="Напишите задачу для ИИ..." style="width:100%;min-height:90px;resize:vertical;box-sizing:border-box;background:rgba(255,255,255,.055);border:1px solid rgba(86,180,255,.22);border-radius:10px;color:#f5fbff;padding:10px;font:inherit;font-size:12px;outline:none"></textarea><div style="display:flex;gap:7px;margin-top:8px"><button type="button" id="qr-ai-feature-send" style="flex:1;border:0;border-radius:10px;padding:10px;background:linear-gradient(135deg,#147cf0,#21b7ff);color:#fff;cursor:pointer;font-weight:700">Запустить ИИ</button>'+nav+'<button type="button" id="qr-ai-feature-clear" style="border:1px solid rgba(91,190,255,.18);border-radius:10px;padding:10px;background:transparent;color:#cbd5e1;cursor:pointer">Очистить</button></div><div id="qr-ai-feature-answer" style="display:none;margin-top:10px;white-space:pre-wrap;font-size:12px;line-height:1.55;background:rgba(255,255,255,.035);border-radius:10px;padding:11px;color:#eef8ff"></div>';
      var input=work.querySelector('#qr-ai-feature-input'),send=work.querySelector('#qr-ai-feature-send'),clear=work.querySelector('#qr-ai-feature-clear'),answer=work.querySelector('#qr-ai-feature-answer'),chipBox=work.querySelector('#qr-ai-feature-chips'),openBtn=work.querySelector('#qr-ai-feature-open-module');input.value=task;chips.forEach(function(text){var c=document.createElement('button');c.type='button';c.textContent=text;c.style.cssText='border:1px solid rgba(91,190,255,.16);border-radius:999px;padding:5px 8px;background:rgba(255,255,255,.03);color:#cbd5e1;cursor:pointer;font-size:10px;';c.onclick=function(){input.value=text;input.focus();};chipBox.appendChild(c);});if(openBtn)openBtn.onclick=function(){if(openModule(f[0])){panel.style.display='none';if(vm()&&vm().showToast)vm().showToast('Открыт рабочий раздел.','success');}else if(vm()&&vm().showToast)vm().showToast('Раздел недоступен или функция не включена.','error');};clear.onclick=function(){input.value='';answer.style.display='none';answer.textContent='';input.focus();};send.onclick=async function(){var message=input.value.trim();if(!message){input.focus();return;}send.disabled=true;send.textContent='ИИ работает…';answer.style.display='block';answer.textContent='Выполняю запрос…';try{var data=await call(f[0],message,vm());answer.textContent=data.answer||'ИИ не вернул ответ.';}catch(e){answer.textContent='Ошибка: '+(e.message||String(e));if(vm()&&vm().showToast)vm().showToast(e.message||'Ошибка ИИ','error');}finally{send.disabled=false;send.textContent='Запустить ИИ';}};input.focus();
    }
    return refresh();
  }
  function boot(){var tries=0,timer=setInterval(function(){tries++;if(install()||tries>80)clearInterval(timer);},250);window.addEventListener('qr-manager-vue-ready',function(){setTimeout(install,50);},{once:true});}
  boot();
})();
