'use strict';
const crypto=require('crypto');const {bearer,getManagerUser}=require('../_lib/manager-auth');const U='https://ulxfsozdryqrnlxzlblt.supabase.co';
const send=(r,s,b)=>r.status(s).setHeader('Content-Type','application/json').end(JSON.stringify(b));const key=()=>crypto.createHash('sha256').update(String(process.env.INTEGRATION_ENCRYPTION_KEY||'')).digest();
function enc(v){const i=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),i),x=Buffer.concat([c.update(JSON.stringify(v)),c.final()]);return [i.toString('base64url'),c.getAuthTag().toString('base64url'),x.toString('base64url')].join('.')}
function dec(v){const[a,b,c]=String(v||'').split('.'),d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(a,'base64url'));d.setAuthTag(Buffer.from(b,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(c,'base64url')),d.final()]).toString())}
function h(){const k=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY;if(!k)throw Error('SUPABASE_SERVICE_ROLE_KEY is not configured');return {apikey:k,Authorization:`Bearer ${k}`,'Content-Type':'application/json'}}async function sb(p,o={}){const r=await fetch(U+p,{...o,headers:{...h(),...(o.headers||{})}}),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch(_){d={}}if(!r.ok)throw Object.assign(Error(d.message||d.error||`Supabase ${r.status}`),{status:r.status});return d}
async function access(u,v){if(u.role==='admin')return;const x=await sb(`/rest/v1/manager_venues?manager_id=eq.${encodeURIComponent(u.id)}&venue_id=eq.${encodeURIComponent(v)}&select=id&limit=1`);if(!x.length)throw Object.assign(Error('venue_access_required'),{status:403})}
function creds(c){const token=String(c.token||c.access_token||'').trim(),store_id=String(c.store_id||c.storeId||'').trim();if(!token)throw Object.assign(Error('evotor_access_token_required'),{status:400});if(!store_id)throw Object.assign(Error('evotor_store_id_required'),{status:400});return {token,store_id}}
async function remote(c){let cursor='',all=[];for(let i=0;i<100;i++){const q=cursor?`?cursor=${encodeURIComponent(cursor)}`:'';const r=await fetch(`https://api.evotor.ru/api/v1/stores/${encodeURIComponent(c.store_id)}/products${q}`,{headers:{Accept:'application/vnd.evotor.v2+json',Authorization:`Bearer ${c.token}`}}),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch(_){d={}}if(!r.ok)throw Object.assign(Error(d.message||d.error||`evotor_api_${r.status}`),{status:r.status});all=all.concat(Array.isArray(d.items)?d.items:[]);cursor=d.paging&&d.paging.next_cursor;if(!cursor)break}return all}
async function persist(v,c,status,meta){const rows=await sb(`/rest/v1/venue_integrations?venue_id=eq.${encodeURIComponent(v)}&provider=eq.evotor&select=id&limit=1`),p={venue_id:v,provider:'evotor',status,credentials_encrypted:enc(c),error_message:null,metadata:meta||{}};if(rows[0])await sb(`/rest/v1/venue_integrations?id=eq.${rows[0].id}`,{method:'PATCH',body:JSON.stringify(p)});else await sb('/rest/v1/venue_integrations',{method:'POST',body:JSON.stringify(p)})}
function norm(a){const cats=new Map(),products=[];for(const x of a){if(!x||!x.id||!x.name)continue;const cat=String(x.parent_id||'main');if(cat!=='main')cats.set(cat,{id:cat,name:cat});products.push({external_id:String(x.id),name:String(x.name),description:x.description||null,price:Number(x.price||0),category:cat,image_url:null,is_available:x.allow_to_sell!==false,metadata:{evotor:x}})}return {products,categories:[...cats.values()]}}
async function imp(v,n){const maps=await sb(`/rest/v1/integration_item_mappings?venue_id=eq.${encodeURIComponent(v)}&provider=eq.evotor&entity_type=eq.product&select=id,external_id,local_id`),by=new Map((maps||[]).map(x=>[String(x.external_id),x]));let created=0,updated=0,unchanged=0,error_count=0;for(const x of n.products){try{const m=by.get(x.external_id),p={venue_id:v,name:x.name,description:x.description,price:x.price,category:x.category,image_url:x.image_url,is_available:x.is_available,applies_to:'all'};if(m&&m.local_id){const o=(await sb(`/rest/v1/products?id=eq.${encodeURIComponent(m.local_id)}&venue_id=eq.${encodeURIComponent(v)}&select=name,description,price,category,image_url,is_available&limit=1`))[0];if(o&&JSON.stringify({...o,price:Number(o.price)})===JSON.stringify({...p,price:Number(p.price)}))unchanged++;else{await sb(`/rest/v1/products?id=eq.${encodeURIComponent(m.local_id)}&venue_id=eq.${encodeURIComponent(v)}`,{method:'PATCH',body:JSON.stringify(p)});updated++}}else{const z=await sb('/rest/v1/products',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(p)}),id=z&&z[0]&&z[0].id;if(!id)throw Error('product_id_missing');await sb('/rest/v1/integration_item_mappings?on_conflict=venue_id%2Cprovider%2Centity_type%2Cexternal_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({venue_id:v,provider:'evotor',entity_type:'product',external_id:x.external_id,local_id:id,external_name:x.name,metadata:x.metadata,last_seen_at:new Date().toISOString(),last_synced_at:new Date().toISOString(),external_status:x.is_available?'active':'inactive'})});created++}}catch(_){error_count++}}return {received:n.products.length,created,updated,unchanged,error_count,skipped:error_count}}
module.exports=async function(req,res){if(req.method!=='POST')return send(res,405,{error:'method_not_allowed'});try{const u=await getManagerUser(bearer(req)),b=req.body||{},v=String(b.venue_id||'').trim(),a=String(b.action||'');await access(u,v);let c=b.credentials?creds(b.credentials):null;if(!c){const z=(await sb(`/rest/v1/venue_integrations?venue_id=eq.${encodeURIComponent(v)}&provider=eq.evotor&select=credentials_encrypted&limit=1`))[0];if(!z)throw Object.assign(Error('integration_not_configured'),{status:400});c=dec(z.credentials_encrypted)}if(a==='connect'||a==='test'){const items=await remote(c);await persist(v,c,'connected',{store_id:c.store_id,verified:true,products_count:items.length});return send(res,200,{ok:true,status:'connected',token_verified:true,received:items.length})}const n=norm(await remote(c));if(a==='nomenclature'||a==='preview_import')return send(res,200,{ok:true,received:n.products.length,products:n.products.slice(0,200),categories:n.categories});if(a==='import_menu'){const r=await imp(v,n);await persist(v,c,r.error_count?'error':'connected',{store_id:c.store_id,products_count:n.products.length,sync_created:r.created,sync_updated:r.updated,sync_unchanged:r.unchanged,sync_errors:r.error_count,last_sync_at:new Date().toISOString()});return send(res,200,{ok:true,status:r.error_count?'partial':'connected',...r})}throw Object.assign(Error('unknown_action'),{status:400})}catch(e){return send(res,e.status||502,{error:e.message||'evotor_integration_error'})}};
