'use strict';
const {bearer,getManagerUser}=require('../_lib/manager-auth');
const crypto=require('crypto');
const U='https://ulxfsozdryqrnlxzlblt.supabase.co';
const send=(r,s,b)=>r.status(s).setHeader('Content-Type','application/json').end(JSON.stringify(b));
const key=()=>crypto.createHash('sha256').update(String(process.env.INTEGRATION_ENCRYPTION_KEY||'')).digest();
function enc(v){const i=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),i),x=Buffer.concat([c.update(JSON.stringify(v)),c.final()]);return [i.toString('base64url'),c.getAuthTag().toString('base64url'),x.toString('base64url')].join('.')}
function dec(v){const[a,b,c]=String(v||'').split('.');const d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(a,'base64url'));d.setAuthTag(Buffer.from(b,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(c,'base64url')),d.final()]).toString())}
function h(){const k=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY;if(!k)throw Error('SUPABASE_SERVICE_ROLE_KEY is not configured');return {apikey:k,Authorization:`Bearer ${k}`,'Content-Type':'application/json'}}
async function sb(p,o={}){const r=await fetch(U+p,{...o,headers:{...h(),...(o.headers||{})}}),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch(_){}if(!r.ok)throw Object.assign(Error(d.message||d.error||`Supabase ${r.status}`),{status:r.status});return d}
async function access(u,v){if(u.role==='admin')return;const x=await sb(`/rest/v1/manager_venues?manager_id=eq.${encodeURIComponent(u.id)}&venue_id=eq.${encodeURIComponent(v)}&select=id&limit=1`);if(!x.length)throw Object.assign(Error('venue_access_required'),{status:403})}
function creds(c){const secret=String(c.secret||c.token||c.api_secret||'').trim();if(!secret)throw Object.assign(Error('frontpad_secret_required'),{status:400});return {secret}}
async function call(c,method){const body=new URLSearchParams();body.set('secret',c.secret);const r=await fetch(`https://app.frontpad.ru/api/index.php?${method}`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8'},body});const t=await r.text();let d={};try{d=JSON.parse(t)}catch(_){throw Object.assign(Error('frontpad_invalid_json'),{status:502})}if(d.result==='error')throw Object.assign(Error(d.error||'frontpad_api_error'),{status:502});if(!r.ok)throw Object.assign(Error(`frontpad_api_${r.status}`),{status:r.status});return d}
function arr(v){return Array.isArray(v)?v:Object.keys(v||{}).sort((a,b)=>Number(a)-Number(b)).map(k=>v[k])}
function norm(d){const ids=arr(d.product_id),names=arr(d.name),prices=arr(d.price),products=[];for(let i=0;i<ids.length;i++){if(!ids[i]||!names[i])continue;products.push({external_id:String(ids[i]),name:String(names[i]),description:null,price:Number(prices[i]||0),category:'main',image_url:null,is_available:true,metadata:{frontpad:{article:String(ids[i])}}})}return {products,categories:[]}}
async function persist(v,c,status,meta){const rows=await sb(`/rest/v1/venue_integrations?venue_id=eq.${encodeURIComponent(v)}&provider=eq.frontpad&select=id&limit=1`),p={venue_id:v,provider:'frontpad',status,credentials_encrypted:enc(c),error_message:null,metadata:meta||{}};if(rows[0])await sb(`/rest/v1/venue_integrations?id=eq.${rows[0].id}`,{method:'PATCH',body:JSON.stringify(p)});else await sb('/rest/v1/venue_integrations',{method:'POST',body:JSON.stringify(p)})}
async function imp(v,n){const maps=await sb(`/rest/v1/integration_item_mappings?venue_id=eq.${encodeURIComponent(v)}&provider=eq.frontpad&entity_type=eq.product&select=id,external_id,local_id`),by=new Map((maps||[]).map(x=>[String(x.external_id),x]));let created=0,updated=0,unchanged=0,error_count=0;for(const x of n.products){try{const m=by.get(x.external_id),p={venue_id:v,name:x.name,description:null,price:x.price,category:x.category,image_url:null,is_available:true,applies_to:'all'};if(m&&m.local_id){const o=(await sb(`/rest/v1/products?id=eq.${encodeURIComponent(m.local_id)}&venue_id=eq.${encodeURIComponent(v)}&select=name,description,price,category,image_url,is_available&limit=1`))[0];if(o&&o.name===p.name&&Number(o.price)===Number(p.price))unchanged++;else{await sb(`/rest/v1/products?id=eq.${encodeURIComponent(m.local_id)}&venue_id=eq.${encodeURIComponent(v)}`,{method:'PATCH',body:JSON.stringify(p)});updated++}}else{const z=await sb('/rest/v1/products',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(p)}),id=z&&z[0]&&z[0].id;if(!id)throw Error('product_id_missing');await sb('/rest/v1/integration_item_mappings?on_conflict=venue_id%2Cprovider%2Centity_type%2Cexternal_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({venue_id:v,provider:'frontpad',entity_type:'product',external_id:x.external_id,local_id:id,external_name:x.name,metadata:x.metadata,last_seen_at:new Date().toISOString(),last_synced_at:new Date().toISOString(),external_status:'active'})});created++}}catch(_){error_count++}}return {received:n.products.length,created,updated,unchanged,error_count,skipped:error_count}}
module.exports=async function(req,res){if(req.method!=='POST')return send(res,405,{error:'method_not_allowed'});try{const u=await getManagerUser(bearer(req)),b=req.body||{},v=String(b.venue_id||'').trim(),a=String(b.action||'');if(!v)throw Object.assign(Error('venue_id_required'),{status:400});await access(u,v);let c=b.credentials?creds(b.credentials):null;if(!c){const z=(await sb(`/rest/v1/venue_integrations?venue_id=eq.${encodeURIComponent(v)}&provider=eq.frontpad&select=credentials_encrypted&limit=1`))[0];if(!z)throw Object.assign(Error('integration_not_configured'),{status:400});c=dec(z.credentials_encrypted)}if(a==='connect'||a==='test'){const d=await call(c,'get_products');const n=norm(d);await persist(v,c,'connected',{verified:true,products_count:n.products.length});return send(res,200,{ok:true,status:'connected',token_verified:true,received:n.products.length})}const n=norm(await call(c,'get_products'));if(a==='nomenclature'||a==='preview_import')return send(res,200,{ok:true,received:n.products.length,products:n.products.slice(0,200),categories:n.categories});if(a==='import_menu'){const r=await imp(v,n);await persist(v,c,r.error_count?'error':'connected',{verified:true,products_count:n.products.length,sync_created:r.created,sync_updated:r.updated,sync_unchanged:r.unchanged,sync_errors:r.error_count,last_sync_at:new Date().toISOString()});return send(res,200,{ok:true,status:r.error_count?'partial':'connected',...r})}throw Object.assign(Error('unknown_action'),{status:400})}catch(e){return send(res,e.status||502,{error:e.message||'frontpad_integration_error'})}};
