'use strict';
const crypto=require('crypto');
const {bearer,getManagerUser}=require('../_lib/manager-auth');
const {PROVIDERS}=require('./registry');
const SUPABASE_URL='https://ulxfsozdryqrnlxzlblt.supabase.co';
const ALLOWED=Object.keys(PROVIDERS);
function send(res,status,body){res.status(status).setHeader('Content-Type','application/json; charset=utf-8').end(JSON.stringify(body));}
function headers(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY;if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured');return {apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};}
async function sb(path,options={}){const r=await fetch(`${SUPABASE_URL}${path}`,{...options,headers:{...headers(),...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch(_){data={raw:text}}if(!r.ok)throw new Error((data&&(data.message||data.error))||`Supabase ${r.status}`);return data;}
function key(){const raw=process.env.INTEGRATION_ENCRYPTION_KEY;if(!raw)throw new Error('INTEGRATION_ENCRYPTION_KEY is not configured');return crypto.createHash('sha256').update(raw).digest();}
function encrypt(v){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv),out=Buffer.concat([c.update(JSON.stringify(v),'utf8'),c.final()]);return [iv.toString('base64url'),c.getAuthTag().toString('base64url'),out.toString('base64url')].join('.');}
function decrypt(v){const [iv,tag,payload]=String(v||'').split('.');if(!iv||!tag||!payload)throw new Error('invalid_credentials');const d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(payload,'base64url')),d.final()]).toString('utf8'));}
async function access(user,venue){if(user.role==='admin')return;const rows=await sb(`/rest/v1/manager_venues?manager_id=eq.${encodeURIComponent(user.id)}&venue_id=eq.${encodeURIComponent(venue)}&select=id&limit=1`);if(!rows.length)throw Object.assign(new Error('venue_access_required'),{status:403});}
function configuredFields(credentials){return Object.keys(credentials||{}).filter(k=>credentials[k]!==undefined&&credentials[k]!==null&&String(credentials[k]).trim()!=='');}
async function existingRow(venue,provider){const rows=await sb(`/rest/v1/venue_integrations?venue_id=eq.${encodeURIComponent(venue)}&provider=eq.${encodeURIComponent(provider)}&select=id,credentials_encrypted,status,error_message,last_sync_at,metadata,created_at,updated_at&limit=1`);return rows[0]||null;}
async function oneStatus(venue,provider){const row=await existingRow(venue,provider);if(!row)return {provider,implemented:!!PROVIDERS[provider].implemented,integration:null};let fields=[];if(row.credentials_encrypted){try{fields=configuredFields(decrypt(row.credentials_encrypted));}catch(_){fields=[];}}const integration={id:row.id,provider,status:row.status,error_message:row.error_message,last_sync_at:row.last_sync_at,metadata:row.metadata||{},created_at:row.created_at,updated_at:row.updated_at,configured:fields.length>0,configured_fields:fields};return {provider,implemented:!!PROVIDERS[provider].implemented,integration};}
async function listRuns(venue,provider,limit){const query=`/rest/v1/integration_sync_runs?venue_id=eq.${encodeURIComponent(venue)}${provider?`&provider=eq.${encodeURIComponent(provider)}`:''}&select=id,venue_id,provider,status,mode,created_count,updated_count,unchanged_count,skipped_count,error_count,details,created_at,finished_at,received_count,duration_ms&order=created_at.desc&limit=${Math.min(Math.max(Number(limit)||30,1),100)}`;return sb(query);}
module.exports=async function(req,res){if(req.method!=='POST')return send(res,405,{error:'method_not_allowed'});try{const user=await getManagerUser(bearer(req));const b=req.body||{};const action=String(b.action||'').trim();const venue=String(b.venue_id||'').trim();if(!['save','status','list_status','list_runs','disconnect'].includes(action))return send(res,400,{error:'unknown_action'});if(!venue)return send(res,400,{error:'venue_id_required'});await access(user,venue);if(action==='list_status'){const requested=Array.isArray(b.providers)&&b.providers.length?b.providers.map(String):ALLOWED;const providers=requested.filter(p=>ALLOWED.includes(p));const statuses=await Promise.all(providers.map(p=>oneStatus(venue,p)));return send(res,200,{ok:true,venue_id:venue,providers:statuses,registry:providers.map(p=>({id:p,name:PROVIDERS[p].name,category:PROVIDERS[p].category,mode:PROVIDERS[p].mode,implemented:!!PROVIDERS[p].implemented}))});}
if(action==='list_runs'){const provider=String(b.provider||'').trim();if(provider&&!ALLOWED.includes(provider))return send(res,400,{error:'unsupported_provider'});const runs=await listRuns(venue,provider,b.limit);return send(res,200,{ok:true,venue_id:venue,provider:provider||null,runs:runs||[]});}
const provider=String(b.provider||'').trim();if(!ALLOWED.includes(provider))return send(res,400,{error:'unsupported_provider'});
if(action==='status'){const x=await oneStatus(venue,provider);return send(res,200,{ok:true,provider,implemented:x.implemented,integration:x.integration});}
if(action==='disconnect'){const existing=await existingRow(venue,provider);if(existing)await sb(`/rest/v1/venue_integrations?id=eq.${encodeURIComponent(existing.id)}`,{method:'PATCH',body:JSON.stringify({status:'disconnected',credentials_encrypted:null,error_message:null,last_sync_at:null,metadata:{},updated_at:new Date().toISOString()})});return send(res,200,{ok:true,provider,status:'disconnected'});}
const incoming=b.credentials&&typeof b.credentials==='object'?b.credentials:{};const existing=await existingRow(venue,provider);let old={};if(existing&&existing.credentials_encrypted){try{old=decrypt(existing.credentials_encrypted)||{};}catch(_){old={};}}const credentials={...old};Object.entries(incoming).forEach(([k,v])=>{if(v!==undefined&&v!==null&&String(v).trim()!=='')credentials[k]=String(v).trim();});const fields=configuredFields(credentials);if(!fields.length)return send(res,400,{error:'credentials_required'});const now=new Date().toISOString();const payload={venue_id:venue,provider,status:'disconnected',credentials_encrypted:encrypt(credentials),metadata:{configured_at:now,configured_by:user.id,configured_fields:fields},error_message:null,updated_at:now};if(existing)await sb(`/rest/v1/venue_integrations?id=eq.${encodeURIComponent(existing.id)}`,{method:'PATCH',body:JSON.stringify(payload)});else await sb('/rest/v1/venue_integrations',{method:'POST',body:JSON.stringify(payload)});return send(res,200,{ok:true,provider,status:'disconnected',configured:true,configured_fields:fields,implemented:!!PROVIDERS[provider].implemented});
}catch(e){return send(res,e.status||500,{error:e.message||'integration_error'});}};
