-- Final production hardening migration. Apply after 20260815_production_hardening.sql.
-- Staff sessions are opaque random tokens; staff tables are not directly readable by anon.
create table if not exists public.staff_sessions (id uuid primary key default gen_random_uuid(), token text not null unique, staff_type text not null check (staff_type in ('cook','courier','waiter')), staff_id uuid not null, venue_id uuid not null references public.venues(id) on delete cascade, expires_at timestamptz not null default (now()+interval '12 hours'), created_at timestamptz not null default now());
create index if not exists staff_sessions_token_idx on public.staff_sessions(token);
create index if not exists staff_sessions_venue_idx on public.staff_sessions(venue_id);
alter table public.staff_sessions enable row level security;
revoke all on public.staff_sessions from anon, authenticated;

drop function if exists public.staff_update_order(text,text,text,uuid,text);
create or replace function public.staff_login(p_type text,p_slug text,p_pin text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v venues; sid uuid; sname text; token_value text; begin select * into v from venues where slug=lower(trim(p_slug)) and status='active' limit 1; if v.id is null then raise exception 'venue_not_found'; end if; if p_type='cook' then select id,name into sid,sname from cooks where venue_id=v.id and pin=trim(p_pin) limit 1; elsif p_type='courier' then select id,name into sid,sname from couriers where venue_id=v.id and pin=trim(p_pin) limit 1; elsif p_type='waiter' then select id,name into sid,sname from waiters where venue_id=v.id and pin=trim(p_pin) limit 1; else raise exception 'invalid_staff_type'; end if; if sid is null then raise exception 'invalid_credentials'; end if; token_value:=encode(gen_random_bytes(32),'hex'); insert into staff_sessions(token,staff_type,staff_id,venue_id) values(token_value,p_type,sid,v.id); return jsonb_build_object('token',token_value,'venueId',v.id,'venueName',v.name,'staffId',sid,'staffName',sname,'type',p_type); end $$;
revoke all on function public.staff_login(text,text,text) from public; grant execute on function public.staff_login(text,text,text) to anon,authenticated;

create or replace function public.staff_orders_json(p_token text) returns jsonb language plpgsql security definer set search_path=public as $$ declare s staff_sessions; result jsonb; begin select * into s from staff_sessions where token=p_token and expires_at>now(); if s.id is null then raise exception 'invalid_session'; end if; select coalesce(jsonb_agg(jsonb_build_object('id',o.id,'order_number',o.order_number,'status',o.status,'order_type',o.order_type,'customer_name',o.customer_name,'customer_phone',o.customer_phone,'delivery_address',o.delivery_address,'payment_method',o.payment_method,'total_price',o.total_price,'comment',o.comment,'cook_name',o.cook_name,'courier_name',o.courier_name,'waiter_name',o.waiter_name,'created_at',o.created_at,'updated_at',o.updated_at,'cooking_started_at',o.cooking_started_at,'ready_at',o.ready_at,'items',coalesce((select jsonb_agg(to_jsonb(i)) from order_items i where i.order_id=o.id),'[]'::jsonb),'addons',coalesce((select jsonb_agg(to_jsonb(a)) from order_addons a where a.order_id=o.id),'[]'::jsonb)) order by o.created_at desc),'[]'::jsonb) into result from orders o where o.venue_id=s.venue_id and ((s.staff_type='cook' and o.status in ('new','changed','cooking','ready','delivery')) or (s.staff_type='courier' and o.order_type='delivery' and o.status in ('ready','delivery') and (o.courier_name is null or o.courier_name=(select name from couriers where id=s.staff_id))) or (s.staff_type='waiter' and o.status in ('ready','delivery'))); return result; end $$;
revoke all on function public.staff_orders_json(text) from public; grant execute on function public.staff_orders_json(text) to anon,authenticated;

create or replace function public.staff_history_json(p_token text) returns jsonb language sql security definer set search_path=public as $$ select coalesce(jsonb_agg(to_jsonb(o) order by o.updated_at desc),'[]'::jsonb) from orders o join staff_sessions s on s.venue_id=o.venue_id where s.token=p_token and s.expires_at>now() and ((s.staff_type='cook' and o.cook_name=(select name from cooks where id=s.staff_id)) or (s.staff_type='courier' and o.courier_name=(select name from couriers where id=s.staff_id)) or (s.staff_type='waiter' and o.waiter_name=(select name from waiters where id=s.staff_id))) and o.status in ('done','delivery') limit 50 $$;
revoke all on function public.staff_history_json(text) from public; grant execute on function public.staff_history_json(text) to anon,authenticated;

create or replace function public.staff_update_order(p_token text,p_order_id uuid,p_status text) returns public.orders language plpgsql security definer set search_path=public as $$ declare s staff_sessions; o orders; staff_name text; begin select * into s from staff_sessions where token=p_token and expires_at>now(); if s.id is null then raise exception 'invalid_session'; end if; select * into o from orders where id=p_order_id and venue_id=s.venue_id for update; if o.id is null then raise exception 'order_not_found'; end if; if s.staff_type='cook' then select name into staff_name from cooks where id=s.staff_id; if p_status not in ('cooking','ready','delivery','done') then raise exception 'invalid_cook_status'; end if; update orders set status=p_status,cook_name=coalesce(staff_name,cook_name),cooking_started_at=case when p_status='cooking' and cooking_started_at is null then now() else cooking_started_at end,ready_at=case when p_status='ready' then now() else ready_at end where id=o.id returning * into o; elsif s.staff_type='courier' then select name into staff_name from couriers where id=s.staff_id; if o.order_type<>'delivery' or p_status not in ('delivery','done') then raise exception 'invalid_courier_operation'; end if; update orders set status=p_status,courier_name=staff_name where id=o.id returning * into o; elsif s.staff_type='waiter' then select name into staff_name from waiters where id=s.staff_id; if p_status not in ('done','delivery') then raise exception 'invalid_waiter_status'; end if; update orders set status=p_status,waiter_name=staff_name where id=o.id returning * into o; else raise exception 'invalid_staff_type'; end if; return o; end $$;
revoke all on function public.staff_update_order(text,uuid,text) from public; grant execute on function public.staff_update_order(text,uuid,text) to anon,authenticated;

create or replace function public.staff_logout(p_token text) returns boolean language sql security definer set search_path=public as $$ delete from staff_sessions where token=p_token returning true $$;
revoke all on function public.staff_logout(text) from public; grant execute on function public.staff_logout(text) to anon,authenticated;

create or replace function public.staff_venue_by_slug(p_slug text) returns jsonb language sql security definer set search_path=public as $$ select case when v.id is null then null else jsonb_build_object('id',v.id,'name',v.name,'slug',v.slug,'status',v.status) end from venues v where v.slug=lower(trim(p_slug)) and v.status='active' limit 1 $$;
revoke all on function public.staff_venue_by_slug(text) from public; grant execute on function public.staff_venue_by_slug(text) to anon,authenticated;

create or replace function public.customer_create_order(p_order_id uuid,p_venue_id uuid,p_customer_name text,p_customer_phone text,p_order_type text,p_delivery_address text,p_comment text,p_payment_method text,p_items jsonb) returns public.orders language plpgsql security definer set search_path=public as $$ declare o orders; r jsonb; qty int; price numeric; pname text; total numeric:=0; begin if p_order_type not in ('pickup','delivery') then raise exception 'invalid_order_type'; end if; if p_order_type='delivery' and nullif(trim(coalesce(p_delivery_address,'')),'') is null then raise exception 'address_required'; end if; if jsonb_typeof(coalesce(p_items,'[]'::jsonb))<>'array' or jsonb_array_length(p_items)=0 then raise exception 'items_required'; end if; for r in select * from jsonb_array_elements(p_items) loop select name,price into pname,price from products where id=(r->>'product_id')::uuid and venue_id=p_venue_id and is_available=true; if pname is null then raise exception 'invalid_product'; end if; qty:=greatest(1,least(coalesce((r->>'qty')::int,1),99)); total:=total+price*qty; end loop; if p_order_type='delivery' then total:=total+150; end if; insert into orders(id,venue_id,customer_name,customer_phone,order_type,delivery_address,comment,payment_method,total_price,status) values(p_order_id,p_venue_id,nullif(trim(p_customer_name),''),regexp_replace(p_customer_phone,'[^0-9+]','','g'),p_order_type,nullif(trim(p_delivery_address),''),nullif(trim(p_comment),''),coalesce(p_payment_method,'cash'),total,'new') returning * into o; for r in select * from jsonb_array_elements(p_items) loop select name,price into pname,price from products where id=(r->>'product_id')::uuid and venue_id=p_venue_id; insert into order_items(order_id,product_id,name,price,qty) values(o.id,(r->>'product_id')::uuid,pname,price,greatest(1,least(coalesce((r->>'qty')::int,1),99))); end loop; return o; end $$;
revoke all on function public.customer_create_order(uuid,uuid,text,text,text,text,text,text,jsonb) from public; grant execute on function public.customer_create_order(uuid,uuid,text,text,text,text,text,text,jsonb) to anon,authenticated;

create or replace function public.customer_add_order_addons(p_order_id uuid,p_addons jsonb) returns boolean language plpgsql security definer set search_path=public as $$ declare r jsonb; o orders; addon_price numeric; begin select * into o from orders where id=p_order_id; if o.id is null then raise exception 'order_not_found'; end if; for r in select * from jsonb_array_elements(coalesce(p_addons,'[]'::jsonb)) loop select price into addon_price from products where venue_id=o.venue_id and category='addon' and is_available=true and name=(r->>'name') and price=greatest(0,coalesce((r->>'price')::numeric,0)) limit 1; if addon_price is null then raise exception 'invalid_addon'; end if; insert into order_addons(order_id,name,price,item_name) values(o.id,r->>'name',addon_price,r->>'item_name'); update orders set total_price=total_price+addon_price where id=o.id; end loop; return true; end $$;
revoke all on function public.customer_add_order_addons(uuid,jsonb) from public; grant execute on function public.customer_add_order_addons(uuid,jsonb) to anon,authenticated;

create or replace function public.customer_track_order_json(p_venue_id uuid,p_customer_phone text) returns jsonb language sql security definer set search_path=public as $$ select case when o.id is null then null else jsonb_build_object('id',o.id,'order_number',o.order_number,'status',o.status,'order_type',o.order_type,'customer_name',o.customer_name,'customer_phone',o.customer_phone,'delivery_address',o.delivery_address,'payment_method',o.payment_method,'total_price',o.total_price,'comment',o.comment,'created_at',o.created_at,'updated_at',o.updated_at,'items',coalesce((select jsonb_agg(to_jsonb(i)) from order_items i where i.order_id=o.id),'[]'::jsonb),'addons',coalesce((select jsonb_agg(to_jsonb(a)) from order_addons a where a.order_id=o.id),'[]'::jsonb)) end from (select * from orders where venue_id=p_venue_id and customer_phone=regexp_replace(p_customer_phone,'[^0-9+]','','g') order by created_at desc limit 1) o $$;
revoke all on function public.customer_track_order_json(uuid,text) from public; grant execute on function public.customer_track_order_json(uuid,text) to anon,authenticated;

create or replace function public.customer_change_order_status(p_order_id uuid,p_customer_phone text,p_status text) returns public.orders language plpgsql security definer set search_path=public as $$ declare o orders; begin if p_status not in ('new','cooking') then raise exception 'invalid_customer_status'; end if; select * into o from orders where id=p_order_id and customer_phone=regexp_replace(p_customer_phone,'[^0-9+]','','g') for update; if o.id is null then raise exception 'order_not_found'; end if; update orders set status=p_status where id=o.id returning * into o; return o; end $$;
revoke all on function public.customer_change_order_status(uuid,text,text) from public; grant execute on function public.customer_change_order_status(uuid,text,text) to anon,authenticated;

-- Direct anonymous order table access is intentionally removed. All customer order mutations/reads use the RPCs above.
drop policy if exists "anon insert orders" on public.orders; drop policy if exists "anon select orders" on public.orders; drop policy if exists "anon update orders" on public.orders; drop policy if exists "auth update orders" on public.orders; drop policy if exists "orders_ins" on public.orders; drop policy if exists "orders_insert" on public.orders; drop policy if exists "orders_sel" on public.orders;
