module.exports = async function handler(req,res){
res.setHeader('Cache-Control','no-store');
if(!['GET','POST'].includes(req.method))return res.status(405).json({error:'method_not_allowed'});
const raw=String((req.query&&req.query.url)||(req.body&&req.body.url)||'').trim();if(!raw)return res.status(400).json({error:'url_required'});
let start;try{start=new URL(/^https?:\/\//i.test(raw)?raw:'https://'+raw)}catch{return res.status(400).json({error:'invalid_url'})}
const host=start.hostname.replace(/^www\./,'').toLowerCase();
if(!/^https?:$/.test(start.protocol)||/^(localhost|127\.0\.0\.1|0\.0\.0\.0|169\.254\.169\.254)$/.test(host)||/^10\.|^192\.168\.|^172\.(1[6-9]|2\d|3[01])\./.test(host))return res.status(400).json({error:'private_url_not_allowed'});
const H={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131 Safari/537.36 QR-Menu/11.0','Accept':'text/html,application/xhtml+xml,text/plain;q=0.9,*/*;q=0.8','Accept-Language':'ru-RU,ru;q=0.9,en;q=0.8'};
const clean=(v,n=1200)=>String(v||'').replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').trim().slice(0,n),abs=(u,b)=>{try{return new URL(String(u||''),b).href}catch{return null}},same=u=>{try{return new URL(u).hostname.replace(/^www\./,'').toLowerCase()===host}catch{return false}};
const money=s=>{const m=String(s).replace(/\u00a0/g,' ').match(/(?:^|\s)(\d{1,6}(?:[ .]\d{3})*(?:[.,]\d{1,2})?)\s*(?:₽|р\.?|руб\.?|rub)(?=\s|$)/i);return m?Number(m[1].replace(/[ .]/g,'').replace(',','.')):0};
const weight=s=>/^\s*\d+(?:[.,]\d+)?\s*(?:г|гр|кг|мл|л|шт)\.?\s*$/i.test(String(s));
const asset=u=>/\.(?:css|js|jpg|jpeg|png|gif|webp|svg|ico|woff2?|ttf|mp4|mp3|zip)(?:[?#].*)?$/i.test(u);
const pdf=u=>/\.pdf(?:[?#].*)?$/i.test(u);
const noise=/^(главная|меню|каталог|о нас|о компании|интерьер|доставка|акции|новости|контакты|отзывы|вакансии|резерв стола|забронировать|заказать|корзина|войти|регистрация|личный кабинет|политика|согласие|обратная связь|подробнее|читать далее|купить|добавить|далее|назад|открыть|закрыть)$/i;
const category=/^(?:.{0,60}(?:закуск|салат|суп|бургер|паст|пицц|ролл|суш|десерт|напит|завтрак|гарнир|соус|мяс|рыб|кофе|чай|бар|горяч|детск).{0,60})$/i;
async function fetchPage(u){const r=await fetch(u,{redirect:'follow',headers:H,signal:AbortSignal.timeout(16000)});if(!r.ok)throw Error('http_'+r.status);const ct=r.headers.get('content-type')||'';if(pdf(u)||/pdf/i.test(ct))return{url:r.url||u,type:'pdf',html:''};if(!/html|xhtml|text/i.test(ct))throw Error('not_html');return{url:r.url||u,type:'html',html:Buffer.from(await r.arrayBuffer()).subarray(0,12*1024*1024).toString('utf8')}}
function decode(s){return String(s).replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>')}
function lines(h){let s=h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<!--[^]*?-->/g,' ');s=s.replace(/<br\s*\/?>/gi,'\n').replace(/<\/(?:div|p|li|section|article|h[1-6]|tr|td|th|a|button|label|option)>/gi,'\n').replace(/<[^>]+>/g,' ');return decode(s).split(/\r?\n+/).map(x=>clean(x,500)).filter(x=>x.length>0)}
// Crawl the site's internal graph instead of relying on guessed menu URLs.
const queue=[start.href],seenUrls=new Set(queue),pages=[],MAX=60,MAX_QUEUE=300;
while(queue.length&&pages.length<MAX){const u=queue.shift();try{const p=await fetchPage(u);pages.push(p);if(p.type!=='html')continue;const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(p.html))&&seenUrls.size<MAX_QUEUE){const v=abs(m[1],p.url);if(!v||!same(v)||asset(v)||v.includes('#')||seenUrls.has(v))continue;const text=clean(m[2].replace(/<[^>]+>/g,' '),200);const signal=(text+' '+v).toLowerCase();const important=/(меню|menu|каталог|catalog|блюд|dish|food|цены|price|еда|ресторан|кафе|бар|пицц|суш|ролл|десерт|напит|завтрак|меню)/i.test(signal);if(important||queue.length<20){seenUrls.add(v);queue.push(v)}}}catch{}}
function analyse(p){if(p.type!=='html')return{p,ls:[],score:0,prices:0,weights:0,clusters:0};const ls=lines(p.html);let prices=0,weights=0,clusters=0;for(let i=0;i<ls.length;i++){if(money(ls[i])){prices++;let plausible=0;for(let j=1;j<=12&&i+j<ls.length;j++){const x=ls[i+j];if(money(x))break;if(weight(x))continue;if(noise.test(x))continue;if(category.test(x)&&x.length<90)continue;if(x.length>=3&&x.length<=180)plausible++}if(plausible>0)clusters++}if(weight(ls[i]))weights++}const heading=/(меню|menu|каталог|catalog|блюд|food|dish|цены|price|еда)/i.test(p.url+' '+ls.slice(0,80).join(' '));return{p,ls,score:prices*2+weights+clusters*5+(heading?8:0),prices,weights,clusters}}
const ranked=pages.map(analyse).sort((a,b)=>b.score-a.score);const candidates=ranked.filter(x=>x.clusters>=2&&x.prices>=2).slice(0,15);
const products=[],keys=new Set(),cats=new Set();
function add(name,p,desc,cat,img){name=clean(name,180);p=Number(p||0);if(!name||!p||p<1||p>1000000||weight(name)||noise.test(name)||name.length<3||/^\d+$/.test(name))return;const key=(clean(cat||'main',100)+'|'+name).toLowerCase();if(keys.has(key))return;keys.add(key);products.push({name,description:clean(desc,1200)||null,price:p,category:clean(cat||'main',100),image_url:img||null,is_available:true,applies_to:'all'})}
for(const c of candidates){let cat='main';for(let i=0;i<c.ls.length;i++){const l=c.ls[i];if(category.test(l)&&l.length<90&&!money(l)&&!weight(l)&&!noise.test(l)){cat=l;cats.add(l);continue}const p=money(l);if(!p)continue;let name='',ni=-1;for(let j=1;j<=12&&i+j<c.ls.length;j++){const x=c.ls[i+j];if(money(x)||weight(x)||noise.test(x))continue;if(category.test(x)&&x.length<90)break;if(x.length>=3&&x.length<=180&&!/^\W+$/.test(x)){name=x;ni=i+j;break}}if(!name)for(let j=1;j<=12&&i-j>=0;j++){const x=c.ls[i-j];if(money(x)||weight(x)||noise.test(x))continue;if(category.test(x)&&x.length<90)break;if(x.length>=3&&x.length<=180&&!/^\W+$/.test(x)){name=x;ni=i-j;break}}if(name){let desc='';if(ni>i)for(let j=ni+1;j<Math.min(ni+8,c.ls.length);j++){const x=c.ls[j];if(money(x)||weight(x)||noise.test(x)||category.test(x)&&x.length<90)break;if(x.length>=8)desc+=(desc?' ':'')+x}add(name,p,desc,cat,null)}}}
// Supplement with structured product data, but never let it alone declare a menu.
for(const p of pages.filter(x=>x.type==='html')){const ss=p.html.match(/<script[^>]+type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi)||[];for(const s of ss){try{const d=JSON.parse(s.replace(/^.*?>/,'').replace(/<\/script>.*$/i,''));const walk=x=>{if(!x)return;if(Array.isArray(x)){x.forEach(walk);return}if(typeof x!=='object')return;const o=Array.isArray(x.offers)?x.offers[0]:x.offers;const pr=o?.price??x.price;if(x.name&&pr&&Number(pr)>0)add(x.name,pr,x.description,x.category,typeof x.image==='string'?abs(x.image,p.url):null);Object.values(x).forEach(walk)};walk(d)}catch{}}}
// A menu is validated only when multiple independent item clusters were found. One accidental product is never enough.
const uniqueNames=new Set(products.map(x=>x.name.toLowerCase()));
const validated=products.length>=5&&candidates.length>0&&candidates.some(x=>x.clusters>=3&&x.prices>=3);
let business={};for(const p of pages.filter(x=>x.type==='html')){const ss=p.html.match(/<script[^>]+type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi)||[];for(const s of ss){try{const d=JSON.parse(s.replace(/^.*?>/,'').replace(/<\/script>.*$/i,''));const q=[...(Array.isArray(d)?d:[d])];while(q.length){const x=q.shift();if(!x||typeof x!=='object')continue;if(Array.isArray(x['@graph']))q.push(...x['@graph']);if(/restaurant|cafe|bar|foodestablishment|localbusiness/i.test(String(x['@type']||''))){business=x;break}}}catch{}}if(business.name)break}
const home=pages[0]?.type==='html'?lines(pages[0].html).join('\n'):'';const title=clean((pages[0]?.html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[,''])[1].replace(/<[^>]+>/g,' '),180);const phone=clean(business.telephone||(home.match(/(?:\+7|8)[\s()\-\d]{9,}/)||[''])[0],80);const address=clean(typeof business.address==='string'?business.address:[business.address?.streetAddress,business.address?.addressLocality,business.address?.addressRegion,business.address?.postalCode].filter(Boolean).join(', '),500);
return res.status(200).json({source_url:start.href,venue:{name:clean(business.name||title||host.split('.')[0],180),description:clean(business.description||'',1200),address,phone,website_url:start.href,logo_url:null,opening_hours:business.openingHours||business.openingHoursSpecification||null},products:products.slice(0,500),meta:{menu_found:validated,products_found:products.length,pages_checked:pages.length,pages_discovered:seenUrls.size,menu_pages_detected:candidates.slice(0,15).map(x=>({url:x.p.url,score:x.score,prices:x.prices,weights:x.weights,clusters:x.clusters})),best_menu_page:candidates[0]?.p.url||null,validation:validated?'validated':'not_validated',message:validated?'Меню найдено и прошло проверку.':'Меню не подтверждено: недостаточно согласованных позиций.'}})};
